(function(c){"function"===typeof define&&define.amd?define(["jquery","./grid.base","./grid.common"],c):"object"===typeof exports?c(require("jquery")):c(jQuery)})(function(c){var p=c.jgrid;c.fn.jqFilter=function(e){if("string"===typeof e){var t=c.fn.jqFilter[e];if(!t)throw"jqFilter - No such method: "+e;var C=c.makeArray(arguments).slice(1);return t.apply(this,C)}var a=c.extend(!0,{filter:null,columns:[],onChange:null,afterRedraw:null,checkValues:null,error:!1,errmsg:"",errorcheck:!0,showQuery:!0,
sopt:null,ops:[],operands:null,numopts:"eq ne lt le gt ge nu nn in ni".split(" "),stropts:"eq ne bw bn ew en cn nc nu nn in ni".split(" "),strarr:["text","string","blob"],groupOps:[{op:"AND",text:"AND"},{op:"OR",text:"OR"}],groupButton:!0,ruleButtons:!0,direction:"ltr"},p.filter,e||{});return this.each(function(){if(!this.filter){this.p=a;if(null===a.filter||void 0===a.filter)a.filter={groupOp:a.groupOps[0].op,rules:[],groups:[]};var e,t=a.columns.length,g,E=/msie/i.test(navigator.userAgent)&&!window.opera,
x=function(){return c("#"+p.jqID(a.id))[0]||null},r=function(f,a){return c(x()).jqGrid("getGuiStyles",f,a||"")},A=function(f){return c(x()).jqGrid("getGridRes","search."+f)},F=function(c){var a=x(),b=a.p.iColByName[c];if(void 0!==b)return{cm:a.p.colModel[b],iCol:b};b=a.p.iPropByName[c];return void 0!==b?{cm:a.p.colModel[b],iCol:b,isAddProp:!0}:{cm:null,iCol:-1}},D=r("states.error"),C=r("dialog.content");a.initFilter=c.extend(!0,{},a.filter);if(t){for(e=0;e<t;e++)g=a.columns[e],g.stype?g.inputtype=
g.stype:g.inputtype||(g.inputtype="text"),g.sorttype?g.searchtype=g.sorttype:g.searchtype||(g.searchtype="string"),void 0===g.hidden&&(g.hidden=!1),g.label||(g.label=g.name),g.cmName=g.name,g.index&&(g.name=g.index),g.hasOwnProperty("searchoptions")||(g.searchoptions={}),g.hasOwnProperty("searchrules")||(g.searchrules={});a.showQuery&&c(this).append("<table class='queryresult "+C+"' style='display:block;max-width:440px;border:0px none;' dir='"+a.direction+"'><tbody><tr><td class='query'></td></tr></tbody></table>");
var G=function(f,l){var b=[!0,""],h=x();if(c.isFunction(l.searchrules))b=l.searchrules.call(h,f,l);else if(p&&p.checkValues)try{b=p.checkValues.call(h,f,-1,l.searchrules,l.label)}catch(u){}b&&b.length&&!1===b[0]&&(a.error=!b[0],a.errmsg=b[1])};this.onchange=function(){a.error=!1;a.errmsg="";return c.isFunction(a.onChange)?a.onChange.call(this,a):!1};this.reDraw=function(){c("table.group:first",this).remove();var f=this.createTableForGroup(a.filter,null);c(this).append(f);c.isFunction(a.afterRedraw)&&
a.afterRedraw.call(this,a)};this.createTableForGroup=function(f,l){var b=this,h,u=c("<table class='"+r("searchDialog.operationGroup","group")+"' style='border:0px none;'><tbody></tbody></table>"),d="left";"rtl"===a.direction&&(d="right",u.attr("dir","rtl"));null===l&&u.append("<tr class='error' style='display:none;'><th colspan='5' class='"+D+"' align='"+d+"'></th></tr>");var k=c("<tr></tr>");u.append(k);d=c("<th colspan='5' align='"+d+"'></th>");k.append(d);if(!0===a.ruleButtons){var g=c("<select class='"+
r("searchDialog.operationSelect","opsel")+"'></select>");d.append(g);var k="",e;for(h=0;h<a.groupOps.length;h++)e=f.groupOp===b.p.groupOps[h].op?" selected='selected'":"",k+="<option value='"+b.p.groupOps[h].op+"'"+e+">"+b.p.groupOps[h].text+"</option>";g.append(k).bind("change",function(){f.groupOp=c(g).val();b.onchange()})}k="<span></span>";a.groupButton&&(k=c("<input type='button' value='+ {}' title='"+A("addGroupTitle")+"' class='"+r("searchDialog.addGroupButton","add-group")+"'/>"),k.bind("click",
function(){void 0===f.groups&&(f.groups=[]);f.groups.push({groupOp:a.groupOps[0].op,rules:[],groups:[]});b.reDraw();b.onchange();return!1}));d.append(k);if(!0===a.ruleButtons){var k=c("<input type='button' value='+' title='"+A("addRuleTitle")+"' class='"+r("searchDialog.addRuleButton","add-rule ui-add")+"'/>"),n;k.bind("click",function(){var a,d,k;void 0===f.rules&&(f.rules=[]);for(h=0;h<b.p.columns.length;h++)if(a=void 0===b.p.columns[h].search?!0:b.p.columns[h].search,d=!0===b.p.columns[h].hidden,
(k=!0===b.p.columns[h].searchoptions.searchhidden)&&a||a&&!d){n=b.p.columns[h];break}a=n.searchoptions.sopt?n.searchoptions.sopt:b.p.sopt?b.p.sopt:-1!==c.inArray(n.searchtype,b.p.strarr)?b.p.stropts:b.p.numopts;f.rules.push({field:n.name,op:a[0],data:""});b.reDraw();return!1});d.append(k)}null!==l&&(k=c("<input type='button' value='-' title='"+A("deleteGroupTitle")+"' class='"+r("searchDialog.deleteGroupButton","delete-group")+"'/>"),d.append(k),k.bind("click",function(){for(h=0;h<l.groups.length;h++)if(l.groups[h]===
f){l.groups.splice(h,1);break}b.reDraw();b.onchange();return!1}));if(void 0!==f.groups)for(h=0;h<f.groups.length;h++)d=c("<tr></tr>"),u.append(d),k=c("<td class='first'></td>"),d.append(k),k=c("<td colspan='4'></td>"),k.append(this.createTableForGroup(f.groups[h],f)),d.append(k);void 0===f.groupOp&&(f.groupOp=b.p.groupOps[0].op);if(void 0!==f.rules)for(h=0;h<f.rules.length;h++)u.append(this.createTableRowForRule(f.rules[h],f));return u};this.createTableRowForRule=function(f,l){var b=this,h=x(),g=
c("<tr></tr>"),d,k,e,m="",n;g.append("<td class='first'></td>");var q=c("<td class='columns'></td>");g.append(q);var t=c("<select class='"+r("searchDialog.label","selectLabel")+"'></select>"),w,v=[];q.append(t);t.bind("change",function(){f.field=c(t).val();var a=c(this).parents("tr:first"),d,e;for(e=0;e<b.p.columns.length;e++)if(b.p.columns[e].name===f.field){d=b.p.columns[e];break}if(d){var l=c.extend({},d.editoptions||{},d.searchoptions||{},F(d.cmName),{id:p.randId(),name:d.name,mode:"search"});
E&&"text"===d.inputtype&&!l.size&&(l.size=10);var g=p.createEl.call(h,d.inputtype,l,"",!0,b.p.ajaxSelectOptions||{},!0);c(g).addClass(r("searchDialog.elem","input-elm"));k=l.sopt?l.sopt:b.p.sopt?b.p.sopt:-1!==c.inArray(d.searchtype,b.p.strarr)?b.p.stropts:b.p.numopts;d="";var u=0,m,n;v=[];c.each(b.p.ops,function(){v.push(this.oper)});b.p.cops&&c.each(b.p.cops,function(b){v.push(b)});for(e=0;e<k.length;e++)n=k[e],w=c.inArray(k[e],v),-1!==w&&(m=b.p.ops[w],m=void 0!==m?m.text:b.p.cops[n].text,0===u&&
(f.op=n),d+="<option value='"+n+"'>"+m+"</option>",u++);c(".selectopts",a).empty().append(d);c(".selectopts",a)[0].selectedIndex=0;p.msie&&9>p.msiever()&&(e=parseInt(c("select.selectopts",a)[0].offsetWidth,10)+1,c(".selectopts",a).width(e),c(".selectopts",a).css("width","auto"));c(".data",a).empty().append(g);p.bindEv.call(h,g,l);c(".input-elm",a).bind("change",function(a){a=a.target;f.data="SPAN"===a.nodeName.toUpperCase()&&l&&c.isFunction(l.custom_value)?l.custom_value.call(h,c(a).children(".customelement:first"),
"get"):a.value;b.onchange()});setTimeout(function(){f.data=c(g).val();b.onchange()},0)}});var q=0,y,z;for(d=0;d<b.p.columns.length;d++)if(n=void 0===b.p.columns[d].search?!0:b.p.columns[d].search,y=!0===b.p.columns[d].hidden,(z=!0===b.p.columns[d].searchoptions.searchhidden)&&n||n&&!y)n="",f.field===b.p.columns[d].name&&(n=" selected='selected'",q=d),m+="<option value='"+b.p.columns[d].name+"'"+n+">"+b.p.columns[d].label+"</option>";t.append(m);m=c("<td class='operators'></td>");g.append(m);e=a.columns[q];
E&&"text"===e.inputtype&&!e.searchoptions.size&&(e.searchoptions.size=10);q=p.createEl.call(h,e.inputtype,c.extend({},e.editoptions||{},e.searchoptions||{},F(e.cmName),{id:p.randId(),name:e.name}),f.data,!0,b.p.ajaxSelectOptions||{},!0);if("nu"===f.op||"nn"===f.op)c(q).attr("readonly","true"),c(q).attr("disabled","true");var B=c("<select class='"+r("searchDialog.operator","selectopts")+"'></select>");m.append(B);B.bind("change",function(){f.op=c(B).val();var a=c(this).parents("tr:first"),a=c(".input-elm",
a)[0];"nu"===f.op||"nn"===f.op?(f.data="","SELECT"!==a.tagName.toUpperCase()&&(a.value=""),a.setAttribute("readonly","true"),a.setAttribute("disabled","true")):("SELECT"===a.tagName.toUpperCase()&&(f.data=a.value),a.removeAttribute("readonly"),a.removeAttribute("disabled"));b.onchange()});k=e.searchoptions.sopt?e.searchoptions.sopt:b.p.sopt?b.p.sopt:-1!==c.inArray(e.searchtype,b.p.strarr)?b.p.stropts:b.p.numopts;m="";c.each(b.p.ops,function(){v.push(this.oper)});b.p.cops&&c.each(b.p.cops,function(b){v.push(b)});
for(d=0;d<k.length;d++)z=k[d],w=c.inArray(k[d],v),-1!==w&&(y=b.p.ops[w],n=f.op===z?" selected='selected'":"",m+="<option value='"+z+"'"+n+">"+(void 0!==y?y.text:b.p.cops[z].text)+"</option>");B.append(m);m=c("<td class='data'></td>");g.append(m);m.append(q);p.bindEv.call(h,q,e.searchoptions);c(q).addClass(r("searchDialog.elem","input-elm")).bind("change",function(){f.data="custom"===e.inputtype?e.searchoptions.custom_value.call(h,c(this).children(".customelement:first"),"get"):c(this).val();b.onchange()});
m=c("<td></td>");g.append(m);!0===a.ruleButtons&&(q=c("<input type='button' value='-' title='"+A("deleteRuleTitle")+"' class='"+r("searchDialog.deleteRuleButton","delete-rule ui-del")+"'/>"),m.append(q),q.bind("click",function(){for(d=0;d<l.rules.length;d++)if(l.rules[d]===f){l.rules.splice(d,1);break}b.reDraw();b.onchange();return!1}));return g};this.getStringForGroup=function(a){var c="(",b;if(void 0!==a.groups)for(b=0;b<a.groups.length;b++){1<c.length&&(c+=" "+a.groupOp+" ");try{c+=this.getStringForGroup(a.groups[b])}catch(h){alert(h)}}if(void 0!==
a.rules)try{for(b=0;b<a.rules.length;b++)1<c.length&&(c+=" "+a.groupOp+" "),c+=this.getStringForRule(a.rules[b])}catch(h){alert(h)}c+=")";return"()"===c?"":c};this.getStringForRule=function(f){var e="",b="",h,g,d=f.data,k;for(h=0;h<a.ops.length;h++)if(a.ops[h].oper===f.op){e=a.operands.hasOwnProperty(f.op)?a.operands[f.op]:"";b=a.ops[h].oper;break}if(""===b&&null!=a.cops)for(k in a.cops)if(a.cops.hasOwnProperty(k)&&(b=k,e=a.cops[k].operand,c.isFunction(a.cops[k].buildQueryValue)))return a.cops[k].buildQueryValue.call(a,
{cmName:f.field,searchValue:d,operand:e});for(h=0;h<a.columns.length;h++)if(a.columns[h].name===f.field){g=a.columns[h];break}if(null==g)return"";if("bw"===b||"bn"===b)d+="%";if("ew"===b||"en"===b)d="%"+d;if("cn"===b||"nc"===b)d="%"+d+"%";if("in"===b||"ni"===b)d=" ("+d+")";a.errorcheck&&G(f.data,g);return-1!==c.inArray(g.searchtype,["int","integer","float","number","currency"])||"nn"===b||"nu"===b?f.field+" "+e+" "+d:f.field+" "+e+' "'+d+'"'};this.resetFilter=function(){a.filter=c.extend(!0,{},a.initFilter);
this.reDraw();this.onchange()};this.hideError=function(){c("th."+D,this).html("");c("tr.error",this).hide()};this.showError=function(){c("th."+D,this).html(a.errmsg);c("tr.error",this).show()};this.toUserFriendlyString=function(){return this.getStringForGroup(a.filter)};this.toString=function(){function c(b){var a="(",g;if(void 0!==b.groups)for(g=0;g<b.groups.length;g++)1<a.length&&(a="OR"===b.groupOp?a+" || ":a+" && "),a+=c(b.groups[g]);if(void 0!==b.rules)for(g=0;g<b.rules.length;g++){1<a.length&&
(a="OR"===b.groupOp?a+" || ":a+" && ");var d=b.rules[g];if(e.p.errorcheck){for(var k=void 0,p=void 0,k=0;k<e.p.columns.length;k++)if(e.p.columns[k].name===d.field){p=e.p.columns[k];break}p&&G(d.data,p)}a+=d.op+"(item."+d.field+",'"+d.data+"')"}a+=")";return"()"===a?"":a}var e=this;return c(a.filter)};this.reDraw();if(a.showQuery)this.onchange();this.filter=!0}}})};c.extend(c.fn.jqFilter,{toSQLString:function(){var c="";this.each(function(){c=this.toUserFriendlyString()});return c},filterData:function(){var c;
this.each(function(){c=this.p.filter});return c},getParameter:function(c){return void 0!==c&&this.p.hasOwnProperty(c)?this.p[c]:this.p},resetFilter:function(){return this.each(function(){this.resetFilter()})},addFilter:function(e){"string"===typeof e&&(e=c.parseJSON(e));this.each(function(){this.p.filter=e;this.reDraw();this.onchange()})}})});
//# sourceMappingURL=grid.filter.map
