(function(b){"function"===typeof define&&define.amd?define(["jquery","./grid.base"],b):"object"===typeof exports?b(require("jquery")):b(jQuery)})(function(b){var p=b.jgrid,w=p.jqID,m=b.fn.jqGrid,y=function(){var a=b.makeArray(arguments);a[0]="subGrid"+a[0].charAt(0).toUpperCase()+a[0].substring(1);a.unshift("");a.unshift("");a.unshift(this.p);return p.feedback.apply(this,a)},r=function(a,e){return this.each(function(){if(this.grid&&null!=a&&!0===this.p.subGrid){var d=b(this).jqGrid("getInd",a,!0);
b(d).find(">td."+e).trigger("click")}})};p.extend({setSubGrid:function(){return this.each(function(){var a=this.p,e=a.subGridModel[0];a.subGridOptions=b.extend({expandOnLoad:!1,delayOnLoad:50,selectOnExpand:!1,selectOnCollapse:!1,reloadOnExpand:!0},a.subGridOptions||{});a.colNames.unshift("");a.colModel.unshift({name:"subgrid",width:p.cell_width?a.subGridWidth+a.cellLayout:a.subGridWidth,labelClasses:"jqgh_subgrid",sortable:!1,resizable:!1,hidedlg:!0,search:!1,fixed:!0,frozen:!0});if(e)for(e.align=
b.extend([],e.align||[]),a=0;a<e.name.length;a++)e.align[a]=e.align[a]||"left"})},addSubGridCell:function(a,e,d,c){var f=this[0],l=f.p.subGridOptions;d=b.isFunction(l.hasSubgrid)?l.hasSubgrid.call(f,{rowid:d,iRow:e,iCol:a,data:c}):!0;return null==f||null==f.p||null==l?"":"<td role='gridcell' class='"+m.getGuiStyles.call(this,"subgrid.tdStart",d?"ui-sgcollapsed sgcollapsed":"")+"' "+f.formatCol(a,e)+">"+(d?"<div class='"+m.getGuiStyles.call(this,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+
m.getGuiStyles.call(this,"subgrid.button","sgbutton")+"'><span class='"+p.mergeCssClasses(l.commonIconClass,l.plusicon)+"'></span></a></div>":"&nbsp;")+"</td>"},addSubGrid:function(a,e){return this.each(function(){var d=this,c=d.p,f=c.subGridModel[0],l=function(b,c){return m.getGuiStyles.call(d,"subgrid."+b,c||"")},r=l("thSubgrid","ui-th-subgrid ui-th-column ui-th-"+c.direction),z=l("rowSubTable","ui-subtblcell"),C=l("row","ui-subgrid ui-row-"+c.direction),D=l("tdWithIcon","subgrid-cell"),E=l("tdData",
"subgrid-data"),t=function(c,a,d){d=f.align[d];a=b("<td"+(d?" style='text-align:"+d+";'":"")+"></td>").html(a);c.append(a)},A=function(a,d){var g=c.xmlReader.subgrid;b(g.root+" "+g.row,a).each(function(){var c,a,n=b("<tr class='"+z+"'></tr>");if(!0===g.repeatitems)b(g.cell,this).each(function(c){t(n,b(this).text()||"&#160;",c)});else if(c=f.mapping||f.name)for(a=0;a<c.length;a++)t(n,b(c[a],this).text()||"&#160;",a);d.append(n)})},B=function(a,d){var g,k,h,n,e,l=c.jsonReader.subgrid,m=p.getAccessor(a,
l.root);if(null!=m)for(k=0;k<m.length;k++){e=m[k];g=b("<tr class='"+z+"'></tr>");if(!0===l.repeatitems)for(l.cell&&(e=e[l.cell]),h=0;h<e.length;h++)t(g,e[h]||"&#160;",h);else if(n=f.mapping||f.name,n.length)for(h=0;h<n.length;h++)t(g,e[n[h]]||"&#160;",h);d.append(g)}},u=function(a,e,g){var k,h;k=l("legacyTable","ui-jqgrid-legacy-subgrid"+(!0===c.altRows&&b(d).jqGrid("isBootstrapGuiStyle")?" table-striped":""));var n=b("<table"+(k?" class='"+k+"'":"")+"><thead></thead><tbody></tbody></table>"),m=b("<tr></tr>");
for(h=0;h<f.name.length;h++)k=b("<th class='"+r+"'></th>").html(f.name[h]).width(f.width[h]),m.append(k);m.appendTo(n[0].tHead);g(a,b(n[0].tBodies[0]));b("#"+w(c.id+"_"+e)).append(n);d.grid.hDiv.loading=!1;b("#load_"+w(c.id)).hide();return!1},F=function(a){var e=b(a).attr("id"),g={nd_:(new Date).getTime()},k,h;g[c.prmNames.subgridid]=e;if(!f)return!1;if(f.params)for(h=0;h<f.params.length;h++)k=c.iColByName[f.params[h]],void 0!==k&&(g[c.colModel[k].name]=b(a.cells[k]).text().replace(/\&#160\;/ig,""));
if(!d.grid.hDiv.loading)switch(d.grid.hDiv.loading=!0,b("#load_"+w(c.id)).show(),c.subgridtype||(c.subgridtype=c.datatype),b.isFunction(c.subgridtype)?c.subgridtype.call(d,g):c.subgridtype=c.subgridtype.toLowerCase(),c.subgridtype){case "xml":case "json":b.ajax(b.extend({type:c.mtype,url:b.isFunction(c.subGridUrl)?c.subGridUrl.call(d,g):c.subGridUrl,dataType:c.subgridtype,data:p.serializeFeedback.call(d,c.serializeSubGridData,"jqGridSerializeSubGridData",g),complete:function(a){"xml"===c.subgridtype?
u(a.responseXML,e,A):(a=b.parseJSON(a.responseText),u(a,e,B))}},p.ajaxOptions,c.ajaxSubgridOptions||{}))}return!1},G=function(){var e=b(this).parent("tr")[0],f=e.nextSibling,g=e.id,k=c.id+"_"+g,h=function(a){return p.mergeCssClasses(c.subGridOptions.commonIconClass,c.subGridOptions[a])},l=1;b.each(c.colModel,function(){!0!==this.hidden&&"rn"!==this.name&&"cb"!==this.name||l++});if(b(this).hasClass("sgcollapsed")){if(!0===c.subGridOptions.reloadOnExpand||!1===c.subGridOptions.reloadOnExpand&&!b(f).hasClass("ui-subgrid")){f=
1<=a?"<td colspan='"+a+"'>&#160;</td>":"";if(!y.call(d,"beforeExpand",k,g))return;b(e).after("<tr role='row' class='"+C+"'>"+f+"<td class='"+D+"'><span class='"+h("openicon")+"'></span></td><td colspan='"+parseInt(c.colNames.length-l,10)+"' class='"+E+"'><div id='"+k+"' class='tablediv'></div></td></tr>");b(d).triggerHandler("jqGridSubGridRowExpanded",[k,g]);b.isFunction(c.subGridRowExpanded)?c.subGridRowExpanded.call(d,k,g):F(e)}else b(f).show();b(this).html("<div class='"+m.getGuiStyles.call(d,
"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+m.getGuiStyles.call(d,"subgrid.button","sgbutton")+"'><span class='"+h("minusicon")+"'></span></a></div>").removeClass("sgcollapsed").addClass("sgexpanded");c.subGridOptions.selectOnExpand&&b(d).jqGrid("setSelection",g)}else if(b(this).hasClass("sgexpanded")){if(!y.call(d,"beforeCollapse",k,g))return;!0===c.subGridOptions.reloadOnExpand?b(f).remove(".ui-subgrid"):b(f).hasClass("ui-subgrid")&&b(f).hide();b(this).html("<div class='"+m.getGuiStyles.call(d,
"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+m.getGuiStyles.call(d,"subgrid.button","sgbutton")+"'><span class='"+h("plusicon")+"'></span></a></div>").removeClass("sgexpanded").addClass("sgcollapsed");c.subGridOptions.selectOnCollapse&&b(d).jqGrid("setSelection",g)}return!1},x,q,v=1;if(d.grid){x=d.rows.length;void 0!==e&&0<e&&(v=e,x=e+1);for(;v<x;)q=d.rows[v],b(q).hasClass("jqgrow")&&(q=b(q.cells[a]),q.hasClass("ui-sgcollapsed")&&(c.scroll&&q.unbind("click"),q.bind("click",G))),
v++;!0===c.subGridOptions.expandOnLoad&&b(d.rows).filter(".jqgrow").each(function(a,c){b(c.cells[0]).click()});d.subGridXml=function(a,b){u(a,b,A)};d.subGridJson=function(a,b){u(a,b,B)}}})},expandSubGridRow:function(a){return r.call(this,a,"sgcollapsed")},collapseSubGridRow:function(a){return r.call(this,a,"sgexpanded")},toggleSubGridRow:function(a){return r.call(this,a,"ui-sgcollapsed")}})});
//# sourceMappingURL=grid.subgrid.map
