(function(a){"function"===typeof define&&define.amd?define(["jquery","./grid.base","./jquery.fmatter","./grid.common"],a):"object"===typeof exports?a(require("jquery")):a(jQuery)})(function(a){var B=a.jgrid,S=B.jqID,M=a.fn.jqGrid,E=M.getGuiStyles,V=M.getGridRes;B.extend({getColProp:function(a){var b=this[0];return null!=b&&b.grid&&(a=b.p.iColByName[a],void 0!==a)?b.p.colModel[a]:{}},setColProp:function(e,b){return this.each(function(){var d=this.p,c;this.grid&&null!=d&&b&&(c=d.iColByName[e],void 0!==
c&&a.extend(!0,d.colModel[c],b))})},sortGrid:function(a,b,d){return this.each(function(){var c=this.grid,g=this.p,h=g.colModel,m=h.length,n,f,p=!1;if(c)for(a||(a=g.sortname),"boolean"!==typeof b&&(b=!1),f=0;f<m;f++)if(n=h[f],n.index===a||n.name===a){!0===g.frozenColumns&&!0===n.frozen&&(p=c.fhDiv.find("#"+g.id+"_"+a));p&&0!==p.length||(p=c.headers[f].el);c=n.sortable;("boolean"!==typeof c||c)&&this.sortData("jqgh_"+g.id+"_"+a,f,b,d,p);break}})},clearBeforeUnload:function(){return this.each(function(){var e=
this.p,b=this.grid,d,c=B.clearArray,g=Object.prototype.hasOwnProperty;a.isFunction(b.emptyRows)&&b.emptyRows.call(this,!0,!0);a(document).unbind("mouseup.jqGrid"+e.id);a(b.hDiv).unbind("mousemove");a(this).unbind();var h,m=b.headers.length;for(h=0;h<m;h++)b.headers[h].el=null;for(d in b)b.hasOwnProperty(d)&&(b.propOrMethod=null);b="formatCol sortData updatepager refreshIndex setHeadCheckBox constructTr clearToolbar fixScrollOffsetAndhBoxPadding rebuildRowIndexes modalAlert toggleToolbar triggerToolbar formatter addXmlData addJSONData ftoolbar _inlinenav nav grid p".split(" ");
m=b.length;for(h=0;h<m;h++)g.call(this,b[h])&&(this[b[h]]=null);this._index={};c(e.data);c(e.lastSelectedData);c(e.selarrrow);c(e.savedRow)})},GridDestroy:function(){return this.each(function(){var e=this.p;if(this.grid&&null!=e){e.pager&&a(e.pager).remove();try{a("#alertmod_"+e.idSel).remove(),a(this).jqGrid("clearBeforeUnload"),a(e.gBox).remove()}catch(b){}}})},GridUnload:function(){return this.each(function(){var e=a(this),b=this.p,d=a.fn.jqGrid;this.grid&&(e.removeClass(d.getGuiStyles.call(e,
"grid","ui-jqgrid-btable")),b.pager&&a(b.pager).empty().removeClass(d.getGuiStyles.call(e,"pagerBottom","ui-jqgrid-pager")).removeAttr("style").removeAttr("dir"),e.jqGrid("clearBeforeUnload"),e.removeAttr("style").removeAttr("tabindex").removeAttr("role").removeAttr("aria-labelledby").removeAttr("style"),e.empty(),e.insertBefore(b.gBox).show(),a(b.pager).insertBefore(b.gBox).show(),a(b.gBox).remove())})},setGridState:function(e){return this.each(function(){var b=this.p,d=this.grid,c=d.cDiv,g=a(d.uDiv),
h=a(d.ubDiv);if(d&&null!=b){var d=M.getIconRes.call(this,"gridMinimize.visible"),m=M.getIconRes.call(this,"gridMinimize.hidden");"hidden"===e?(a(".ui-jqgrid-bdiv, .ui-jqgrid-hdiv",b.gView).slideUp("fast"),b.pager&&a(b.pager).slideUp("fast"),b.toppager&&a(b.toppager).slideUp("fast"),!0===b.toolbar[0]&&("both"===b.toolbar[1]&&h.slideUp("fast"),g.slideUp("fast")),b.footerrow&&a(".ui-jqgrid-sdiv",b.gBox).slideUp("fast"),a(".ui-jqgrid-titlebar-close span",c).removeClass(d).addClass(m),b.gridstate="hidden"):
"visible"===e&&(a(".ui-jqgrid-hdiv, .ui-jqgrid-bdiv",b.gView).slideDown("fast"),b.pager&&a(b.pager).slideDown("fast"),b.toppager&&a(b.toppager).slideDown("fast"),!0===b.toolbar[0]&&("both"===b.toolbar[1]&&h.slideDown("fast"),g.slideDown("fast")),b.footerrow&&a(".ui-jqgrid-sdiv",b.gBox).slideDown("fast"),a(".ui-jqgrid-titlebar-close span",c).removeClass(m).addClass(d),b.gridstate="visible")}})},filterToolbar:function(e){return this.each(function(){var b=this,d=b.grid,c=a(b),g=b.p,h=B.bindEv,m=B.info_dialog,
n=B.htmlEncode;if(!this.ftoolbar){var f=a.extend(!0,{autosearch:!0,autosearchDelay:500,searchOnEnter:!0,beforeSearch:null,afterSearch:null,beforeClear:null,afterClear:null,searchurl:"",stringResult:!1,groupOp:"AND",defaultSearch:"bw",idMode:"new",searchOperators:!1,resetIcon:"x",applyLabelClasses:!0,loadFilterDefaults:!0,operands:{eq:"==",ne:"!",lt:"<",le:"<=",gt:">",ge:">=",bw:"^",bn:"!^","in":"=",ni:"!=",ew:"|",en:"!@",cn:"~",nc:"!~",nu:"#",nn:"!#"}},B.search,g.searching||{},e||{}),p=g.colModel,
w=function(a){return V.call(c,a)},N=w("errors.errcap"),K=w("edit.bClose"),F=w("edit.msg"),x=E.call(b,"states.hover"),C=E.call(b,"states.select"),J=E.call(b,"filterToolbar.dataField"),H,r=function(a){var b="gs_";switch(f.idMode){case "compatibility":b+=g.idPrefix;break;case "new":b+=g.id+"_"}return b+a},y=function(){var b;b=g.postData.filters;var c={},d,e,u=g.iColByName,k,h;if(b){if("string"===typeof b)try{b=a.parseJSON(b)}catch(l){b={}}d=(b||{}).rules;if(!(null==b||b.groupOp.toUpperCase()!==f.groupOp.toUpperCase()||
null==d||0===d.length||null!=b.groups&&0<b.groups.length)){for(b=0;b<d.length;b++){e=d[b];k=p[u[e.field]];if(null==k||!1===k.search)return;h=k.searchoptions||{};if(h.sopt){if(0>a.inArray(e.op,h.sopt))return}else if("select"===k.stype){if("eq"!==e.op)return}else if(e.op!==f.defaultSearch)return;c[k.name]={op:e.op,data:e.data}}return c}}},I=function(){var e={},G=0,u={};a.each(p,function(){var c=this,l=c.index||c.name,q,h;q=c.searchoptions||{};var k=a("#"+r(c.name),!0===c.frozen&&!0===g.frozenColumns?
d.fhDiv:d.hDiv),m=function(a,b){var d=c.formatoptions||{};return void 0!==d[a]?d[a]:w("formatter."+(b||c.formatter)+"."+a)},T=function(a){var b=m("thousandsSeparator").replace(/([\.\*\_\'\(\)\{\}\+\?\\])/g,"\\$1");return a.replace(new RegExp(b,"g"),"")};h=f.searchOperators?k.parent().prev().children("a").data("soper")||f.defaultSearch:q.sopt?q.sopt[0]:"select"===c.stype?"eq":f.defaultSearch;if("custom"===c.stype&&a.isFunction(q.custom_value)&&0<k.length&&"SPAN"===k[0].nodeName.toUpperCase())q=q.custom_value.call(b,
k.children(".customelement").first(),"get");else if("select"===c.stype)q=k.val();else switch(q=a.trim(k.val()),c.formatter){case "integer":q=T(q).replace(m("decimalSeparator","number"),".");""!==q&&(q=String(parseInt(q,10)));break;case "number":q=T(q).replace(m("decimalSeparator"),".");""!==q&&"0"===String(q).charAt(0)&&(q=String(parseFloat(q)));break;case "currency":var k=m("prefix"),n=m("suffix");k&&k.length&&(q=q.substr(k.length));n&&n.length&&(q=q.substr(0,q.length-n.length));q=T(q).replace(m("decimalSeparator"),
".");""!==q&&(q=String(parseFloat(q)))}if(q||"nu"===h||"nn"===h)e[l]=q,u[l]=h,G++;else try{delete g.postData[l]}catch(W){}});var h=0<G?!0:!1;if(f.stringResult||f.searchOperators||"local"===g.datatype){var l='{"groupOp":"'+f.groupOp+'","rules":[',k=0;a.each(e,function(a,b){0<k&&(l+=",");l+='{"field":"'+a+'",';l+='"op":"'+u[a]+'",';l+='"data":"'+(b+"").replace(/\\/g,"\\\\").replace(/\"/g,'\\"')+'"}';k++});l+="]}";a.extend(g.postData,{filters:l});a.each(["searchField","searchString","searchOper"],function(a,
b){g.postData.hasOwnProperty(b)&&delete g.postData[b]})}else a.extend(g.postData,e);var m;g.searchurl&&(m=g.url,c.jqGrid("setGridParam",{url:g.searchurl}));var n="stop"===c.triggerHandler("jqGridToolbarBeforeSearch")?!0:!1;!n&&a.isFunction(f.beforeSearch)&&(n=f.beforeSearch.call(b));n||c.jqGrid("setGridParam",{search:h}).trigger("reloadGrid",[a.extend({page:1},f.reloadGridSearchOptions||{})]);m&&c.jqGrid("setGridParam",{url:m});c.triggerHandler("jqGridToolbarAfterSearch");a.isFunction(f.afterSearch)&&
f.afterSearch.call(b)},L=w("search.odata")||[],u=g.customSortOperations,l=function(d,G,e){a("#sopt_menu").remove();G=parseInt(G,10);e=parseInt(e,10)+18;var l,h=0,k=[],m=a(d).data("soper"),h=a(d).data("colname"),A=a(".ui-jqgrid-view").css("font-size")||"11px";G="<ul id='sopt_menu' class='"+E.call(b,"searchToolbar.menu","ui-search-menu")+"' role='menu' tabindex='0' style='z-index:9999;display:block;font-size:"+A+";left:"+G+"px;top:"+e+"px;'>";h=g.iColByName[h];if(void 0!==h){h=p[h];e=a.extend({},h.searchoptions);
var t,v;e.sopt||(e.sopt=[],e.sopt[0]="select"===h.stype?"eq":f.defaultSearch);a.each(L,function(){k.push(this.oper)});null!=u&&a.each(u,function(a){k.push(a)});for(h=0;h<e.sopt.length;h++)A=e.sopt[h],l=a.inArray(A,k),-1!==l&&(l=L[l],void 0!==l?(v=f.operands[A],t=l.text):null!=u&&(t=u[A],v=t.operand,t=t.text),l=m===A?C:"",G+='<li class="ui-menu-item '+l+'" role="presentation"><a class="ui-corner-all g-menu-item" tabindex="0" role="menuitem" value="'+n(A)+'" data-oper="'+n(v)+'"><table><tr><td style="width:25px">'+
n(v)+"</td><td>"+n(t)+"</td></tr></table></a></li>");G+="</ul>";a("body").append(G);a("#sopt_menu").addClass("ui-menu ui-widget ui-widget-content ui-corner-all");a("#sopt_menu > li > a").hover(function(){a(this).addClass(x)},function(){a(this).removeClass(x)}).click(function(){var b=a(this).attr("value"),e=a(this).data("oper");c.triggerHandler("jqGridToolbarSelectOper",[b,e,d]);a("#sopt_menu").hide();a(d).text(e).data("soper",b);!0===f.autosearch&&(e=a(d).parent().next().children()[0],(a(e).val()||
"nu"===b||"nn"===b)&&I())})}},A,R=a("<tr></tr>",{"class":"ui-search-toolbar",role:"row"});f.loadFilterDefaults&&(H=y()||{});a.each(p,function(c){var d,e;e="";var l,n,k=this.searchoptions||{},p=this.editoptions||{},y=a("<th></th>",{"class":E.call(b,"colHeaders","ui-th-column ui-th-"+g.direction+" "+(f.applyLabelClasses?this.labelClasses||"":""))}),t=a("<div></div>"),v=a("<table class='ui-search-table'><tr><td class='ui-search-oper'></td><td class='ui-search-input'></td><td class='ui-search-clear' style='width:1px'></td></tr></table>");
!0===this.hidden&&a(y).css("display","none");this.search=!1===this.search?!1:!0;void 0===this.stype&&(this.stype="text");d=a.extend({mode:"filter"},k);if(this.search){if(f.searchOperators){e=g.search&&null!=H[this.name]?H[this.name].op:d.sopt?d.sopt[0]:"select"===this.stype?"eq":f.defaultSearch;for(n=0;n<L.length;n++)if(L[n].oper===e){l=f.operands[e]||"";break}if(void 0===l&&null!=u)for(var q in u)if(u.hasOwnProperty(q)&&q===e){l=u[q].operand;break}void 0===l&&(l="=");e="<a title='"+(null!=d.searchtitle?
d.searchtitle:w("search.operandTitle"))+"' data-soper='"+e+"' class='"+E.call(b,"searchToolbar.operButton","soptclass")+"' data-colname='"+this.name+"'>"+l+"</a>"}a("td",v).first().data("colindex",c).append(e);null!=d.sopt&&1!==d.sopt.length||a("td.ui-search-oper",v).hide();g.search&&null!=H[this.name]&&(d.defaultValue=H[this.name].data);void 0===d.clearSearch&&(d.clearSearch="text"===this.stype?!0:!1);d.clearSearch?(e=w("search.resetTitle")||"Clear Search Value",a("td",v).eq(2).append("<a title='"+
e+"' class='"+E.call(b,"searchToolbar.clearButton","clearsearchclass")+"'><span>"+f.resetIcon+"</span></a>")):a("td",v).eq(2).hide();switch(this.stype){case "select":if(e=this.surl||d.dataUrl)a(t).append(v),a.ajax(a.extend({url:e,context:{stbl:v,options:d,cm:this,iCol:c},dataType:"html",success:function(a,c,e){c=this.cm;var g=this.iCol,l=this.options,u=this.stbl.find(">tbody>tr>td.ui-search-input");void 0!==l.buildSelect?(a=l.buildSelect.call(b,a,e,c,g))&&u.append(a):u.append(a);a=u.children("select");
0===a.find("option[value='']").length&&"string"===typeof d.noFilterText&&(z=document.createElement("option"),z.value="",z.innerHTML=d.noFilterText,a.prepend(z));void 0!==l.defaultValue&&a.val(l.defaultValue);a.attr({name:c.index||c.name,id:r(c.name)});l.attr&&a.attr(l.attr);a.addClass(J);a.css({width:"100%"});h.call(b,a[0],l);B.fullBoolFeedback.call(b,l.selectFilled,"jqGridSelectFilled",{elem:a[0],options:l,cm:c,cmName:c.name,iCol:g,mode:"filter"});!0===f.autosearch&&a.change(function(){I();return!1})}},
B.ajaxOptions,g.ajaxSelectOptions||{}));else{var D,U,O;this.searchoptions?(D=void 0===k.value?p.value||"":k.value,U=void 0===k.separator?p.separator||":":k.separator,O=void 0===k.delimiter?p.delimiter||";":k.delimiter):this.editoptions&&(D=void 0===p.value?"":p.value,U=void 0===p.separator?":":p.separator,O=void 0===p.delimiter?";":p.delimiter);if(D){k=document.createElement("select");k.style.width="100%";a(k).attr({name:this.index||this.name,id:r(this.name)});var z,C,M;if("string"===typeof D)for(e=
D.split(O),O=0;O<e.length;O++)D=e[O].split(U),z=document.createElement("option"),z.value=D[0],""===D[0]&&(M=!0),z.innerHTML=D[1],k.appendChild(z);else if("object"===typeof D)for(C in D)D.hasOwnProperty(C)&&(z=document.createElement("option"),z.value=C,""===C&&(M=!0),z.innerHTML=D[C],k.appendChild(z));M||"string"!==typeof d.noFilterText||(z=document.createElement("option"),z.value="",z.innerHTML=d.noFilterText,a(k).prepend(z));void 0!==d.defaultValue&&a(k).val(d.defaultValue);d.attr&&a(k).attr(d.attr);
a(k).addClass(J);a(t).append(v);h.call(b,k,d);a("td",v).eq(1).append(k);B.fullBoolFeedback.call(b,d.selectFilled,"jqGridSelectFilled",{elem:k,options:this.searchoptions||p,cm:this,cmName:this.name,iCol:c,mode:"filter"});!0===f.autosearch&&a(k).change(function(){I();return!1})}}break;case "text":c=void 0!==d.defaultValue?d.defaultValue:"";a("td",v).eq(1).append("<input type='text' class='"+J+"' name='"+(this.index||this.name)+"' id='"+r(this.name)+"' value='"+c+"'/>");a(t).append(v);d.attr&&a("input",
t).attr(d.attr);h.call(b,a("input",t)[0],d);!0===f.autosearch&&(f.searchOnEnter?a("input",t).keypress(function(a){return 13===(a.charCode||a.keyCode||0)?(I(),!1):this}):a("input",t).keydown(function(a){switch(a.which){case 13:return!1;case 9:case 16:case 37:case 38:case 39:case 40:case 27:break;default:A&&clearTimeout(A),A=setTimeout(function(){I()},f.autosearchDelay)}}));break;case "custom":a("td",v).eq(1).append("<span style='width:100%;padding:0;box-sizing:border-box;' class='"+J+"' name='"+(this.index||
this.name)+"' id='"+r(this.name)+"'/>");a(t).append(v);try{if(a.isFunction(d.custom_element)){var Q=d.custom_element.call(b,void 0!==d.defaultValue?d.defaultValue:"",d);if(Q)Q=a(Q).addClass("customelement"),a(t).find("span[name='"+(this.index||this.name)+"']").append(Q);else throw"e2";}else throw"e1";}catch(P){"e1"===P&&m.call(b,N,"function 'custom_element' "+F.nodefined,K),"e2"===P?m.call(b,N,"function 'custom_element' "+F.novalue,K):m.call(b,N,"string"===typeof P?P:P.message,K)}}}a(y).append(t);
a(y).find(".ui-search-oper .soptclass,.ui-search-clear .clearsearchclass").hover(function(){a(this).addClass(x)},function(){a(this).removeClass(x)});a(R).append(y);f.searchOperators||a("td",v).eq(0).hide()});a(d.hDiv).find(">div>.ui-jqgrid-htable>thead").append(R);f.searchOperators&&(a(".soptclass",R).click(function(b){var c=a(this).offset();l(this,c.left,c.top);b.stopPropagation()}),a("body").on("click",function(b){"soptclass"!==b.target.className&&a("#sopt_menu").hide()}));a(".clearsearchclass",
R).click(function(){var b=a(this).parents("tr").first(),c=parseInt(a("td.ui-search-oper",b).data("colindex"),10),d=a.extend({},p[c].searchoptions||{}).defaultValue||"";"select"===p[c].stype?d?a("td.ui-search-input select",b).val(d):a("td.ui-search-input select",b)[0].selectedIndex=0:a("td.ui-search-input input",b).val(d);!0===f.autosearch&&I()});b.ftoolbar=!0;b.triggerToolbar=I;b.clearToolbar=function(e){var l={},h=0,u;e="boolean"!==typeof e?!0:e;a.each(p,function(){var c,e=a("#"+r(this.name),!0===
this.frozen&&!0===g.frozenColumns?d.fhDiv:d.hDiv),f,k=this.searchoptions||{};void 0!==k.defaultValue&&(c=k.defaultValue);u=this.index||this.name;switch(this.stype){case "select":f=0<e.length?!e[0].multiple:!0;e.find("option").each(function(b){this.selected=0===b&&f;if(a(this).val()===c)return this.selected=!0,!1});if(void 0!==c)l[u]=c,h++;else try{delete g.postData[u]}catch(m){}break;case "text":e.val(c||"");if(void 0!==c)l[u]=c,h++;else try{delete g.postData[u]}catch(m){}break;case "custom":a.isFunction(k.custom_value)&&
0<e.length&&"SPAN"===e[0].nodeName.toUpperCase()&&k.custom_value.call(b,e.children(".customelement").first(),"set",c||"")}});var m=0<h?!0:!1;g.resetsearch=!0;if(f.stringResult||f.searchOperators||"local"===g.datatype){var k='{"groupOp":"'+f.groupOp+'","rules":[',n=0;a.each(l,function(a,b){0<n&&(k+=",");k+='{"field":"'+a+'",';k+='"op":"eq",';k+='"data":"'+(b+"").replace(/\\/g,"\\\\").replace(/\"/g,'\\"')+'"}';n++});k+="]}";a.extend(g.postData,{filters:k});a.each(["searchField","searchString","searchOper"],
function(a,b){g.postData.hasOwnProperty(b)&&delete g.postData[b]})}else a.extend(g.postData,l);var A;g.searchurl&&(A=g.url,c.jqGrid("setGridParam",{url:g.searchurl}));var t="stop"===c.triggerHandler("jqGridToolbarBeforeClear")?!0:!1;!t&&a.isFunction(f.beforeClear)&&(t=f.beforeClear.call(b));t||e&&c.jqGrid("setGridParam",{search:m}).trigger("reloadGrid",[a.extend({page:1},f.reloadGridResetOptions||{})]);A&&c.jqGrid("setGridParam",{url:A});c.triggerHandler("jqGridToolbarAfterClear");a.isFunction(f.afterClear)&&
f.afterClear()};b.toggleToolbar=function(){var b=a("tr.ui-search-toolbar",d.hDiv),e=!0===g.frozenColumns?a("tr.ui-search-toolbar",d.fhDiv):!1;"none"===b.css("display")?(b.show(),e&&e.show()):(b.hide(),e&&e.hide());!0===g.frozenColumns&&(c.jqGrid("destroyFrozenColumns"),c.jqGrid("setFrozenColumns"))};!0===g.frozenColumns&&(c.jqGrid("destroyFrozenColumns"),c.jqGrid("setFrozenColumns"));c.bind("jqGridRefreshFilterValues.filterToolbar"+(f.loadFilterDefaults?" jqGridAfterLoadComplete.filterToolbar":""),
function(){var b,c,d=y(),e=this.p,l;if(e&&e.search&&d){for(b in d)d.hasOwnProperty(b)&&(c=d[b],l=a("#"+r(b)),l.val(c.data),l=l.closest(".ui-search-input").siblings(".ui-search-oper").children(".soptclass"),l.data("soper",c.op),l.text(f.operands[c.op]));for(c=0;c<e.colModel.length;c++)b=e.colModel[c].name,d.hasOwnProperty(b)||a("#"+r(b)).val("")}})}})},destroyFilterToolbar:function(){return this.each(function(){this.ftoolbar&&(this.toggleToolbar=this.clearToolbar=this.triggerToolbar=null,this.ftoolbar=
!1,a(this.grid.hDiv).find("table thead tr.ui-search-toolbar").remove(),!0===this.p.frozenColumns&&a(this).jqGrid("destroyFrozenColumns").jqGrid("setFrozenColumns"))})},destroyGroupHeader:function(e){void 0===e&&(e=!0);return this.each(function(){var b,d,c,g;b=this.grid;var h=this.p.colModel,m=a("table.ui-jqgrid-htable thead",b.hDiv);if(b){a(this).unbind(".setGroupHeaders");var n=a("<tr>",{role:"row"}).addClass("ui-jqgrid-labels"),f=b.headers;b=0;for(d=f.length;b<d;b++){c=h[b].hidden?"none":"";c=a(f[b].el).width(f[b].width).css("display",
c);try{c.removeAttr("rowSpan")}catch(p){c.attr("rowSpan",1)}n.append(c);g=c.children("span.ui-jqgrid-resize");0<g.length&&(g[0].style.height="");c.children("div")[0].style.top=""}a(m).children("tr.ui-jqgrid-labels").remove();a(m).prepend(n);!0===e&&a(this).jqGrid("setGridParam",{groupHeader:null})}})},setGroupHeaders:function(e){e=a.extend({useColSpanStyle:!1,applyLabelClasses:!0,groupHeaders:[]},e||{});return this.each(function(){this.p.groupHeader=e;var b,d,c=0,g,h,m,n,f,p,w=this.p,N=w.colModel,
K=N.length,F=this.grid.headers,x=a("table.ui-jqgrid-htable",this.grid.hDiv),C=B.isCellClassHidden,J=x.children("thead").children("tr.ui-jqgrid-labels"),H=J.last().addClass("jqg-second-row-header");g=x.children("thead");var r=x.find(".jqg-first-row-header");void 0===r[0]?r=a("<tr>",{role:"row","aria-hidden":"true"}).addClass("jqg-first-row-header").css("height","auto"):r.empty();var y=function(a,b){var c=b.length,d;for(d=0;d<c;d++)if(b[d].startColumnName===a)return d;return-1};a(this).prepend(g);g=
a("<tr>",{role:"row"}).addClass("ui-jqgrid-labels jqg-third-row-header");for(b=0;b<K;b++)if(m=F[b].el,n=a(m),d=N[b],h={height:"0",width:F[b].width+"px",display:d.hidden?"none":""},a("<th>",{role:"gridcell"}).css(h).addClass("ui-first-th-"+w.direction+(e.applyLabelClasses?" "+(d.labelClasses||""):"")).appendTo(r),m.style.width="",h=E.call(this,"colHeaders","ui-th-column-header ui-th-"+w.direction+" "+(e.applyLabelClasses?d.labelClasses||"":"")),f=y(d.name,e.groupHeaders),0<=f){f=e.groupHeaders[f];
c=f.numberOfColumns;p=f.titleText;for(f=d=0;f<c&&b+f<K;f++)N[b+f].hidden||C(N[b+f].classes)||a(F[b+f].el).is(":hidden")||d++;h=a("<th>").addClass(h).css({height:"22px","border-top":"0 none"}).html(p);0<d&&h.attr("colspan",String(d));w.headertitles&&h.attr("title",h.text());0===d&&h.hide();n.before(h);g.append(m);--c}else 0===c?e.useColSpanStyle?n.attr("rowspan",J.length+1):(a("<th>").addClass(h).css({display:d.hidden?"none":"","border-top":"0 none"}).insertBefore(n),g.append(m)):(g.append(m),c--);
w=a(this).children("thead");w.prepend(r);g.insertAfter(H);x.prepend(w);e.useColSpanStyle&&(x.find("span.ui-jqgrid-resize").each(function(){var b=a(this).parent();b.is(":visible")&&(this.style.cssText="height:"+b.height()+"px !important;cursor:col-resize;")}),x.find(".ui-th-column>div").each(function(){var b=a(this),c=b.parent();c.is(":visible")&&c.is(":has(span.ui-jqgrid-resize)")&&!b.hasClass("ui-jqgrid-rotate")&&!b.hasClass("ui-jqgrid-rotateOldIE")&&b.css("top",(c.height()-b.outerHeight(!0))/2+
"px")}));a(this).triggerHandler("jqGridAfterSetGroupHeaders")})},getNumberOfFrozenColumns:function(){var a=this;if(0===a.length)return 0;var a=a[0],a=a.p.colModel,b=a.length,d=-1,c;for(c=0;c<b&&!0===a[c].frozen;c++)d=c;return d+1},setFrozenColumns:function(){return this.each(function(){var e=this,b=a(e),d=e.p,c=e.grid;if(c&&null!=d&&!0!==d.frozenColumns){var g=d.colModel,h,m=g.length,n=-1,f=!1,p=[],w=S(d.id),B=E.call(e,"states.hover"),K=E.call(e,"states.disabled");if(!0!==d.subGrid&&!0!==d.treeGrid&&
!d.scroll){for(h=0;h<m&&!0===g[h].frozen;h++)f=!0,n=h,p.push("#jqgh_"+w+"_"+S(g[h].name));d.sortable&&(g=a(c.hDiv).find(".ui-jqgrid-htable .ui-jqgrid-labels"),g.sortable("destroy"),b.jqGrid("setGridParam",{sortable:{options:{items:0<p.length?">th:not(:has("+p.join(",")+"),:hidden)":">th:not(:hidden)"}}}),b.jqGrid("sortableColumns",g));if(0<=n&&f){f=d.caption?a(c.cDiv).outerHeight():0;p=a(".ui-jqgrid-htable",d.gView).height();d.toppager&&(f+=a(c.topDiv).outerHeight());!0===d.toolbar[0]&&"bottom"!==
d.toolbar[1]&&(f+=a(c.uDiv).outerHeight());c.fhDiv=a("<div style='position:absolute;overflow:hidden;"+("rtl"===d.direction?"right:0;border-top-left-radius:0;":"left:0;border-top-right-radius:0;")+"top:"+f+"px;height:"+p+"px;' class='"+E.call(e,"hDiv","frozen-div ui-jqgrid-hdiv")+"'></div>");c.fbDiv=a("<div style='position:absolute;overflow:hidden;"+("rtl"===d.direction?"right:0;":"left:0;")+"top:"+(parseInt(f,10)+parseInt(p,10)+1)+"px;overflow:hidden;' class='frozen-bdiv ui-jqgrid-bdiv'></div>");
a(d.gView).append(c.fhDiv);g=a(".ui-jqgrid-htable",d.gView).clone(!0);m=g[0].tHead.rows;if(d.groupHeader){a(m[0].cells).filter(":gt("+n+")").remove();a(m).filter(".jqg-third-row-header").each(function(){a(this).children("th[id]").each(function(){var b=a(this).attr("id");b&&b.substr(0,e.id.length+1)===e.id+"_"&&(b=b.substr(e.id.length+1),d.iColByName[b]>n&&a(this).remove())})});var F=-1,x=-1,C,J;a(m).filter(".jqg-second-row-header").children("th").each(function(){C=parseInt(a(this).attr("colspan")||
1,10);J=parseInt(a(this).attr("rowspan")||1,10);1<J?(F++,x++):C&&(F+=C,x++);if(F===n)return!1});F!==n&&(x=n);a(m).filter(".jqg-second-row-header,.ui-search-toolbar").each(function(){a(this).children(":gt("+x+")").remove()})}else a(m).each(function(){a(this).children(":gt("+n+")").remove()});a(g).width(1);a(c.fhDiv).append(g).mousemove(function(a){if(c.resizing)return c.dragMove(a),!1}).scroll(function(){this.scrollLeft=0});d.footerrow&&(g=a(".ui-jqgrid-bdiv",d.gView).height(),c.fsDiv=a("<div style='position:absolute;"+
("rtl"===d.direction?"right:0;":"left:0;")+"top:"+(parseInt(f,10)+parseInt(p,10)+parseInt(g,10)+1)+"px;' class='frozen-sdiv ui-jqgrid-sdiv'></div>"),a(d.gView).append(c.fsDiv),f=a(".ui-jqgrid-ftable",d.gView).clone(!0),a("tr",f).each(function(){a("td:gt("+n+")",this).remove()}),a(f).width(1),a(c.fsDiv).append(f));b.bind("jqGridSortCol.setFrozenColumns",function(b,e,f){b=a("tr.ui-jqgrid-labels:last th:eq("+d.lastsort+")",c.fhDiv);e=a("tr.ui-jqgrid-labels:last th:eq("+f+")",c.fhDiv);a("span.ui-grid-ico-sort",
b).addClass(K);a(b).attr("aria-selected","false");a("span.ui-icon-"+d.sortorder,e).removeClass(K);a(e).attr("aria-selected","true");d.viewsortcols[0]||d.lastsort===f||(a("span.s-ico",b).hide(),a("span.s-ico",e).show())});a(d.gView).append(c.fbDiv);a(c.bDiv).scroll(function(){a(c.fbDiv).scrollTop(a(this).scrollTop())});!0===d.hoverrows&&a(d.idSel).unbind("mouseover").unbind("mouseout");var H=function(a,b){var c=a.height();1<=Math.abs(c-b)&&0<b&&(a.height(b),c=a.height(),1<=Math.abs(b-c)&&a.height(b+
Math.round(b-c)))},r=function(a,b){var c=a.width();1<=Math.abs(c-b)&&(a.width(b),c=a.width(),1<=Math.abs(b-c)&&a.width(b+Math.round(b-c)))},y=function(b,c,e,f){var g,m,n,p,w,k,r;r=a(c).position().top;var x,t,v;if(null!=b&&0<b.length){b[0].scrollTop=c.scrollTop;b.css("rtl"===d.direction?{top:r,right:0}:{top:r,left:0});m=b.children("table").children("thead").children("tr");n=a(c).children("div").children("table").children("thead").children("tr");0===n.length&&(m=a(b.children("table")[0].rows),n=a(a(c).children("div").children("table")[0].rows));
g=Math.min(m.length,n.length);x=0<g?a(m[0]).position().top:0;t=0<g?a(n[0]).position().top:0;if(0<=e)for(0<=f&&(g=Math.min(f+1,g));e<g;e++)if(p=a(n[e]),"none"!==p.css("display")&&p.is(":visible")){r=p.position().top;f=a(m[e]);w=f.position().top;k=p.height();if(null!=d.groupHeader&&d.groupHeader.useColSpanStyle)for(v=p[0].cells,h=0;h<v.length;h++)p=v[h],null!=p&&"TH"===p.nodeName.toUpperCase()&&(k=Math.max(k,a(p).height()));r=k+(r-t)+(x-w);H(f,r)}H(b,c.clientHeight)}},f={resizeDiv:!0,resizedRows:{iRowStart:0,
iRowEnd:-1}},I={header:f,resizeFooter:!0,body:f};b.bind("jqGridAfterGridComplete.setFrozenColumns",function(){a(d.idSel+"_frozen").remove();a(c.fbDiv).height(c.hDiv.clientHeight);var e=a(this).clone(!0),f=e[0].rows,g=b[0].rows;a(f).filter("tr[role=row]").each(function(){a(this.cells).filter("td[role=gridcell]:gt("+n+")").remove()});c.fbRows=f;e.width(1).attr("id",d.id+"_frozen");e.appendTo(c.fbDiv);if(!0===d.hoverrows){var h=function(b,c,d){a(b)[c](B);a(d[b.rowIndex])[c](B)};a(f).filter(".jqgrow").hover(function(){h(this,
"addClass",g)},function(){h(this,"removeClass",g)});a(g).filter(".jqgrow").hover(function(){h(this,"addClass",f)},function(){h(this,"removeClass",f)})}y(c.fhDiv,c.hDiv,0,-1);y(c.fbDiv,c.bDiv,0,-1);c.sDiv&&y(c.fsDiv,c.sDiv,0,-1)});var L=function(b){a(c.fbDiv).scrollTop(a(c.bDiv).scrollTop());b.header.resizeDiv&&y(c.fhDiv,c.hDiv,b.header.iRowStart,b.header.iRowEnd);b.body.resizeDiv&&y(c.fbDiv,c.bDiv,b.body.iRowStart,b.body.iRowEnd);b.resizeFooter&&c.sDiv&&b.resizeFooter&&y(c.fsDiv,c.sDiv,0,-1);var d=
c.fhDiv[0].clientWidth;b.header.resizeDiv&&null!=c.fhDiv&&1<=c.fhDiv.length&&H(a(c.fhDiv),c.hDiv.clientHeight);b.body.resizeDiv&&null!=c.fbDiv&&0<c.fbDiv.length&&r(a(c.fbDiv),d);b.resizeFooter&&null!=c.fsDiv&&0<=c.fsDiv.length&&r(a(c.fsDiv),d)};a(d.gBox).bind("resizestop.setFrozenColumns",function(){setTimeout(function(){L(I)},50)});b.bind("jqGridInlineEditRow.setFrozenColumns jqGridInlineAfterRestoreRow.setFrozenColumns jqGridInlineAfterSaveRow.setFrozenColumns jqGridAfterEditCell.setFrozenColumns jqGridAfterRestoreCell.setFrozenColumns jqGridAfterSaveCell.setFrozenColumns jqGridResizeStop.setFrozenColumns",
function(a,c){var d=b.jqGrid("getInd",c);L({header:{resizeDiv:!1,resizedRows:{iRowStart:-1,iRowEnd:-1}},resizeFooter:!0,body:{resizeDiv:!0,resizedRows:{iRowStart:d,iRowEnd:d}}})});b.bind("jqGridResizeStop.setFrozenColumns",function(){L(I)});b.bind("jqGridResetFrozenHeights.setFrozenColumns",function(a,b){L(b||I)});c.hDiv.loading||b.triggerHandler("jqGridAfterGridComplete");d.frozenColumns=!0}}}})},destroyFrozenColumns:function(){return this.each(function(){var e=a(this),b=this.grid,d=this.p,c=S(d.id);
if(b&&!0===d.frozenColumns){a(b.fhDiv).remove();a(b.fbDiv).remove();b.fhDiv=null;b.fbDiv=null;b.fbRows=null;d.footerrow&&(a(b.fsDiv).remove(),b.fsDiv=null);e.unbind(".setFrozenColumns");if(!0===d.hoverrows){var g,h=E.call(this,"states.hover");e.bind("mouseover",function(b){g=a(b.target).closest("tr.jqgrow");"ui-subgrid"!==a(g).attr("class")&&a(g).addClass(h)}).bind("mouseout",function(b){g=a(b.target).closest("tr.jqgrow");a(g).removeClass(h)})}d.frozenColumns=!1;d.sortable&&(b=a(b.hDiv).find(".ui-jqgrid-htable .ui-jqgrid-labels"),
b.sortable("destroy"),e.jqGrid("setGridParam",{sortable:{options:{items:">th:not(:has(#jqgh_"+c+"_cb,#jqgh_"+c+"_rn,#jqgh_"+c+"_subgrid),:hidden)"}}}),e.jqGrid("sortableColumns",b))}})}})});
//# sourceMappingURL=grid.custom.map
