$(document).ready(function(){var a=document.title,d=location.href;$("#share-wrapper li").hover(function(){var a=$(this);880<$(window).width()&&(a.hasClass("visible")?a.animate({"margin-left":"-117px"},"fast").removeClass("visible"):a.animate({"margin-left":"0px"},"fast").addClass("visible"))});$(".button-wrap").click(function(g){switch($(this).attr("class").split(" ")[0]){case "facebook":var m="https://www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(d)+"&amp;title="+encodeURIComponent(a);
break;case "twitter":m="http://twitter.com/home?status="+encodeURIComponent(a+" "+d);break;case "digg":m="http://www.digg.com/submit?phase=2&amp;url="+encodeURIComponent(d)+"&amp;title="+encodeURIComponent(a);break;case "stumbleupon":m="http://www.stumbleupon.com/submit?url="+encodeURIComponent(d)+"&amp;title="+encodeURIComponent(a);break;case "delicious":m="http://del.icio.us/post?url="+encodeURIComponent(d)+"&amp;title="+encodeURIComponent(a);break;case "google":m="https://plus.google.com/share?url="+
encodeURIComponent(d)+"&amp;title="+encodeURIComponent(a);break;case "email":m="mailto:?subject="+a+"&body=Found this great link for you : "+d}winWidth=650;winHeight=450;winLeft=($(window).width()-winWidth)/2;winTop=($(window).height()-winHeight)/2;winOptions="width="+winWidth+",height="+winHeight+",top="+winTop+",left="+winLeft;window.open(m,"Share This Link",winOptions);return!1})});
(function(a){"function"===typeof define&&define.amd?define(["jquery"],a):a(jQuery)})(function(a){function d(a){return a}function g(a){return decodeURIComponent(a.replace(q," "))}function m(a){0===a.indexOf('"')&&(a=a.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,"\\"));try{return e.json?JSON.parse(a):a}catch(b){}}var q=/\+/g,e=a.cookie=function(l,b,c){if(void 0!==b){c=a.extend({},e.defaults,c);if("number"===typeof c.expires){var r=c.expires,f=c.expires=new Date;f.setDate(f.getDate()+r)}b=e.json?
JSON.stringify(b):String(b);return document.cookie=[e.raw?l:encodeURIComponent(l),"=",e.raw?b:encodeURIComponent(b),c.expires?"; expires="+c.expires.toUTCString():"",c.path?"; path="+c.path:"",c.domain?"; domain="+c.domain:"",c.secure?"; secure":""].join("")}b=e.raw?d:g;c=document.cookie.split("; ");for(var r=l?void 0:{},f=0,p=c.length;f<p;f++){var h=c[f].split("="),n=b(h.shift()),h=b(h.join("="));if(l&&l===n){r=m(h);break}l||(r[n]=m(h))}return r};e.defaults={};a.removeCookie=function(d,b){return void 0!==
a.cookie(d)?(a.cookie(d,"",a.extend({},b,{expires:-1})),!0):!1}});
(function(a){a.fn.faceBadge=function(d){a.fn.faceBadge.defaults={pageId:null,loaderText:"Loading badge...",width:720,height:266,coverHeight:266,textColor:"#ffffff",showDesc:!1,linkToPage:!0};var g=a.extend({},a.fn.faceBadge.defaults,d);return this.each(function(){var d=a(this);d.hide().empty().addClass("faceBadge");var q=a('<p class="preLoader">'+g.loaderText+"</p>");d.append(q);window.jsonPageGraph="http://graph.facebook.com/"+g.pageId;jQuery.getJSON(jsonPageGraph,{format:"json"}).done(function(e){d.hide();
var l=e.likes.toString(),b=e.about.toString().substr(0,100)+" ...",c=e.name.toString(),r=e.cover.source.replace("s720x720","s720x720"),b="";if(g.linkToPage)var f='<a target="_blank" href="'+e.link+'">',p="</a>";else p=f="";void 0!==e.description?b=e.description.toString().substr(0,70)+" ...":void 0!==e.about&&(b=e.about.toString().substr(0,70)+" ...");if(3<l.length){e=l.length%3;var h=".",n=0<e?l.substring(0,e):"";for(i=0;i<Math.floor(l.length/3);i++)0===e&&0===i?n+=l.substring(e+3*i,e+3*i+3):(1<
n&&(h=","),n+=h+l.substring(e+3*i,e+3*i+3));l=n}d.html('<div class="faceBadge-cover"></div>');e=a(".faceBadge-cover");e.css("height",g.coverHeight);g.showDesc&&e.append('<div class="faceBadge-desc">'+b+"</div>");e.append('<img width="'+g.width+'" style="" src="'+r+'" /><div style="height: '+g.coverHeight+'px ; width:100%" class="cover-shadow"></div>');d.append('<div id="faceBadge" class="faceBadge-page-data"></div>');r=a(".faceBadge-page-data");r.append('<div class="FaceBadge-image">'+f+'<img src="https://graph.facebook.com/'+
g.pageId+'/picture?width=100&height=100" width="100" height="100"/>'+p+"</div>");r.append('<div class="faceBadge-content"><div class="faceBadge-name">'+c+"</div></div>");r.append('<div class="faceBadge-like-count"></div>');a(".faceBadge-like-count").append('<iframe src="//www.facebook.com/plugins/like.php?href='+encodeURIComponent("http://www.facebook.com/"+g.pageId)+'&amp;width=250px&amp;layout=standard&amp;colorscheme=dark&amp;action=like&amp;show_faces=true&amp;share=false&amp;height=80&amp;appId=118671008210303" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:250px; height:80px; float:left" allowTransparency="true" id="face"></iframe>');
a(".faceBadge-like-count").append('<span style="color:'+g.textColor+'; text-shadow:none">'+l+"</span>");d.fadeIn()})})}})(jQuery);
(function(a){a.cookieBar=function(d,g){var m="cookies"==d?"cookies":"set"==d?"set":!1;d=a.extend({message:"We use cookies to track usage and preferences.",acceptButton:!0,acceptText:"I Understand",declineButton:!1,declineText:"Disable Cookies",policyButton:!0,policyText:"Privacy Policy",policyURL:"info_terms.php",autoEnable:!0,expireDays:365,forceShow:!1,effect:"slide",element:"body",append:!1,fixed:!0,zindex:"",redirect:String(window.location.href),domain:String(window.location.hostname)},d);var q=
new Date;q.setTime(q.getTime()+864E5*d.expireDays);var q=q.toGMTString(),e="cb-enabled={value}; expires="+q+"; path=/",l,b="",c,r=document.cookie.split("; ");for(l=0;l<r.length;l++)c=r[l].split("="),"cb-enabled"==c[0]&&(b=c[1]);""==b&&d.autoEnable&&(b="enabled",document.cookie=e.replace("{value}","enabled"));if("cookies"==m)return"enabled"==b||"accepted"==b?!0:!1;if("set"!=m||"accepted"!=g&&"declined"!=g){var m=d.message.replace("{policy_url}",d.policyURL),q=d.acceptButton?'<a href="" class="cb-enable">'+
d.acceptText+"</a>":"",f=d.declineButton?'<a href="" class="cb-disable">'+d.declineText+"</a>":"",p=d.policyButton?'<a href="'+d.policyURL+'" class="cb-policy">'+d.policyText+"</a>":"",h=d.fixed?' class="fixed"':"",n=""!=d.zindex?' style="z-index:'+d.zindex+';"':"";if(d.forceShow||"enabled"==b||""==b)d.append?a(d.element).append('<div id="cookie-bar"'+h+n+"><p>"+m+q+f+p+"</p></div>"):a(d.element).prepend('<div id="cookie-bar"'+h+n+"><p>"+m+q+f+p+"</p></div>");a("#cookie-bar .cb-enable").click(function(){document.cookie=
e.replace("{value}","accepted");if("enabled"!=b&&"accepted"!=b)window.location=d.currentLocation;else return"slide"==d.effect?a("#cookie-bar").slideUp(300,function(){a("#cookie-bar").remove()}):"fade"==d.effect?a("#cookie-bar").fadeOut(300,function(){a("#cookie-bar").remove()}):a("#cookie-bar").hide(0,function(){a("#cookie-bar").remove()}),!1});a("#cookie-bar .cb-disable").click(function(){var f=new Date;f.setTime(f.getTime()-864E6);f=f.toGMTString();r=document.cookie.split("; ");for(l=0;l<r.length;l++)c=
r[l].split("="),0<=c[0].indexOf("_")?document.cookie=c[0]+"=0; expires="+f+"; domain="+d.domain.replace("www","")+"; path=/":document.cookie=c[0]+"=0; expires="+f+"; path=/";document.cookie=e.replace("{value}","declined");if("enabled"==b&&"accepted"!=b)window.location=d.currentLocation;else return"slide"==d.effect?a("#cookie-bar").slideUp(300,function(){a("#cookie-bar").remove()}):"fade"==d.effect?a("#cookie-bar").fadeOut(300,function(){a("#cookie-bar").remove()}):a("#cookie-bar").hide(0,function(){a("#cookie-bar").remove()}),
!1})}else return document.cookie=e.replace("{value}",g),"accepted"==g?!0:!1}})(jQuery);window.twttr=function(a,d,g){var m,q=a.getElementsByTagName(d)[0];if(!a.getElementById(g))return a=a.createElement(d),a.id=g,a.src="https://platform.twitter.com/widgets.js",q.parentNode.insertBefore(a,q),window.twttr||(m={_e:[],ready:function(a){m._e.push(a)}})}(document,"script","twitter-wjs");
(function(a){function d(b,c,a,f){if("function"==typeof f.before){var d=jQuery.Event("FILo Before Event");f.before(d)}d=b.filo.root_path;d=void 0==f.filo_loaderGraphic?d+b.filo.filo_loaderGraphicDefault:f.filo_loaderGraphic;if(null==b(".filo_loader")||0==b(".filo_loader").length){var h=new Image;h.onload=function(){b(h).css("marginTop",this.height/2*-1);b(h).css("marginLeft",this.width/2*-1);b("#"+String(c)).append(h)};h.setAttribute("class","filo_loader");h.src=d}var n=[];b.each(b("#"+String(c)).find(".excluded"),
function(c,a){n.push(b(a).attr("id"))});var k=[];b.each(b("#"+c).find(".album"),function(c,a){k.push(b(a).attr("id"))});if(void 0!=f.albums&&0<f.albums.length)for(d=0;d<f.albums.length;d++)k.push(decodeURI(f.albums[d]));if(void 0!=f.excluded&&0<f.excluded.length)for(d=0;d<f.excluded.length;d++)n.push(decodeURI(f.excluded[d]));var d="https://graph.facebook.com/fql?q=",e="",e=0<parseInt(a)?JSON.stringify({albums:"SELECT aid, name FROM album WHERE owner = "+a}):JSON.stringify({page_id:"SELECT page_id FROM page WHERE username = '"+
a+"'",albums:"SELECT aid, name FROM album WHERE owner IN (SELECT page_id FROM #page_id)"}),d=d+encodeURIComponent(e);b.browser.msie?b.ajax({url:d,dataType:"jsonp"}).success(function(d){d=d.data;g(b,c,a,1<d.length?d[1].fql_result_set:d[0].fql_result_set,k,n,f)}):b.getJSON(d,function(d){d=d.data;d=1<d.length?d[1].fql_result_set:d[0].fql_result_set;0>=d.length&&b(".filo_loader").remove();g(b,c,a,d,k,n,f)}).error(function(){b(".filo_loader").remove()})}function g(b,c,a,d,e,h,n){b.filo.toLoad[c]=0;b.filo.isLoaded[c]=
0;for(album in d)d[album].name=d[album].name.replace(/[\/]/g,":");var k="";0<e.length?b.each(d,function(d,f){if(l(f.name,e)){b.filo.toLoad[c]+=1;var h=b.filo.maxCountDefault;void 0!=b("#"+c+" #"+f.name).attr("maxCount")?h=parseInt(b("#"+c+" #"+f.name).attr("maxCount")):void 0!=b("#"+c+" #"+f.name.toLowerCase()).attr("maxCount")?h=parseInt(b("#"+c+" #"+f.name.toLowerCase()).attr("maxCount")):void 0!=n&&void 0!=n.maxCount&&(h=n.maxCount);k="all"==h?JSON.stringify({photos:"SELECT src, src_big FROM photo WHERE aid = '"+
f.aid+"'"}):JSON.stringify({photos:"SELECT src, src_big FROM photo WHERE aid = '"+f.aid+"' LIMIT "+h});var g="https://graph.facebook.com/fql?q="+encodeURIComponent(k);b("#"+c+" #"+f.name).remove();b("#"+c+" #"+f.name.toLowerCase()).remove();var t=b('<div class="album" id="'+f.name+'"></div>').append('<div class="title">'+f.name.replace(/[:]/g,"/")+'</div><div class="thumbs"></div>');b(t).hide();b("#"+c).append(t);b.browser.msie?b.ajax({url:g,dataType:"jsonp"}).success(function(d){m(1,b,a,c,d.data[0].fql_result_set,
t,h,n)}):b.getJSON(g,function(d){m(1,b,a,c,d.data[0].fql_result_set,t,h,n)})}}):b.each(d,function(d,f){if(!l(f.name,h)){b.filo.toLoad[c]+=1;var e=b.filo.maxCountDefault;void 0!=n&&void 0!=n.maxCount?e=n.maxCount:void 0!=b("#"+f.name).attr("maxCount")&&(e=parseInt(b("#"+f.name).attr("maxCount")));k="all"==e?JSON.stringify({photos:"SELECT src, src_big FROM photo WHERE aid = '"+f.aid+"'"}):JSON.stringify({photos:"SELECT src, src_big FROM photo WHERE aid = '"+f.aid+"' LIMIT "+e});var p="https://graph.facebook.com/fql?q="+
encodeURIComponent(k),g=b('<div class="album" id="'+f.name+'"></div>').append('<div class="title">'+f.name.replace(/[:]/g,"/")+'</div><div class="thumbs"></div>').hide();b("#"+c).append(g);b.browser.msie?b.ajax({url:p,dataType:"jsonp"}).success(function(d){m(1,b,a,c,d.data[0].fql_result_set,g,e,n)}):b.getJSON(p,function(d){m(1,b,a,c,d.data[0].fql_result_set,g,e,n)})}})}function m(b,c,a,d,e,h,n,k){var g=1==b?1:26*(b-1),m=[];b=e;var l=c.filo.root_path;if(void 0!=k.order&&"reverse"==k.order)b.reverse();
else if(void 0!=k.order&&"random"==k.order){for(var s=[],t=[];s.length<n&&s.length<b.length;){var u=Math.floor(Math.random()*b.length);void 0==t[u]&&(s.push(b[u]),t[u]=!0)}b=s}c.each(b,function(b,d){m[g-1]=d.src_big;var f=1==g?" first":"",t=g==n?" last":"",s=new Image;s.setAttribute("class","picture filo_picture");s.setAttribute("id",g-1);var u=0;s.onerror=function(){2>u?(console.log("load picture again: "+d.src),s.src=d.src,u++):(s.onerror=null,s.src=c.filo.root_path+c.filo.defaultImage)};s.src=
d.src;f=c('<div class="thumb thumb_'+g+f+t+'"><div class="inner"><a href="'+d.src_big+'"></a></div></div>');c(f).find("a").append(s);c(h).find(".thumbs").append(f);c(h).find(".filo_picture").unbind("click");c(h).find(".filo_picture").click(function(b){b.preventDefault();if(void 0!=k.href)return void 0!=k.method&&"post"==k.method.toLowerCase()?(b=!0==k.newWindow?'target="_blank"':"",c("body").append('<form id="filo_forward" '+b+' method="POST" action="'+k.href+'"><input name="profile" value="'+a+'" /><input name="album" value="'+
c(h).attr("id")+'" /></form>'),c("#filo_forward").trigger("submit").remove()):k.newWindow?window.open(k.href+"?profile="+a+"&album="+c(h).attr("id")):document.location=k.href+"?profile="+a+"&album="+c(h).attr("id"),!1;if(1>c(".filo_overlay").length){c.filo.closeButton=l+c.filo.closeButtons.black;void 0!=k.closeButton&&(c.filo.closeButton=void 0!=c.filo.closeButtons[k.closeButton]?l+c.filo.closeButtons[k.closeButton]:k.closeButton);var d=900;c.each(c("body *"),function(b,a){"auto"!=c(a).css("zIndex")&&
(d=Math.max(d,parseInt(c(a).css("zIndex"))))});b=void 0!=k.overlay?"background: "+k.overlay+"; ":"background: "+c.filo.overlayDefault+";";var f=void 0!=k.overlayOpacity?" opacity: "+k.overlayOpacity+";":" opacity: "+c.filo.overlayOpacityDefault+";";c("body").append('<div class="filo_overlay" style="z-index:'+(d+1)+';" ><div class="filo_overlay_background" style="'+b+f+'"></div><div class="filo_overlay_container"><div class="filo_overlay_container_left"></div><div class="filo_overlay_container_right"></div><div class="picture_counter"></div></div></div>');
var e=new Image;e.onload=function(){c(".filo_overlay_container").append(e);var b=0<c(".filo_overlay_container").css("border-width")?c(".filo_overlay_container").css("border-width"):17;c(this).css("right",-1*(this.width/2+b));c(this).css("top",-1*(this.height/2+b));e.setAttribute("class","filo_overlay_container_close");c(".filo_overlay_container_close").click(function(){c(".filo_overlay").remove()})};e.src=c.filo.closeButton;q(c,c(this).attr("id"),m,c(h).attr("id"),k);c(".filo_overlay_background").click(function(b){"filo_overlay_background"==
c(b.target).attr("class")&&c(".filo_overlay").remove()});c(".filo_overlay_container_left").click(function(){var b=parseInt(c(".filo_full_picture").attr("id"));0<b&&q(c,b-1,m,c(h).attr("id"),k)});c(".filo_overlay_container_right").click(function(){var b=parseInt(c(".filo_full_picture").attr("id"));b<m.length-1&&q(c,b+1,m,c(h).attr("id"),k)});c(".filo_overlay_container_left").mouseenter(function(){c(this).css("backgroundColor","none").css("background-image","url('"+TemplateP+"/img/left_white.png')").css("background-repeat",
"no-repeat").css("background-position","left center")}).mouseout(function(){c(this).css("background-image","")});c(".filo_overlay_container_right").mouseenter(function(){c(this).css("backgroundColor","none").css("background-image","url('"+TemplateP+"/img/right_white.png')").css("background-repeat","no-repeat").css("background-position","right center")}).mouseout(function(){c(this).css("background-image","")})}});if(g>=n)return c(h).append('<div class="clear"></div>'),!1;g++;g==e.length&&c(h).append('<div class="clear"></div>')});
c.filo.isLoaded[d]+=1;c(h).fadeIn("slow");c.filo.isLoaded[d]==c.filo.toLoad[d]&&(c("#"+d+" .album").last().attr("class",c("#"+d+" .album").last().attr("class")+" last"),c("#"+d).append('<div class="clear"></div>'),c("#"+d+" .add").remove(),c("#"+d+" .excluded").remove(),c("#"+d+" .filo_loader").remove(),"function"==typeof k.load&&(d=jQuery.Event("FILo Load Event"),k.load(d)))}function q(b,c,a,d,e){b(".filo_overlay_container_left").show();b(".filo_overlay_container_right").show();0==c&&b(".filo_overlay_container_left").hide();
c==a.length-1&&b(".filo_overlay_container_right").hide();var h=parseInt(b(".filo_overlay_container").css("border-top-width").split("px")[0]),n=parseInt(b(".picture_counter").height()),k=(e.maxWidth?e.maxWidth:b.filo.maxWidth)/100;e=(e.maxHeight?e.maxHeight:b.filo.maxHeight)/100;var g=b(window).width()*k-h,m=b(window).height()*e-(h+n),l=new Image;l.onload=function(){var e=this.width,h=this.height,k,p;e>h?(k=e>g?g:e,p=k*h/e,p>m&&(p=h>m?m:h,k=p*e/h)):(p=h>m?m:h,k=p*e/h,k>g&&(k=e>g?g:e,p=k*h/e));0<b(".filo_overlay_container .filo_full_picture").length?
b(".filo_overlay_container .filo_full_picture").fadeOut(300,function(){b(l).css("display","none");l.width=k;l.height=p;b(".filo_overlay_container").width(k).height(p).css("margin-left",k/2*-1).css("margin-top",p/2*-1-n).prepend(l).find(l).fadeIn(300);b(this).remove();b(".filo_overlay_container_close").show();b(".filo_overlay_container .picture_counter").html("<span>Album: "+d+" | Pic: "+(parseInt(c)+1)+" of "+a.length+"</span>")}):(b(l).width(k).height(p),b(".filo_overlay_container").width(k).height(p).css("margin-left",
k/2*-1).css("margin-top",p/2*-1-n).prepend(l).fadeIn(300),b(".filo_overlay_container_close").show(),b(".filo_overlay_container .picture_counter").html("<span>Album: "+d+" | Pic: "+(parseInt(c)+1)+" of "+a.length+"</span>"));e=b(".filo_overlay_container .picture_counter span").width();b(".filo_overlay_container .picture_counter span").css("paddingLeft").split("px");h=b(".filo_overlay_container .picture_counter span").css("paddingRight").split("px")[0];b(".filo_overlay_container .picture_counter").width(e+
parseInt(h)+parseInt(h)).css("position","absolute").css("left","50%").css("marginLeft","-"+(e+parseInt(h)+parseInt(h))/2+"px")};l.setAttribute("class","filo_full_picture");l.setAttribute("id",c);l.src=a[c]}function e(b,c){if(0<b(".filo_overlay").length&&!b.filo.resize){b(".filo_full_picture").css("width","").css("height","");resize=!0;var a=(c.maxWidth?c.maxWidth:b.filo.maxWidth)/100,d=(c.maxHeight?c.maxHeight:b.filo.maxHeight)/100,e=parseInt(b(".filo_overlay_container").css("border-top-width").split("px")[0]),
h=parseInt(b(".picture_counter").height()),a=b(window).width()*a-e,d=b(window).height()*d-(e+h),e=parseInt(b(".filo_full_picture").width()),g=parseInt(b(".filo_full_picture").height()),k,l;e>g?(k=e>a?a:e,l=k*g/e,l>d&&(l=g>d?d:g,k=l*e/g)):(l=g>d?d:g,k=l*e/g,k>a&&(k=e>a?a:e,l=k*g/e));b(".filo_overlay_container img.filo_full_picture").width(k);b(".filo_overlay_container").width(k).height(l).css("margin-left",k/2*-1).css("margin-top",l/2*-1-h);resize=!1}}function l(b,a){for(var d=0;d<a.length;d++)if(b.toLowerCase()==
a[d].toLowerCase())return!0;return!1}a.fn.filo=function(b){if(a(this).length){void 0==b&&(b={container:this});-1==(void 0!=a(this).attr("class")&&a(this).attr("class").indexOf("template"))&&void 0!=b.template?a(this).addClass("template_"+b.template+" filo"):a(this).addClass("filo");var c=a(this).attr("id"),g=c+"_"+Date.now(),g=g.replace(".","");a(this).attr("id",g);d(a,g,c,b);a(window).unbind("resize");a(window).resize(function(){e(a,b)})}else console.log("filo container is undefined, please check the ID or class name")};
a.filo=function(b,c){void 0==c?c={container:"body"}:void 0==c.container&&(c.container="body");var g=b+"_"+Date.now(),g=g.replace(".",""),f=void 0!=c.template?"template_"+c.template:"";a(c.container).append('<div class="filo '+f+'" id="'+g+'"></div>');d(a,g,b,c);a(window).unbind("resize");a(window).resize(function(){e(a,c)})};jQuery.filo.getUrlParams=function(){for(var a=[],c,d=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),e=0;e<d.length;e++)c=d[e].split("="),a.push(c[0]),
a[c[0]]=c[1];return a};a(document).ready(function(){a.filo.toLoad=[];a.filo.isLoaded=[];a.filo.maxCountDefault=3;a.filo.overlayDefault="rgb(177,177,177)";a.filo.overlayOpacityDefault=.5;a.filo.photos_array=null;a.filo.resize=!1;a.filo.closeButtons={black:"/../img/close_black.png",white:"/../img/close_white.png"};a.filo.defaultImage="/../img/default.png";a.filo.order=["normal","reverse","random"];a.filo.method="post";a.filo.newWindow=!1;var b=a.filo,c;a:{try{throw Error();}catch(g){var f="";void 0!=
g.fileName?f=g.fileName.split("/"):(c=document.getElementsByTagName("script"),a.each(c,function(a,b){0<=b.src.indexOf("filo.js")&&(f=b.src.split("/"))}));if(""==f){c="filo/";break a}}c="";for(var l=0;l<f.length-1;l++)c=l<f.length-2?c+(f[l]+"/"):c+f[l]}b.root_path=c;a.filo.ie=!1;a.support.cors=!0;a.filo.maxHeight=90;a.filo.maxWidth=90;var h=[];a.each(a(".filo"),function(b,c){var g=a(c).attr("id"),f=g+"_"+Date.now()+"_"+Math.round(1E5*Math.random()),f=f.replace(".","");a(c).attr("id",f);void 0!=a("#"+
f).attr("maxCount")&&(h.maxCount=a("#"+f).attr("maxCount"));void 0!=a("#"+f).attr("href")&&(h.href=a("#"+f).attr("href"));void 0!=a("#"+f).attr("newWindow")&&(h.newWindow="true"==a("#"+f).attr("newWindow")?!0:!1);h.method=void 0!=a("#"+f).attr("method")?a("#"+f).attr("method"):"post";d(a,f,g,h);a(window).unbind("resize");a(window).resize(function(){e(a,h)})})});"undefined"==typeof a.browser&&(a.browser={msie:"Microsoft Internet Explorer"==navigator.appName});Date.now=Date.now||function(){return+new Date}})(jQuery);
window.fbAsyncInit=function(){FB.init({appId:"118671008210303",xfbml:!0,version:"v2.0"})};(function(a,d,g){var m=a.getElementsByTagName(d)[0];a.getElementById(g)||(a=a.createElement(d),a.id=g,a.src="//connect.facebook.net/en_US/sdk.js",m.parentNode.insertBefore(a,m))})(document,"script","facebook-jssdk");
$(document).ready(function(){$("a[href*='http://']:not([href*='"+location.hostname+"']),[href*='https://']:not([href*='"+location.hostname+"'])").attr("target","_blank").attr("title","Opens new window").addClass("external")});
$(document).ready(function(){
	
	//Check to see if the window is top if not then display button
	$(window).scroll(function(){
		if ($(this).scrollTop() > 100) {
			$('.scrollToTop').fadeIn();
		} else {
			$('.scrollToTop').fadeOut();
		}
	});
	
	//Click event to scroll to top
	$('.scrollToTop').click(function(){
		$('html, body').animate({scrollTop : 0},800);
		return false;
	});
	
});
