name: Request to increase package size limit
description: Request a higher limit for your package.
title: "Increase package size limit for {{PROJECT NAME}}"
body:
  - type: dropdown
    attributes:
      label: Type
      options:
        - NPM Package
        - GitHub Repository
    validations:
      required: true

  - type: textarea
    attributes:
      label: Links
      description: Links to the NPM Package or Github Repository. A link to GitHub is always preferred.
      placeholder: |
        https://github.com/jsdelivr/jsdelivr
        https://npmjs.com/jsdelivr
    validations:
      required: true

  - type: input
    attributes:
      label: Project License
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Relationship
      options:
        - Maintainer
        - User
    validations:
      required: true

  - type: textarea
    attributes:
      label: Short description of the project
      description: Help us better understand your project.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Requisites
      description: |
        Please, confirm and check each one of the checkboxes.
      options:
        - label: There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
          required: true
        - label: The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).
          required: true
        - label: I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
          required: true
        - label: I understand that not filling out this template correctly will lead to the issue being closed.
          required: true

  - type: textarea
    attributes:
      label: Additional content
      description: Anything you want to add.
    validations:
