name: Other
description: Anything that doesn't fit into the categories above
title: ""
body:
  - type: markdown
    attributes:
      value: |
        Is your issue related to a specific project?
        Please include all relevant links to cdn.jsdelivr.net, npm, GitHub, and your relation to the project.

  - type: textarea
    attributes:
      label: Description
      description: Describe your problem.
    validations:
      required: true
