/*
 miq 1.4.0

 @copyright Copyright 2015 Edwin Martin

 @see {@link http://www.bitstorm.org/javascript/miq/|miq}

 @license MIT
*/
function miq(a,b){if("function"==typeof a)document.addEventListener("DOMContentLoaded",a);else{var c=Object.create(miq.fn),d;if("object"==typeof a)if(Array.isArray(a)){for(d=0;d<a.length;d++)c[d]=a[d];c.length=a.length}else c[0]=a,c.length=1;else if(a)if(d=a.match(/<(.+)>/))c[0]=(b||document).createElement(d[1]),c.length=1;else{var e=(b||document).querySelectorAll(a);for(d=0;d<e.length;d++)c[d]=e[d];c.length=e.length}else c.length=0;return c}}
miq.fn=Object.create(Array.prototype,{miq:{value:"1.4.0"},first:{get:function(){return this[0]}},get:{value:function(a){return $(this[a||0])}},on:{value:function(a,b){this.forEach(function(c){c.addEventListener(a,b)});return this}},off:{value:function(a,b){this.forEach(function(c){c.removeEventListener(a,b)});return this}},addClass:{value:function(a){this.forEach(function(b){b.className=b.className+" "+a});return this}},removeClass:{value:function(a){this.forEach(function(b){b.className=b.className.replace(a,
"")});return this}},hasClass:{value:function(a){return""!=this.first.className&&(new RegExp("\\b"+a+"\\b")).test(this.first.className)}},prop:{value:function(a,b){if("undefined"==typeof b)return this.first[a];this.forEach(function(c){c[a]=b});return this}},attr:{value:function(a,b){if("undefined"==typeof b)return this.first.getAttribute(a);this.forEach(function(c){c.setAttribute(a,b)});return this}},removeAttr:{value:function(a){this.forEach(function(b){b.removeAttribute(a)});return this}},val:{value:function(a){if("undefined"==
typeof a)return this.first.value;this.forEach(function(b){b.value=a});return this}},data:{value:function(a,b){if("undefined"==typeof b)return miq.dataStore[this.first._miqData||0];this.forEach(function(a){a.first._miqData=miq.dataCounter;miq.dataStore[miq.dataCounter]=b;miq.dataCounter++});return this}},append:{value:function(a){var b=this;miq(a).forEach(function(a){b.first.appendChild(a.first)});return this}},find:{value:function(a){return miq(a,this.first)}},remove:{value:function(a){this.forEach(function(a){a.parentNode.removeChild(a)});
return this}},closest:{value:function(a){var b=this.first;do if(b[miq.matches](a))return miq(b);while(b=b.parentElement);return null}},matches:{value:function(a){return miq(this.filter(function(b){return b[miq.matches](a)}))}},css:{value:function(a,b){if("undefined"==typeof b)return this.first.style[a];this.forEach(function(c){c.style[a]=b});return this}},html:{value:function(a){if("undefined"==typeof a)return this.first.innerHTML;this.forEach(function(b){b.innerHTML=a});return this}},text:{value:function(a){if("undefined"==
typeof a)return this.first.textContent;this.forEach(function(b){b.textContent=a});return this}},ajaxCallback:{value:function(a,b,c,d){var e=new XMLHttpRequest;e.onreadystatechange=function(){var a;if(4==e.readyState)if(200==e.status){switch(d.type){case "xml":a=e.responseXML;break;case "json":a=JSON.parse(e.responseText);break;default:a=e.responseText}b(a)}else c&&c("Ajax error: "+e.status)};e.open(d.method||"GET",a,!0);if(d.headers)for(var f in d.headers)e.setRequestHeader(f,d.headers[f]);e.send(d.data||
"")}},ajax:{value:function(a,b){return new Promise(function(c,d){miq().ajaxCallback(a,c,d,b)})}}});miq.dataStore=[null];miq.dataCounter=1;miq.matches=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector"].filter(function(a){return a in document.documentElement})[0];"undefined"==typeof $&&($=miq);
