//>>built
/*

 Lo-Dash 1.3.1 (Custom Build) <http://lodash.com/>
 Build: `lodash modern -o ./dist/lodash.js`
 Copyright 2012-2013 The Dojo Foundation <http://dojofoundation.org/>
 Based on Underscore.js 1.4.4 <http://underscorejs.org/>
 Copyright 2009-2013 Jeremy Ashkenas, DocumentCloud Inc.
 Available under MIT license <http://lodash.com/license>
*/
(function(c,f){var h,a,k,n=function(){},g=function(a){for(var b in a)return 0;return 1},b={}.toString,d=function(a){return"[object Function]"==b.call(a)},m=function(a){return"[object String]"==b.call(a)},e=function(a){return"[object Array]"==b.call(a)},i=function(a,b){if(a)for(var d=0;d<a.length;)b(a[d++])},l=function(a,b){for(var d in b)a[d]=b[d];return a},q=function(a,b){return l(Error(a),{src:"dojoLoader",info:b})},x=1,A=function(){return"_"+x++},o=function(a,b,d){return fa(a,b,d,0,o)},t=this,
p=t.document,Ga=p&&p.createElement("DiV"),s=o.has=function(a){return d(r[a])?r[a]=r[a](t,p,Ga):r[a]},r=s.cache=f.hasCache;s.add=function(a,b,d,e){(void 0===r[a]||e)&&(r[a]=b);return d&&s(a)};for(var u in c.has)s.add(u,c.has[u],0,1);o.async=1;var F=new Function("return eval(arguments[0]);");o.eval=function(a,b){return F(a+"\r\n////@ sourceURL="+b)};var C={},v=o.signal=function(a,b){var d=C[a];i(d&&d.slice(0),function(a){a.apply(null,e(b)?b:[b])})},ua=o.on=function(a,b){var d=C[a]||(C[a]=[]);d.push(b);
return{remove:function(){for(var a=0;a<d.length;a++)if(d[a]===b){d.splice(a,1);break}}}},Oa=[],Pa={},ga=[],va={},Qa=o.map={},aa=[],G={},Ha="",ha={},wa={};u={};var U=function(a){var b,d,e,i;for(b in wa)d=wa[b],(e=b.match(/^url\:(.+)/))?ha["url:"+xb(e[1],a)]=d:"*now"==b?i=d:"*noref"!=b&&(e=Ra(b,a),ha[e.mid]=ha["url:"+e.url]=d);i&&i(T(a));wa={}},oa=function(a){return a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})},ba=function(a,b){b.splice(0,b.length);for(var d in a)b.push([d,a[d],
RegExp("^"+oa(d)+"(/|$)"),d.length]);b.sort(function(a,b){return b[3]-a[3]});return b},ia=function(a){var b=a.name;b||(b=a,a={name:b});a=l({main:"main"},a);a.location=a.location?a.location:b;if(a.packageMap)Qa[b]=a.packageMap;if(!a.main.indexOf("./"))a.main=a.main.substring(2);va[b]=a},Ia=[],P=function(a,b,d){for(var e in a){if("waitSeconds"==e)o.waitms=1E3*(a[e]||0);"cacheBust"==e&&(Ha=a[e]?m(a[e])?a[e]:(new Date).getTime()+"":"");if("baseUrl"==e||"combo"==e)o[e]=a[e];a[e]!==r&&(o.rawConfig[e]=a[e],
"has"!=e&&s.add("config-"+e,a[e],0,b))}if(!o.baseUrl)o.baseUrl="./";/\/$/.test(o.baseUrl)||(o.baseUrl+="/");for(e in a.has)s.add(e,a.has[e],0,b);i(a.packages,ia);for(k in a.packagePaths)i(a.packagePaths[k],function(a){var b=k+"/"+a;m(a)&&(a={name:a});a.location=b;ia(a)});ba(l(Qa,a.map),aa);i(aa,function(a){a[1]=ba(a[1],[]);if("*"==a[0])aa.star=a});ba(l(Pa,a.paths),ga);i(a.aliases,function(a){m(a[0])&&(a[0]=RegExp("^"+oa(a[0])+"$"));Oa.push(a)});if(b)Ia.push({config:a.config});else for(e in a.config)b=
V(e,d),b.config=l(b.config||{},a.config[e]);if(a.cache)U(),wa=a.cache,a.cache["*noref"]&&U();v("config",[a,o.rawConfig])};o.rawConfig={};P(f,1);P(c,1);P(u,1);var L=function(a){pa(function(){i(a.deps,Ja)})},fa=function(a,b,d,i,c){var g;if(m(a)){if((g=V(a,i,!0))&&g.executed)return g.result;throw q("undefinedModule",a);}e(a)||(P(a,0,i),a=b,b=d);if(e(a))if(a.length){for(var d="require*"+A(),h,k=[],f=0;f<a.length;)h=a[f++],k.push(V(h,i));g=l(j("",d,0,""),{injected:2,deps:k,def:b||n,require:i?i.require:
o,gc:1});G[g.mid]=g;L(g);var p=X&&0!="sync";pa(function(){xa(g,p)});g.executed||y.push(g);w()}else b&&b();return c},T=function(a){if(!a)return o;var b=a.require;if(!b)b=function(d,e,i){return fa(d,e,i,a,b)},a.require=l(b,o),b.module=a,b.toUrl=function(b){return xb(b,a)},b.toAbsMid=function(b){return lb(b,a)};return b},y=[],B=[],z={},ja=function(a){a.injected=1;z[a.mid]=1;a.url&&(z[a.url]=a.pack||1);Ta()},ka=function(a){a.injected=2;delete z[a.mid];a.url&&delete z[a.url];g(z)&&Ka()},Y=o.idle=function(){return!B.length&&
g(z)&&!y.length&&!X},O=function(a,b){if(b)for(var d=0;d<b.length;d++)if(b[d][2].test(a))return b[d];return 0},yb=function(a){for(var b=[],d,e,a=a.replace(/\\/g,"/").split("/");a.length;)d=a.shift(),".."==d&&b.length&&".."!=e?(b.pop(),e=b[b.length-1]):"."!=d&&b.push(e=d);return b.join("/")},j=function(a,b,d,e){return{pid:a,mid:b,pack:d,url:e,executed:0,def:0}},zb=function(a,b,e,g,c,k,f,n){var m,l,o,p;p=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||p&&!b)return j(0,a,0,a);a=yb(p?b.mid+"/../"+a:a);
if(/^\./.test(a))throw q("irrationalPath",a);b&&(o=O(b.mid,k));(o=(o=o||k.star)&&O(a,o[1]))&&(a=o[1]+a.substring(o[3]));b=(h=a.match(/^([^\/]+)(\/(.+))?$/))?h[1]:"";(m=e[b])?a=b+"/"+(l=h[3]||m.main):b="";var t=0;i(Oa,function(b){var e=a.match(b[0]);e&&0<e.length&&(t=d(b[1])?a.replace(b[0],b[1]):b[1])});if(t)return zb(t,0,e,g,c,k,f,n);if(e=g[a])return n?j(e.pid,e.mid,e.pack,e.url):g[a];g=(o=O(a,f))?o[1]+a.substring(o[3]):b?m.location+"/"+l:a;/(^\/)|(\:)/.test(g)||(g=c+g);return j(b,a,m,yb(g+".js"))},
Ra=function(a,b){return zb(a,b,va,G,o.baseUrl,aa,ga)},Ab=function(a,b,d){return a.normalize?a.normalize(b,function(a){return lb(a,d)}):lb(b,d)},Bb=0,V=function(a,b,d){var e,i;(e=a.match(/^(.+?)\!(.*)$/))?(i=V(e[1],b,d),5===i.executed&&!i.load&&da(i),i.load?(e=Ab(i,e[2],b),a=i.mid+"!"+(i.dynamic?++Bb+"!":"")+e):(e=e[2],a=i.mid+"!"+ ++Bb+"!waitingForPlugin"),a={plugin:i,mid:a,req:T(b),prid:e}):a=Ra(a,b);return G[a.mid]||!d&&(G[a.mid]=a)},lb=o.toAbsMid=function(a,b){return Ra(a,b).mid},xb=o.toUrl=function(a,
b){var d=Ra(a+"/x",b),e=d.url;return ya(0===d.pid?a:e.substring(0,e.length-5))},za={injected:2,executed:5,def:3,result:3},Q=function(a){return G[a]=l({mid:a},za)},Ua=Q("require"),la=Q("exports"),Z=Q("module"),H={},Aa=0,da=function(a){var b=a.result;a.dynamic=b.dynamic;a.normalize=b.normalize;a.load=b.load;return a},Va=function(a){var b={};i(a.loadQ,function(d){var e=Ab(a,d.prid,d.req.module),i=a.dynamic?d.mid.replace(/waitingForPlugin$/,e):a.mid+"!"+e,e=l(l({},d),{mid:i,prid:e,injected:0});G[i]||
Ma(G[i]=e);b[d.mid]=G[i];ka(d);delete G[d.mid]});a.loadQ=0;var d=function(a){for(var d=a.deps||[],e=0;e<d.length;e++)(a=b[d[e].mid])&&(d[e]=a)},e;for(e in G)d(G[e]);i(y,d)},qa=function(b){o.trace("loader-finish-exec",[b.mid]);b.executed=5;b.defOrder=Aa++;b.loadQ&&(da(b),Va(b));for(a=0;a<y.length;)y[a]===b?y.splice(a,1):a++;/^require\*/.test(b.mid)&&delete G[b.mid]},Wa=[],xa=function(a,b){if(4===a.executed)return o.trace("loader-circular-dependency",[Wa.concat(a.mid).join("->")]),!a.def||b?H:a.cjs&&
a.cjs.exports;if(!a.executed){if(!a.def)return H;var e=a.mid,i=a.deps||[],g,c=[],h=0;for(a.executed=4;h<i.length;){g=i[h++];g=g===Ua?T(a):g===la?a.cjs.exports:g===Z?a.cjs:xa(g,b);if(g===H)return a.executed=0,o.trace("loader-exec-module",["abort",e]),H;c.push(g)}o.trace("loader-run-factory",[a.mid]);e=a.def;c=d(e)?e.apply(null,c):e;a.result=void 0===c&&a.cjs?a.cjs.exports:c;qa(a)}return a.result},X=0,pa=function(a){try{X++,a()}finally{X--}Y()&&v("idle",[])},w=function(){X||pa(function(){for(var a,
b,d=0;d<y.length;)a=Aa,b=y[d],xa(b),a!=Aa?d=0:d++})};void 0===s("dojo-loader-eval-hint-url")&&s.add("dojo-loader-eval-hint-url",1);var ya=function(a){a+="";return a+(Ha?(/\?/.test(a)?"&":"?")+Ha:"")},Ma=function(a){var b=a.plugin;5===b.executed&&!b.load&&da(b);var d=function(b){a.result=b;ka(a);qa(a);w()};b.load?b.load(a.prid,a.req,d):b.loadQ?b.loadQ.push(a):(b.loadQ=[a],y.unshift(b),Ja(b))},ma=0,ra=0,Ba=0,Xa=function(a,b){s("config-stripStrict")&&(a=a.replace(/"use strict"/g,""));Ba=1;a===ma?ma.call(null):
o.eval(a,s("dojo-loader-eval-hint-url")?b.url:b.mid);Ba=0},Ja=function(a){var b=a.mid,d=a.url;if(!a.executed&&!a.injected&&!(z[b]||a.url&&(a.pack&&z[a.url]===a.pack||1==z[a.url])))if(ja(a),a.plugin)Ma(a);else{var e=function(){Ya(a);2!==a.injected&&(ka(a),l(a,za),o.trace("loader-define-nonmodule",[a.url]));w()};(ma=ha[b]||ha["url:"+a.url])?(o.trace("loader-inject",["cache",a.mid,d]),Xa(ma,a),e()):(o.trace("loader-inject",["script",a.mid,d]),ra=a,o.injectUrl(ya(d),e,a),ra=0)}},sa=function(a,b,e){o.trace("loader-define-module",
[a.mid,b]);if(2===a.injected)return v("error",q("multipleDefine",a)),a;l(a,{deps:b,def:e,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(b){a.cjs.exports=b},config:function(){return a.config}}});for(var i=0;i<b.length;i++)b[i]=V(b[i],a);ka(a);if(!d(e)&&!b.length)a.result=e,qa(a);return a},Ya=function(a,b){for(var d=[],e,g;B.length;)g=B.shift(),b&&(g[0]=b.shift()),e=g[0]&&V(g[0])||a,d.push([e,g[1],g[2]]);U(a);i(d,function(a){L(sa.apply(null,a))})},Ka=n,Ta=n;s.add("ie-event-behavior",
!!p.attachEvent&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var Ca=function(a,b,d,e){if(s("ie-event-behavior"))return a.attachEvent(d,e),function(){a.detachEvent(d,e)};a.addEventListener(b,e,!1);return function(){a.removeEventListener(b,e,!1)}},Za=Ca(window,"load","onload",function(){o.pageLoaded=1;"complete"!=p.readyState&&(p.readyState="complete");Za()}),Da=p.getElementsByTagName("script")[0],$a=Da.parentNode;o.injectUrl=function(a,b,d){var d=d.node=p.createElement("script"),
e=Ca(d,"load","onreadystatechange",function(a){var a=a||window.event,d=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(d.readyState))e(),i(),b&&b()}),i=Ca(d,"error","onerror",function(b){e();i();v("error",q("scriptError",[a,b]))});d.type="text/javascript";d.charset="utf-8";d.src=a;$a.insertBefore(d,Da);return d};o.log=n;o.trace=n;Q=function(a,b,e){var i=arguments.length,g=["require","exports","module"],c=[0,a,b];1==i?c=[0,d(a)?g:[],a]:2==i&&m(a)?c=[a,d(b)?g:[],b]:3==i&&(c=[a,b,e]);
o.trace("loader-define",c.slice(0,2));if((i=c[0]&&V(c[0]))&&!z[i.mid])L(sa(i,c[1],c[2]));else if(!s("ie-event-behavior")||Ba)B.push(c);else{i=i||ra;if(!i)for(a in z)if((g=G[a])&&g.node&&"interactive"===g.node.readyState){i=g;break}i?(U(i),L(sa(i,c[1],c[2]))):v("error",q("ieDefineFailed",c[0]));w()}};Q.amd={vendor:"dojotoolkit.org"};l(l(o,f.loaderPatch),c.loaderPatch);ua("error",function(a){try{if(console.error(a),a instanceof Error)for(var b in a);}catch(d){}});l(o,{uid:A,cache:ha,packs:va});if(!t.define)t.define=
Q,t.require=o,i(Ia,function(a){P(a)}),ua=u.deps||c.deps||f.deps,u=u.callback||c.callback||f.callback,o.boot=ua||u?[ua||[],u]:0})(this.dojoConfig||this.djConfig||this.require||{},{async:1,baseUrl:"./",hasCache:{"config-selectorEngine":"acme","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:"../frozen",main:"GameCore",name:"frozen"},{location:".",name:"dojo"},{location:"../dcl",main:"dcl",name:"dcl"},{location:"../lodash",main:"lodash",name:"lodash"},
{location:"../hammer",main:"hammer",name:"hammer"}]});
require({cache:{"dist/frozen":function(){define([],1)},"frozen/box2d/BoxGame":function(){define("frozen/box2d/BoxGame",["../GameCore","./Box","lodash","dcl"],function(c,f,h,a){return a(c,{box:null,boxUpdating:!0,entities:null,joints:null,constructor:function(){if(!this.box)this.box=new f;if(!this.entities)this.entities={};if(!this.joints)this.joints={}},beforeUpdate:function(a){this.boxUpdating&&(this.box.update(a),this.box.updateExternalState(this.entities))},addBody:function(a){this.entities[a.id]=
a;this.box.addBody(a)},addBodies:function(){var a=h.flatten(arguments,!0),c=this;h.forEach(a,function(a){c.addBody(a)})},removeBody:function(a){this.box.removeBody(a.id);delete this.entities[a.id]},removeBodies:function(){var a=h.flatten(arguments,!0),c=this;h.forEach(a,function(a){c.removeBody(a)})},addJoint:function(a){this.joints[a.id]=a;this.box.addJoint(a)},addJoints:function(){var a=h.flatten(arguments,!0),c=this;h.forEach(a,function(a){c.addJoint(a)})},removeJoint:function(a){this.box.removeJoint(a.id);
delete this.joints[a.id]},removeJoints:function(){var a=h.flatten(arguments,!0),c=this;h.forEach(a,function(a){c.removeJoint(a)})}})})},"frozen/GameCore":function(){define("frozen/GameCore","dcl,dcl/advise,dcl/bases/Mixer,lodash,./InputManager,./ResourceManager,./shims/RAF".split(","),function(c,f,h,a,k,n){return c(h,{statics:{FONT_SIZE:24},isRunning:!1,canvasId:null,maxStep:40,contextType:"2d",height:0,width:0,resourceManager:null,inputManager:null,loadingForeground:"#00F",loadingBackground:"#FFF",
gameAreaId:null,canvasPercentage:0,constructor:function(){var a=this.preUpdate||this.beforeUpdate;a&&f.before(this,"update",a)},setHeight:function(a){this.height=a;this.canvas.height=a},setWidth:function(a){this.width=a;this.canvas.width=a},stop:function(){this.isRunning=!1},run:function(){this.isRunning||(this.init(),this.loadResources(this.resourceManager),this.initInput(this.inputManager),this.launchLoop())},loadResources:function(){},init:function(){if(!this.canvas)this.canvas=document.getElementById(this.canvasId);
if(this.canvas){if(!this.context)this.context=this.canvas.getContext(this.contextType);if(this.context){this.setHeight(this.height||this.canvas.height);this.setWidth(this.width||this.canvas.width);if(!this.inputManager)this.inputManager=this.gameAreaId&&this.canvasPercentage?new k({canvas:this.canvas,gameArea:document.getElementById(this.gameAreaId),canvasPercentage:this.canvasPercentage}):new k({canvas:this.canvas});this.inputManager.resize();if(!this.resourceManager)this.resourceManager=new n;this.loadResources(this.resourceManager);
this.isRunning=!0}else alert("Sorry, your browser does not support a "+this.contextType+" drawing surface on canvas.  I recommend any browser but Internet Explorer")}else alert("Sorry, your browser does not support canvas.  I recommend any browser but Internet Explorer")},initInput:function(){},handleInput:function(){},gameLoop:function(){this.currTime=(new Date).getTime();this.elapsedTime=Math.min(this.currTime-this.prevTime,this.maxStep);this.prevTime=this.currTime;this.resourceManager&&!this.resourceManager.resourcesReady()?
(this.updateLoadingScreen(this.elapsedTime),this.drawLoadingScreen(this.context)):(this.handleInput(this.inputManager,this.elapsedTime),this.paused||this.update(this.elapsedTime),this.context.save(),this.draw(this.context),this.context.restore())},launchLoop:function(){this.elapsedTime=0;var c=Date.now();this.prevTime=this.currTime=c;this.loopRunner=a.bind(this.loopRunner,this);window.requestAnimationFrame(this.loopRunner)},loopRunner:function(){this.gameLoop();window.requestAnimationFrame(this.loopRunner)},
update:function(){},updateLoadingScreen:function(){},draw:function(a){if("2d"===this.contextType)a.font="14px sans-serif",a.fillText("This game does not have its own draw function!",10,50)},drawLoadingScreen:function(a){if(this.resourceManager&&"2d"===this.contextType)a.fillStyle=this.loadingBackground,a.fillRect(0,0,this.width,this.height),a.fillStyle=this.loadingForeground,a.strokeStyle=this.loadingForeground,a.font="bold "+Math.floor(this.height/12)+"px sans-serif",a.fillText("Loading... "+this.resourceManager.getPercentComplete()+
"%",0.1*this.width,0.55*this.height),a.strokeRect(0.1*this.width,0.7*this.height,0.8*this.width,0.1*this.height),a.fillRect(0.1*this.width,0.7*this.height,0.8*this.width*this.resourceManager.getPercentComplete()/100,0.1*this.height),a.lineWidth=4}})})},"dcl/dcl":function(){(function(c){"undefined"!=typeof define?define(["./mini"],c):"undefined"!=typeof module?module.exports=c(require("./mini")):dcl=c(dcl)})(function(c){function f(){}function h(a,c,b){var d=a||f,h=c||f,e=b||f,i=function(){var a;d.apply(this,
arguments);try{a=e.apply(this,arguments)}catch(b){a=b}h.call(this,arguments,a);if(a instanceof Error)throw a;return a};i.advices={b:a,a:c,f:b};return i}function a(a){return function(g,b){var d=g._m,h;d&&((h=+d.w[b]||0)&&h!=a&&c._e("set chaining",b,g,a,h),d.w[b]=a)}}var k=c(c.Super,{constructor:function(){this.b=this.f.before;this.a=this.f.after;this.f=this.f.around}});c.mix(c,{Advice:k,advise:function(a){return new k(a)},before:function(a){return new k({before:a})},after:function(a){return new k({after:a})},
around:c.superCall,chainBefore:a(1),chainAfter:a(2),isInstanceOf:function(a,c){if(a instanceof c)return!0;var b=a.constructor._m,d;if(b)for(b=b.b,d=b.length-1;0<=d;--d)if(b[d]===c)return!0;return!1},_sb:function(a,g,b,d){var d=d[b]=c._ec(g,b,"f"),k=c._ec(g,b,"b").reverse(),g=c._ec(g,b,"a"),d=a?c._st(d,1==a?function(a){return c._sc(a.reverse())}:c._sc,b):c._ss(d,b);return!k.length&&!g.length?d||function(){}:h(c._sc(k),c._sc(g),d)}});return c})},"dcl/mini":function(){(function(c){"undefined"!=typeof define?
define([],c):"undefined"!=typeof module?module.exports=c():dcl=c()})(function(){function c(b,e){var i=[0],g,f,m,l,s,r,u,F,C=0,v;if(b)if(b instanceof Array){l={};u=b.slice(0).reverse();for(F=u.length-1;0<=F;--F)if(f=u[F],f._u=f._u||a++,g=f._m){for(r=g.b,C=r.length-1;0<C;--C)v=r[C]._u,l[v]=(l[v]||0)+1;u[F]=r.slice(0)}else u[F]=[f];s={};a:for(;u.length;){for(F=0;F<u.length;++F)if(r=u[F],f=r[0],v=f._u,!l[v]){s[v]||(i.push(f),s[v]=1);r.shift();r.length?--l[r[0]._u]:u.splice(F,1);continue a}c._e("cycle",
e,u)}b=b[0];C=i.length-((l=b._m)&&b===i[i.length-(C=l.b.length)]?C:1)-1}else b._u=b._u||a++,i=i.concat((l=b._m)?l.b:b);g=b?c.delegate(b[n]):{};for(r=b&&(l=b._m)?c.delegate(l.w):{constructor:2};0<C;--C)if(f=i[C],l=f._m,d(g,l&&l.h||f[n]),l)for(v in u=l.w)r[v]=(+r[v]||0)|u[v];for(v in e)h(l=e[v])?r[v]=+r[v]||0:g[v]=l;s={b:i,h:e,w:r,c:{}};i[0]={_m:s,prototype:g};f=g;l=s.w;r=s.b;u=s.c;for(m in l)f[m]=c._sb(l[m],r,m,u);m=g[k];m._m=s;m[n]=g;i[0]=m;return c._p(m)}function f(a){this.f=a}function h(a){return a instanceof
f}var a=0,k="constructor",n="prototype",g=function(){},b={},d,m,e,i,l;(d=function(a,b){for(var d in b)a[d]=b[d]})(c,{mix:d,delegate:function(a){g[n]=a;a=new g;g[n]=null;return a},Super:f,superCall:function(a){return new f(a)},_p:function(a){return a},_e:function(a){throw Error("dcl: "+a);},_f:function(a,b){var d=a.f(b);d.ctr=a.ctr;return d},_ec:m=function(a,d,e){for(var i=a.length-1,c=[],g,k,f="f"==e;g=a[i];--i)if((k=g._m)?(k=k.h).hasOwnProperty(d)&&(h(k=k[d])?f?k.f:k=k[e]:f):f&&(k=g[n][d])&&k!==
b[d])k.ctr=g,c.push(k);return c},_sc:i=function(a){var b=a.length,d;return!b?0:1==b?(d=a[0],function(){d.apply(this,arguments)}):function(){for(var d=0;d<b;++d)a[d].apply(this,arguments)}},_ss:e=function(a,d){for(var e=0,i,g=b[d];i=a[e];++e)g=h(i)?a[e]=c._f(i,g,d):i;return d!=k?g:function(){g.apply(this,arguments)}},_st:l=function(a,b,d){for(var e=0,i,g,f=0;i=a[e];++e)h(i)&&(g=e-f,a[e]=c._f(i,!g?0:1==g?a[f]:b(a.slice(f,e)),d),f=e);g=e-f;return!g?0:1==g&&d!=k?a[f]:b(f?a.slice(f):a)},_sb:function(a,
b,d,c){b=c[d]=m(b,d,"f");return(a?l(b,i,d):e(b,d))||function(){}}});return c})},"dcl/advise":function(){(function(c){"undefined"!=typeof define?define([],c):"undefined"!=typeof module?module.exports=c():advise=c()})(function(){function c(a,c){this.nb=this.pb=this.na=this.pa=this.nf=this.pf=this;this.i=a;this.n=c}function f(a){var c=function(){var c,b,d=arguments;for(c=a.pb;c!==a;c=c.pb)c.b.apply(this,d);try{a.pf!==a&&(b=a.pf.f.apply(this,d))}catch(h){b=h}for(c=a.na;c!==a;c=c.na)c.a.call(this,d,b);
if(b instanceof Error)throw b;return b};c.adviceNode=a;return c}function h(a,h,g){var b=a[h],d;b&&b.adviceNode&&b.adviceNode instanceof c?d=b.adviceNode:(d=new c(a,h),b&&b.advices?(b=b.advices,d.a(b.b,b.a,b.f)):d.a(0,0,b),a[h]=f(d));"function"==typeof g&&(g=g(h,a));return d.a(g.before,g.after,0,g.around)}var a=c.prototype={a:function(a,f,g,b){var d=new c(this.i,this.n);d.p=this;d.b=a;this._a("b",d);d.a=f;this._a("a",d);d.f=g;this._a("f",d,b);if(d.o=b)d.f=h._f(b,d.pf.f,this);return d},_a:function(a,
c,g){if(c[a]||g)g="n"+a,a="p"+a,(c[a]=this[a])[g]=(c[g]=this)[a]=c},r:function(a){this._r("b",a);this._r("a",a);this._r("f",a)},_r:function(a,c){var g="n"+a,b="p"+a;c[g][b]=c[b];c[b][g]=c[g]},destroy:function(){var a=this.pf.f,c=this.nf,g=this.p;this.r(this);if(c!==this)for(;c!==g;a=c.f,c=c.nf)if(c.o)c.f=h._f(c.o,a,this);this.i=0}};a.unadvise=a.destroy;h.before=function(a,c,g){return h(a,c,{before:g})};h.after=function(a,c,g){return h(a,c,{after:g})};h.around=function(a,c,g){return h(a,c,{around:g})};
h.Node=c;h._f=function(a,c){return a(c)};return h})},"dcl/bases/Mixer":function(){(function(c){"undefined"!=typeof define?define(["../mini"],c):"undefined"!=typeof module?module.exports=c(require("../mini")):dclBasesMixer=c(dcl)})(function(c){return c(null,{declaredClass:"dcl/bases/Mixer",constructor:function(f){c.mix(this,f)}})})},"lodash/lodash":function(){(function(c){function f(a,b,d){for(var d=(d||0)-1,e=a.length;++d<e;)if(a[d]===b)return d;return-1}function h(a,b){var d=typeof b,a=a.cache;if("boolean"==
d||null==b)return a[b];"number"!=d&&"string"!=d&&(d="object");var e="number"==d?b:Ga+b,a=a[d]||(a[d]={});return"object"==d?a[e]&&-1<f(a[e],b)?0:-1:a[e]?0:-1}function a(a){var b=this.cache,d=typeof a;if("boolean"==d||null==a)b[a]=!0;else{"number"!=d&&"string"!=d&&(d="object");var e="number"==d?a:Ga+a,c=b[d]||(b[d]={});if("object"==d){if((c[e]||(c[e]=[])).push(a)==this.array.length)b[d]=!1}else c[e]=!0}}function k(a){return a.charCodeAt(0)}function n(a,b){var d=a.index,e=b.index,a=a.criteria,b=b.criteria;
if(a!==b){if(a>b||"undefined"==typeof a)return 1;if(a<b||"undefined"==typeof b)return-1}return d<e?-1:1}function g(b){var d=-1,e=b.length,c=m();c["false"]=c["null"]=c["true"]=c.undefined=!1;var g=m();g.array=b;g.cache=c;for(g.push=a;++d<e;)g.push(b[d]);return!1===c.object?(i(g),null):g}function b(a){return"\\"+z[a]}function d(){return A.pop()||[]}function m(){return o.pop()||{array:null,cache:null,criteria:null,"false":!1,index:0,leading:!1,maxWait:0,"null":!1,number:null,object:null,push:null,string:null,
trailing:!1,"true":!1,undefined:!1,value:null}}function e(a){a.length=0;A.length<r&&A.push(a)}function i(a){var b=a.cache;b&&i(b);a.array=a.cache=a.criteria=a.object=a.number=a.string=a.value=null;o.length<r&&o.push(a)}function l(a,b,d){b||(b=0);"undefined"==typeof d&&(d=a?a.length:0);for(var e=-1,d=d-b||0,c=Array(0>d?0:d);++e<d;)c[e]=a[b+e];return c}function q(a){function j(a){return a&&"object"==typeof a&&!R(a)&&J.call(a,"__wrapped__")?a:new o(a)}function o(a){this.__wrapped__=a}function r(a,b,
d,e){function c(){var e=arguments,ab=g?this:b;i||(a=b[h]);d.length&&(e=e.length?(e=I.call(e),f?e.concat(d):d.concat(e)):d);return this instanceof c?(ab=H(a.prototype)?bb(a.prototype):{},e=a.apply(ab,e),H(e)?e:ab):a.apply(ab,e)}var i=Z(a),g=!d,h=b;if(g)var f=e,d=b;else if(!i){if(!e)throw new Hb;b=a}return c}function A(a){return Cb[a]}function z(){var a=(a=j.indexOf)===Ya?f:a;return a}function V(a){return function(b,d,e,c){"boolean"!=typeof d&&null!=d&&(c=e,e=!(c&&c[d]===b)?d:x,d=!1);null!=e&&(e=j.createCallback(e,
c));return a(b,d,e,c)}}function Y(a){var b,d;if(!(a&&N.call(a)==L)||(b=a.constructor,Z(b)&&!(b instanceof b)))return!1;ta(a,function(a,b){d=b});return d===x||J.call(a,d)}function ja(a){return Ib[a]}function za(a,b,c,i,g,h){var f=a;"boolean"!=typeof b&&null!=b&&(i=c,c=b,b=!1);if("function"==typeof c){c="undefined"==typeof i?c:j.createCallback(c,i,1);f=c(f);if("undefined"!=typeof f)return f;f=a}if(i=H(f)){var k=N.call(f);if(!y[k])return f;var m=R(f)}if(!i||!b)return i?m?l(f):nb({},f):f;i=ea[k];switch(k){case ba:case ia:return new i(+f);
case P:case T:return new i(f);case fa:return i(f.source,Oa.exec(f))}k=!g;g||(g=d());h||(h=d());for(var n=g.length;n--;)if(g[n]==a)return h[n];f=m?i(f.length):{};if(m){if(J.call(a,"index"))f.index=a.index;if(J.call(a,"input"))f.input=a.input}g.push(a);h.push(f);(m?w:E)(a,function(a,d){f[d]=za(a,b,c,x,g,h)});k&&(e(g),e(h));return f}function Q(a){var b=[];ta(a,function(a,d){Z(a)&&b.push(d)});return b.sort()}function Ua(a){for(var b=-1,d=S(a),e=d.length,c={};++b<e;){var i=d[b];c[a[i]]=i}return c}function la(a,
b,c,i,g,h){var f=c===p;if("function"==typeof c&&!f){var c=j.createCallback(c,i,2),k=c(a,b);if("undefined"!=typeof k)return!!k}if(a===b)return 0!==a||1/a==1/b;var m=typeof a,l=typeof b;if(a===a&&(!a||"function"!=m&&"object"!=m)&&(!b||"function"!=l&&"object"!=l))return!1;if(null==a||null==b)return a===b;l=N.call(a);m=N.call(b);l==U&&(l=L);m==U&&(m=L);if(l!=m)return!1;switch(l){case ba:case ia:return+a==+b;case P:return a!=+a?b!=+b:0==a?1/a==1/b:a==+b;case fa:case T:return a==ca(b)}m=l==oa;if(!m){if(J.call(a,
"__wrapped__ ")||J.call(b,"__wrapped__"))return la(a.__wrapped__||a,b.__wrapped__||b,c,i,g,h);if(l!=L)return!1;var l=a.constructor,n=b.constructor;if(l!=n&&(!Z(l)||!(l instanceof l&&Z(n)&&n instanceof n)))return!1}n=!g;g||(g=d());h||(h=d());for(l=g.length;l--;)if(g[l]==a)return h[l]==b;var o=0,k=!0;g.push(a);h.push(b);if(m){l=a.length;o=b.length;k=o==a.length;if(!k&&!f)return k;for(;o--;)if(m=l,n=b[o],f)for(;m--&&!(k=la(a[m],n,c,i,g,h)););else if(!(k=la(a[o],n,c,i,g,h)))break;return k}ta(b,function(b,
d,e){if(J.call(e,d))return o++,k=J.call(a,d)&&la(a[d],b,c,i,g,h)});k&&!f&&ta(a,function(a,b,d){if(J.call(d,b))return k=-1<--o});n&&(e(g),e(h));return k}function Z(a){return"function"==typeof a}function H(a){return!(!a||!B[typeof a])}function Aa(a){return"number"==typeof a||N.call(a)==P}function da(a){return"string"==typeof a||N.call(a)==T}function Va(a,b,c){var i=arguments,g=0,h=2;if(!H(a))return a;if(c===p)var f=i[3],k=i[4],l=i[5];else{var m=!0,k=d(),l=d();if("number"!=typeof c)h=i.length;3<h&&"function"==
typeof i[h-2]?f=j.createCallback(i[--h-1],i[h--],2):2<h&&"function"==typeof i[h-1]&&(f=i[--h])}for(;++g<h;)(R(i[g])?w:E)(i[g],function(b,d){var e,c,i=b,D=a[d];if(b&&((c=R(b))||ob(b))){for(i=k.length;i--;)if(e=k[i]==b){D=l[i];break}if(!e){var g;if(f&&(i=f(D,b),g="undefined"!=typeof i))D=i;g||(D=c?R(D)?D:[]:ob(D)?D:{});k.push(b);l.push(D);g||(D=Va(D,b,p,f,k,l))}}else f&&(i=f(D,b),"undefined"==typeof i&&(i=b)),"undefined"!=typeof i&&(D=i);a[d]=D});m&&(e(k),e(l));return a}function qa(a){for(var b=-1,
d=S(a),e=d.length,c=K(e);++b<e;)c[b]=a[d[b]];return c}function Wa(a,b,d){var e=-1,c=z(),i=a?a.length:0,g=!1,d=(0>d?$(0,i+d):d)||0;i&&"number"==typeof i?g=-1<(da(a)?a.indexOf(b,d):c(a,b,d)):E(a,function(a){if(++e>=d)return!(g=a===b)});return g}function xa(a,b,d){var e=!0,b=j.createCallback(b,d),d=-1,c=a?a.length:0;if("number"==typeof c)for(;++d<c&&(e=!!b(a[d],d,a)););else E(a,function(a,d,c){return e=!!b(a,d,c)});return e}function X(a,b,d){var e=[],b=j.createCallback(b,d),d=-1,c=a?a.length:0;if("number"==
typeof c)for(;++d<c;){var i=a[d];b(i,d,a)&&e.push(i)}else E(a,function(a,d,c){b(a,d,c)&&e.push(a)});return e}function pa(a,b,d){var b=j.createCallback(b,d),d=-1,e=a?a.length:0;if("number"==typeof e)for(;++d<e;){var c=a[d];if(b(c,d,a))return c}else{var i;E(a,function(a,d,e){if(b(a,d,e))return i=a,!1});return i}}function w(a,b,d){var e=-1,c=a?a.length:0,b=b&&"undefined"==typeof d?b:j.createCallback(b,d);if("number"==typeof c)for(;++e<c&&!(!1===b(a[e],e,a)););else E(a,b);return a}function ya(a,b,d){var e=
-1,c=a?a.length:0,b=j.createCallback(b,d);if("number"==typeof c)for(var i=K(c);++e<c;)i[e]=b(a[e],e,a);else i=[],E(a,function(a,d,c){i[++e]=b(a,d,c)});return i}function Ma(a,b,d){var e=-Infinity,c=e;if(!b&&R(a))for(var d=-1,i=a.length;++d<i;){var g=a[d];g>c&&(c=g)}else b=!b&&da(a)?k:j.createCallback(b,d),w(a,function(a,d,i){d=b(a,d,i);d>e&&(e=d,c=a)});return c}function ma(a,b){var d=-1,e=a?a.length:0;if("number"==typeof e)for(var c=K(e);++d<e;)c[d]=a[d][b];return c||ya(a,b)}function ra(a,b,d,e){if(!a)return d;
var c=3>arguments.length,b=j.createCallback(b,e,4),i=-1,g=a.length;if("number"==typeof g)for(c&&(d=a[++i]);++i<g;)d=b(d,a[i],i,a);else E(a,function(a,e,i){d=c?(c=!1,a):b(d,a,e,i)});return d}function Ba(a,b,d,e){var c=a?a.length:0,i=3>arguments.length;if("number"!=typeof c)var g=S(a),c=g.length;b=j.createCallback(b,e,4);w(a,function(e,h,f){h=g?g[--c]:--c;d=i?(i=!1,a[h]):b(d,a[h],h,f)});return d}function Xa(a,b,d){var e,b=j.createCallback(b,d),d=-1,c=a?a.length:0;if("number"==typeof c)for(;++d<c&&!(e=
b(a[d],d,a)););else E(a,function(a,d,c){return!(e=b(a,d,c))});return!!e}function Ja(a){var b=-1,d=z(),e=a?a.length:0,c=Ea.apply(M,I.call(arguments,1)),k=[],l=e>=s&&d===f;if(l){var m=g(c);m?(d=h,c=m):l=!1}for(;++b<e;)m=a[b],0>d(c,m)&&k.push(m);l&&i(c);return k}function sa(a,b,d){if(a){var e=0,c=a.length;if("number"!=typeof b&&null!=b)for(var i=-1,b=j.createCallback(b,d);++i<c&&b(a[i],i,a);)e++;else if(e=b,null==e||d)return a[0];return l(a,0,cb($(0,e),c))}}function Ya(a,b,d){if("number"==typeof d)var e=
a?a.length:0,d=0>d?$(0,e+d):d||0;else if(d)return d=Ta(a,b),a[d]===b?d:-1;return a?f(a,b,d):-1}function Ka(a,b,d){if("number"!=typeof b&&null!=b)for(var e=0,c=-1,i=a?a.length:0,b=j.createCallback(b,d);++c<i&&b(a[c],c,a);)e++;else e=null==b||d?1:$(0,b);return l(a,e)}function Ta(a,b,d,e){for(var c=0,i=a?a.length:c,d=d?j.createCallback(d,e,1):ib,b=d(b);c<i;)e=c+i>>>1,d(a[e])<b?c=e+1:i=e;return c}function Ca(a){for(var b=-1,d=a?Ma(ma(a,"length")):0,e=K(0>d?0:d);++b<d;)e[b]=ma(a,b);return e}function Za(a,
b){for(var d=-1,e=a?a.length:0,c={};++d<e;){var i=a[d];b?c[i]=b[d]:c[i[0]]=i[1]}return c}function Da(a,b){return Db.fastBind||na&&2<arguments.length?na.call.apply(na,arguments):r(a,b,I.call(arguments,2))}function $a(a,b,d){function e(){db(j);db(n);k=0;j=n=null}function c(){var b=o&&(!q||1<k);e();b&&(!1!==m&&(l=new Sa),h=a.apply(f,g))}function i(){e();if(o||m!==b)l=new Sa,h=a.apply(f,g)}var g,h,f,k=0,l=0,m=!1,j=null,n=null,o=!0,b=$(0,b||0);if(!0===d)var q=!0,o=!1;else if(H(d))q=d.leading,m="maxWait"in
d&&$(b,d.maxWait||0),o="trailing"in d?d.trailing:o;return function(){g=arguments;f=this;k++;db(n);if(!1===m)q&&2>k&&(h=a.apply(f,g));else{var d=new Sa;!j&&!q&&(l=d);var e=m-(d-l);0>=e?(db(j),j=null,l=d,h=a.apply(f,g)):j||(j=eb(i,e))}b!==m&&(n=eb(c,b));return h}}function ub(a){var b=I.call(arguments,1);return eb(function(){a.apply(x,b)},1)}function ib(a){return a}function vb(a){w(Q(a),function(b){var d=j[b]=a[b];j.prototype[b]=function(){var a=this.__wrapped__,b=[a];fb.apply(b,arguments);b=d.apply(j,
b);return a&&"object"==typeof a&&a===b?this:new o(b)}})}function wb(){return this.__wrapped__}var a=a?O.defaults(c.Object(),a,O.pick(c,ha)):c,K=a.Array,jb=a.Boolean,Sa=a.Date,kb=a.Function,W=a.Math,Gb=a.Number,La=a.Object,mb=a.RegExp,ca=a.String,Hb=a.TypeError,M=[],pb=La.prototype,Jb=a._,Fa=mb("^"+ca(pb.valueOf).replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/valueOf|for [^\]]+/g,".+?")+"$"),Kb=W.ceil,db=a.clearTimeout,Ea=M.concat,Eb=W.floor,Lb=kb.prototype.toString,Na=Fa.test(Na=La.getPrototypeOf)&&
Na,J=pb.hasOwnProperty,fb=M.push,gb=a.setImmediate,eb=a.setTimeout,N=pb.toString,na=Fa.test(na=N.bind)&&na,bb=Fa.test(bb=La.create)&&bb,qb=Fa.test(qb=K.isArray)&&qb,Mb=a.isFinite,Nb=a.isNaN,hb=Fa.test(hb=La.keys)&&hb,$=W.max,cb=W.min,rb=a.parseInt,Fb=W.random,I=M.slice,W=Fa.test(a.attachEvent),W=na&&!/\n|true/.test(na+W),ea={};ea[oa]=K;ea[ba]=jb;ea[ia]=Sa;ea[Ia]=kb;ea[L]=La;ea[P]=Gb;ea[fa]=mb;ea[T]=ca;o.prototype=j.prototype;var Db=j.support={};Db.fastBind=na&&!W;j.templateSettings={escape:/<%-([\s\S]+?)%>/g,
evaluate:/<%([\s\S]+?)%>/g,interpolate:Pa,variable:"",imports:{_:j}};var R=qb,S=!hb?function(a){var b,d=[];if(!a||!B[typeof a])return d;for(b in a)J.call(a,b)&&d.push(b);return d}:function(a){return!H(a)?[]:hb(a)},Cb={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},Ib=Ua(Cb),nb=function(a,b,d){var e,c=a,i=c;if(!c)return i;var g=arguments,h=0,f="number"==typeof d?2:g.length;if(3<f&&"function"==typeof g[f-2])var k=j.createCallback(g[--f-1],g[f--],2);else 2<f&&"function"==typeof g[f-1]&&
(k=g[--f]);for(;++h<f;)if((c=g[h])&&B[typeof c])for(var l=-1,m=B[typeof c]&&S(c),n=m?m.length:0;++l<n;)e=m[l],i[e]=k?k(i[e],c[e]):c[e];return i},sb=function(a,b,d){var e,c=a,i=c;if(!c)return i;for(var g=arguments,h=0,f="number"==typeof d?2:g.length;++h<f;)if((c=g[h])&&B[typeof c])for(var k=-1,l=B[typeof c]&&S(c),m=l?l.length:0;++k<m;)e=l[k],"undefined"==typeof i[e]&&(i[e]=c[e]);return i},ta=function(a,b,d){var e;if(!a||!B[typeof a])return a;b=b&&"undefined"==typeof d?b:j.createCallback(b,d);for(e in a)if(!1===
b(a[e],e,a))break;return a},E=function(a,b,d){if(!a||!B[typeof a])return a;for(var b=b&&"undefined"==typeof d?b:j.createCallback(b,d),e=-1,c=B[typeof a]&&S(a),i=c?c.length:0;++e<i&&!(d=c[e],!1===b(a[d],d,a)););return a},ob=function(a){if(!(a&&N.call(a)==L))return!1;var b=a.valueOf,d="function"==typeof b&&(d=Na(b))&&Na(d);return d?a==d||Na(a)==d:Y(a)},jb=V(function D(a,b,d){for(var e=-1,c=a?a.length:0,i=[];++e<c;){var g=a[e];d&&(g=d(g,e,a));R(g)?fb.apply(i,b?g:D(g)):i.push(g)}return i}),tb=V(function(a,
b,c){var k=-1,l=z(),m=a?a.length:0,j=[],n=!b&&m>=s&&l===f,o=c||n?d():j;if(n){var q=g(o);q?(l=h,o=q):(n=!1,o=c?o:(e(o),j))}for(;++k<m;){var q=a[k],p=c?c(q,k,a):q;if(b?!k||o[o.length-1]!==p:0>l(o,p))(c||n)&&o.push(p),j.push(q)}n?(e(o.array),i(o)):c&&e(o);return j});W&&ka&&"function"==typeof gb&&(ub=Da(gb,a));gb=8==rb(va+"08")?rb:function(a,b){return rb(da(a)?a.replace(Qa,""):a,b||0)};j.after=function(a,b){return 1>a?b():function(){if(1>--a)return b.apply(this,arguments)}};j.assign=nb;j.at=function(a){for(var b=
-1,d=Ea.apply(M,I.call(arguments,1)),e=d.length,c=K(e);++b<e;)c[b]=a[d[b]];return c};j.bind=Da;j.bindAll=function(a){for(var b=1<arguments.length?Ea.apply(M,I.call(arguments,1)):Q(a),d=-1,e=b.length;++d<e;){var c=b[d];a[c]=Da(a[c],a)}return a};j.bindKey=function(a,b){return r(a,b,I.call(arguments,2),p)};j.compact=function(a){for(var b=-1,d=a?a.length:0,e=[];++b<d;){var c=a[b];c&&e.push(c)}return e};j.compose=function(){var a=arguments;return function(){for(var b=arguments,d=a.length;d--;)b=[a[d].apply(this,
b)];return b[0]}};j.countBy=function(a,b,d){var e={},b=j.createCallback(b,d);w(a,function(a,d,c){d=ca(b(a,d,c));J.call(e,d)?e[d]++:e[d]=1});return e};j.createCallback=function(a,b,d){if(null==a)return ib;var e=typeof a;if("function"!=e){if("object"!=e)return function(b){return b[a]};var c=S(a);return function(b){for(var d=c.length,e=!1;d--&&(e=la(b[c[d]],a[c[d]],p)););return e}}return"undefined"==typeof b||ga&&!ga.test(Lb.call(a))?a:1===d?function(d){return a.call(b,d)}:2===d?function(d,e){return a.call(b,
d,e)}:4===d?function(d,e,c,i){return a.call(b,d,e,c,i)}:function(d,e,c){return a.call(b,d,e,c)}};j.debounce=$a;j.defaults=sb;j.defer=ub;j.delay=function(a,b){var d=I.call(arguments,2);return eb(function(){a.apply(x,d)},b)};j.difference=Ja;j.filter=X;j.flatten=jb;j.forEach=w;j.forIn=ta;j.forOwn=E;j.functions=Q;j.groupBy=function(a,b,d){var e={},b=j.createCallback(b,d);w(a,function(a,d,c){d=ca(b(a,d,c));(J.call(e,d)?e[d]:e[d]=[]).push(a)});return e};j.initial=function(a,b,d){if(!a)return[];var e=0,
c=a.length;if("number"!=typeof b&&null!=b)for(var i=c,b=j.createCallback(b,d);i--&&b(a[i],i,a);)e++;else e=null==b||d?1:b||e;return l(a,0,cb($(0,c-e),c))};j.intersection=function(a){for(var b=arguments,c=b.length,k=-1,l=d(),m=-1,j=z(),n=a?a.length:0,o=[],q=d();++k<c;){var p=b[k];l[k]=j===f&&(p?p.length:0)>=s&&g(k?b[k]:q)}a:for(;++m<n;){var t=l[0],p=a[m];if(0>(t?h(t,p):j(q,p))){k=c;for((t||q).push(p);--k;)if(t=l[k],0>(t?h(t,p):j(b[k],p)))continue a;o.push(p)}}for(;c--;)(t=l[c])&&i(t);e(l);e(q);return o};
j.invert=Ua;j.invoke=function(a,b){var d=I.call(arguments,2),e=-1,c="function"==typeof b,i=a?a.length:0,g=K("number"==typeof i?i:0);w(a,function(a){g[++e]=(c?b:a[b]).apply(a,d)});return g};j.keys=S;j.map=ya;j.max=Ma;j.memoize=function(a,b){function d(){var e=d.cache,c=Ga+(b?b.apply(this,arguments):arguments[0]);return J.call(e,c)?e[c]:e[c]=a.apply(this,arguments)}d.cache={};return d};j.merge=Va;j.min=function(a,b,d){var e=Infinity,c=e;if(!b&&R(a))for(var d=-1,i=a.length;++d<i;){var g=a[d];g<c&&(c=
g)}else b=!b&&da(a)?k:j.createCallback(b,d),w(a,function(a,d,i){d=b(a,d,i);d<e&&(e=d,c=a)});return c};j.omit=function(a,b,d){var e=z(),c="function"==typeof b,i={};if(c)b=j.createCallback(b,d);else var g=Ea.apply(M,I.call(arguments,1));ta(a,function(a,d,h){if(c?!b(a,d,h):0>e(g,d))i[d]=a});return i};j.once=function(a){var b,d;return function(){if(b)return d;b=!0;d=a.apply(this,arguments);a=null;return d}};j.pairs=function(a){for(var b=-1,d=S(a),e=d.length,c=K(e);++b<e;){var i=d[b];c[b]=[i,a[i]]}return c};
j.partial=function(a){return r(a,I.call(arguments,1))};j.partialRight=function(a){return r(a,I.call(arguments,1),null,p)};j.pick=function(a,b,d){var e={};if("function"!=typeof b)for(var c=-1,i=Ea.apply(M,I.call(arguments,1)),g=H(a)?i.length:0;++c<g;){var h=i[c];h in a&&(e[h]=a[h])}else b=j.createCallback(b,d),ta(a,function(a,d,c){b(a,d,c)&&(e[d]=a)});return e};j.pluck=ma;j.range=function(a,b,d){a=+a||0;d=+d||1;null==b&&(b=a,a=0);for(var e=-1,b=$(0,Kb((b-a)/d)),c=K(b);++e<b;)c[e]=a,a+=d;return c};
j.reject=function(a,b,d){b=j.createCallback(b,d);return X(a,function(a,d,e){return!b(a,d,e)})};j.rest=Ka;j.shuffle=function(a){var b=-1,d=a?a.length:0,e=K("number"==typeof d?d:0);w(a,function(a){var d=Eb(Fb()*(++b+1));e[b]=e[d];e[d]=a});return e};j.sortBy=function(a,b,d){var e=-1,c=a?a.length:0,g=K("number"==typeof c?c:0),b=j.createCallback(b,d);w(a,function(a,d,c){var i=g[++e]=m();i.criteria=b(a,d,c);i.index=e;i.value=a});c=g.length;for(g.sort(n);c--;)a=g[c],g[c]=a.value,i(a);return g};j.tap=function(a,
b){b(a);return a};j.throttle=function(a,b,d){var e=!0,c=!0;!1===d?e=!1:H(d)&&(e="leading"in d?d.leading:e,c="trailing"in d?d.trailing:c);d=m();d.leading=e;d.maxWait=b;d.trailing=c;a=$a(a,b,d);i(d);return a};j.times=function(a,b,d){for(var a=-1<(a=+a)?a:0,e=-1,c=K(a),b=j.createCallback(b,d,1);++e<a;)c[e]=b(e);return c};j.toArray=function(a){return a&&"number"==typeof a.length?l(a):qa(a)};j.transform=function(a,b,d,e){var c=R(a),b=j.createCallback(b,e,4);null==d&&(c?d=[]:(e=a&&a.constructor,d=H(e&&
e.prototype)?bb(e&&e.prototype):{}));(c?w:E)(a,function(a,e,c){return b(d,a,e,c)});return d};j.union=function(a){R(a)||(arguments[0]=a?I.call(a):M);return tb(Ea.apply(M,arguments))};j.uniq=tb;j.unzip=Ca;j.values=qa;j.where=X;j.without=function(a){return Ja(a,I.call(arguments,1))};j.wrap=function(a,b){return function(){var d=[a];fb.apply(d,arguments);return b.apply(this,d)}};j.zip=function(a){return a?Ca(arguments):[]};j.zipObject=Za;j.collect=ya;j.drop=Ka;j.each=w;j.extend=nb;j.methods=Q;j.object=
Za;j.select=X;j.tail=Ka;j.unique=tb;vb(j);j.chain=j;j.prototype.chain=function(){return this};j.clone=za;j.cloneDeep=function(a,b,d){return za(a,!0,b,d)};j.contains=Wa;j.escape=function(a){return null==a?"":ca(a).replace(G,A)};j.every=xa;j.find=pa;j.findIndex=function(a,b,d){for(var e=-1,c=a?a.length:0,b=j.createCallback(b,d);++e<c;)if(b(a[e],e,a))return e;return-1};j.findKey=function(a,b,d){var e,b=j.createCallback(b,d);E(a,function(a,d,c){if(b(a,d,c))return e=d,!1});return e};j.has=function(a,b){return a?
J.call(a,b):!1};j.identity=ib;j.indexOf=Ya;j.isArguments=function(a){return N.call(a)==U};j.isArray=R;j.isBoolean=function(a){return!0===a||!1===a||N.call(a)==ba};j.isDate=function(a){return a?"object"==typeof a&&N.call(a)==ia:!1};j.isElement=function(a){return a?1===a.nodeType:!1};j.isEmpty=function(a){var b=!0;if(!a)return b;var d=N.call(a),e=a.length;if(d==oa||d==T||d==U||d==L&&"number"==typeof e&&Z(a.splice))return!e;E(a,function(){return b=!1});return b};j.isEqual=la;j.isFinite=function(a){return Mb(a)&&
!Nb(parseFloat(a))};j.isFunction=Z;j.isNaN=function(a){return Aa(a)&&a!=+a};j.isNull=function(a){return null===a};j.isNumber=Aa;j.isObject=H;j.isPlainObject=ob;j.isRegExp=function(a){return a?"object"==typeof a&&N.call(a)==fa:!1};j.isString=da;j.isUndefined=function(a){return"undefined"==typeof a};j.lastIndexOf=function(a,b,d){var e=a?a.length:0;for("number"==typeof d&&(e=(0>d?$(0,e+d):cb(d,e-1))+1);e--;)if(a[e]===b)return e;return-1};j.mixin=vb;j.noConflict=function(){a._=Jb;return this};j.parseInt=
gb;j.random=function(a,b){null==a&&null==b&&(b=1);a=+a||0;null==b?(b=a,a=0):b=+b||0;var d=Fb();return a%1||b%1?a+cb(d*(b-a+parseFloat("1e-"+((d+"").length-1))),b):a+Eb(d*(b-a+1))};j.reduce=ra;j.reduceRight=Ba;j.result=function(a,b){var d=a?a[b]:x;return Z(d)?a[b]():d};j.runInContext=q;j.size=function(a){var b=a?a.length:0;return"number"==typeof b?b:S(a).length};j.some=Xa;j.sortedIndex=Ta;j.template=function(a,d,e){var c=j.templateSettings;a||(a="");var e=sb({},e,c),i=sb({},e.imports,c.imports),c=
S(i),i=qa(i),g,h=0,f=e.interpolate||aa,k="__p += '",f=mb((e.escape||aa).source+"|"+f.source+"|"+(f===Pa?ua:aa).source+"|"+(e.evaluate||aa).source+"|$","g");a.replace(f,function(d,e,c,i,f,l){c||(c=i);k+=a.slice(h,l).replace(Ha,b);e&&(k+="' +\n__e("+e+") +\n'");f&&(g=!0,k+="';\n"+f+";\n__p += '");c&&(k+="' +\n((__t = ("+c+")) == null ? '' : __t) +\n'");h=l+d.length;return d});var k=k+"';\n",l=f=e.variable;l||(f="obj",k="with ("+f+") {\n"+k+"\n}\n");k=(g?k.replace(u,""):k).replace(F,"$1").replace(C,
"$1;");k="function("+f+") {\n"+(l?"":f+" || ("+f+" = {});\n")+"var __t, __p = '', __e = _.escape"+(g?", __j = Array.prototype.join;\nfunction print() { __p += __j.call(arguments, '') }\n":";\n")+k+"return __p\n}";e="\n/*\n//@ sourceURL="+(e.sourceURL||"/lodash/template/source["+wa++ +"]")+"\n*/";try{var m=kb(c,"return "+k+e).apply(x,i)}catch(n){throw n.source=k,n;}if(d)return m(d);m.source=k;return m};j.unescape=function(a){return null==a?"":ca(a).replace(v,ja)};j.uniqueId=function(a){var b=++t;return ca(null==
a?"":a)+b};j.all=xa;j.any=Xa;j.detect=pa;j.findWhere=pa;j.foldl=ra;j.foldr=Ba;j.include=Wa;j.inject=ra;E(j,function(a,b){j.prototype[b]||(j.prototype[b]=function(){var b=[this.__wrapped__];fb.apply(b,arguments);return a.apply(j,b)})});j.first=sa;j.last=function(a,b,d){if(a){var e=0,c=a.length;if("number"!=typeof b&&null!=b)for(var i=c,b=j.createCallback(b,d);i--&&b(a[i],i,a);)e++;else if(e=b,null==e||d)return a[c-1];return l(a,$(0,c-e))}};j.take=sa;j.head=sa;E(j,function(a,b){j.prototype[b]||(j.prototype[b]=
function(b,d){var e=a(this.__wrapped__,b,d);return null==b||d&&"function"!=typeof b?e:new o(e)})});j.VERSION="1.3.1";j.prototype.toString=function(){return ca(this.__wrapped__)};j.prototype.value=wb;j.prototype.valueOf=wb;w(["join","pop","shift"],function(a){var b=M[a];j.prototype[a]=function(){return b.apply(this.__wrapped__,arguments)}});w(["push","reverse","sort","unshift"],function(a){var b=M[a];j.prototype[a]=function(){b.apply(this.__wrapped__,arguments);return this}});w(["concat","slice","splice"],
function(a){var b=M[a];j.prototype[a]=function(){return new o(b.apply(this.__wrapped__,arguments))}});return j}var x,A=[],o=[],t=0,p={},Ga=+new Date+"",s=75,r=40,u=/\b__p \+= '';/g,F=/\b(__p \+=) '' \+/g,C=/(__e\(.*?\)|\b__t\)) \+\n'';/g,v=/&(?:amp|lt|gt|quot|#39);/g,ua=/\$\{([^\\}]*(?:\\.[^\\}]*)*)\}/g,Oa=/\w*$/,Pa=/<%=([\s\S]+?)%>/g,ga=(ga=/\bthis\b/)&&ga.test(q)&&ga,va=" \t\u000b\u000c\u00a0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000",
Qa=RegExp("^["+va+"]*0+(?=.$)"),aa=/($^)/,G=/[&<>"']/g,Ha=/['\n\r\t\u2028\u2029\\]/g,ha="Array,Boolean,Date,Function,Math,Number,Object,RegExp,String,_,attachEvent,clearTimeout,isFinite,isNaN,parseInt,setImmediate,setTimeout".split(","),wa=0,U="[object Arguments]",oa="[object Array]",ba="[object Boolean]",ia="[object Date]",Ia="[object Function]",P="[object Number]",L="[object Object]",fa="[object RegExp]",T="[object String]",y={};y[Ia]=!1;y[U]=y[oa]=y[ba]=y[ia]=y[P]=y[L]=y[fa]=y[T]=!0;var B={"boolean":!1,
"function":!0,object:!0,number:!1,string:!1,undefined:!1},z={"\\":"\\","'":"'","\n":"n","\r":"r","\t":"t","\u2028":"u2028","\u2029":"u2029"},ja=B[typeof exports]&&exports,ka=B[typeof module]&&module&&module.exports==ja&&module,Y=B[typeof global]&&global;if(Y&&(Y.global===Y||Y.window===Y))c=Y;var O=q();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(c._=O,define(function(){return O})):ja&&!ja.nodeType?ka?(ka.exports=O)._=O:ja._=O:c._=O})(this)},"frozen/InputManager":function(){define("frozen/InputManager",
"./GameAction,./MouseAction,./TouchAction,./utils/insideCanvas,dcl,dcl/bases/Mixer,dcl/mixins/Cleanup,dojo/has,dojo/on,lodash,hammer,dojo/domReady!".split(","),function(c,f,h,a,k,n,g,b,d,m,e){return k([n,g],{keyActions:null,mouseAction:null,touchAction:null,canvas:null,handleMouse:!0,handleTouch:!0,handleKeys:!0,gameArea:null,canvasPercentage:null,emulateMouse:!0,hammer:null,on:function(a,b){var d=this.hammer,e=this.removeCleanup;d.on(a,b);var c=this.pushCleanup([a,b],function(a){d.off.apply(d,a)});
return{remove:function(){e(c);c()}}},constructor:function(){function a(b){b.remove()}m.bindAll(this);if(!this.hammer)this.hammer=e(document,{prevent_default:!0,drag_max_touches:0,hold:!1});if(!this.keyActions)this.keyActions={};this.handleKeys&&(this.pushCleanup(d(document,"keydown",this.keydown),a),this.pushCleanup(d(document,"keyup",this.keyup),a));if(this.emulateMouse){if(this.on("touch",this.mousedown),this.on("drag",this.mousemove),this.on("release",this.mouseup),!this.mouseAction)this.mouseAction=
new f}else if(this.on("touch",this.touchstart),this.on("drag",this.touchmove),this.on("release",this.touchend),!this.touchAction)this.touchAction=new h;this.gameArea&&this.canvasPercentage&&(this.pushCleanup(d(window,"resize",this.resize),a),this.pushCleanup(d(window,"orientationchange",this.resize),a))},insideCanvas:function(b){return a(b,this.canvas)},mapToKey:function(a,b){this.keyActions[b]=a},addKeyAction:function(a,b){var d=new c;if(b)d.behavior=d.statics.DETECT_INITAL_PRESS_ONLY;this.mapToKey(d,
a);return d},mouseUp:function(a){this.mouseup(a)},mouseup:function(a){this.mouseAction.release(this.normalizePoint(a.gesture.touches[0]))},mouseDown:function(a){this.mousedown(a)},mousedown:function(a){this.mouseAction.release(null);a=this.normalizePoint(a.gesture.touches[0]);this.mouseAction.insideCanvas=this.insideCanvas(a);this.mouseAction.press(a)},mouseMove:function(a){this.mousemove(a)},mousemove:function(a){this.mouseAction.position=this.normalizePoint(a.gesture?a.gesture.touches[0]:a)},touchStart:function(a){this.touchstart(a)},
touchstart:function(a){this.touchAction.release(null);a=m.map(a.gesture.touches,this.normalizePoint);this.touchAction.insideCanvas=m.some(a,this.insideCanvas);this.touchAction.press(a)},touchEnd:function(a){this.touchend(a)},touchend:function(a){this.touchAction.release(m.map(a.gesture.touches,this.normalizePoint))},touchMove:function(a){this.touchmove(a)},touchmove:function(a){this.touchAction.positions=m.map(a.gesture.touches,this.normalizePoint);this.touchAction.startPositions&&a.preventDefault()},
getKeyAction:function(a){return this.keyActions?this.keyActions[a.keyCode]||this.keyActions[String.fromCharCode(a.keyCode)]:null},keyPressed:function(a){this.keydown(a)},keyDown:function(a){this.keydown(a)},keydown:function(a){(a=this.getKeyAction(a))&&!a.isPressed()&&a.press()},keyReleased:function(a){this.keyup(a)},keyup:function(a){(a=this.getKeyAction(a))&&a.release()},getMouseLoc:function(a){return this.normalizePoint(a)},normalizePoint:function(a){var b,d;d=this.canvas.getBoundingClientRect();
b=d.left;d=d.top;return this.zoomRatio?{x:Math.round((a.clientX-b)/this.zoomRatio),y:Math.round((a.clientY-d)/this.zoomRatio)}:{x:Math.round(a.clientX-b),y:Math.round(a.clientY-d)}},resize:function(){var a,b;if(this.gameArea&&this.canvasPercentage&&this.canvas){var d=this.canvas.width,e=this.canvas.height,c=window.getComputedStyle(document.body,null)||{};a=parseFloat(c.marginLeft)||0;var g=parseFloat(c.marginTop)||0;b=parseFloat(c.marginRight)||0;c=parseFloat(c.marginBottom)||0;a+=b;b=g+c;g=window.innerWidth-
a;a=window.innerHeight-b;e=d/e;c=b="";g/a>e?(g=a*e,b=g+"px",c=a+"px"):(b=g+"px",c=Math.round(g/e)+"px");this.zoomRatio=g/d*this.canvasPercentage;this.gameArea.style.width=b;this.gameArea.style.height=c;d=Math.floor(100*this.canvasPercentage)+"%";this.canvas.style.width=d;this.canvas.style.height=d;this.canvas.style.display="block";this.canvas.style.marginLeft="auto";this.canvas.style.marginRight="auto"}}})})},"frozen/GameAction":function(){define("frozen/GameAction",["dcl","dcl/bases/Mixer"],function(c,
f){return c(f,{name:null,behavior:0,amount:0,state:0,statics:{NORMAL:0,DETECT_INITAL_PRESS_ONLY:1,STATE_RELEASED:0,STATE_PRESSED:1,STATE_WAITING_FOR_RELEASE:2,STATE_MOVED:3},constructor:function(){this.reset()},reset:function(){this.state=this.statics.STATE_RELEASED;this.amount=0},tap:function(){this.press();this.release()},press:function(){this.state=this.statics.STATE_PRESSED;this.behavior===this.statics.DETECT_INITAL_PRESS_ONLY&&this.pressAmt(1)},pressAmt:function(c){if(this.state!==this.statics.STATE_WAITING_FOR_RELEASE)this.amount+=
c,this.state=this.statics.STATE_WAITING_FOR_RELEASE},release:function(){this.state=this.statics.STATE_RELEASED},isPressed:function(){return this.state===this.statics.STATE_PRESSED?!0:!1},getAmount:function(){var c=this.amount;if(0!==c)if(this.state===this.statics.STATE_RELEASED)this.amount=0;else if(this.behavior===this.statics.DETECT_INITAL_PRESS_ONLY)this.state=this.statics.STATE_WAITING_FOR_RELEASE,this.amount=0;return c}})})},"frozen/MouseAction":function(){define("frozen/MouseAction",["dcl",
"./GameAction"],function(c,f){return c(f,{startPosition:null,endPosition:null,position:null,insideCanvas:null,press:c.superCall(function(c){return function(a){this.position=this.startPosition=a;c.apply(this)}}),release:c.superCall(function(c){return function(a){this.endPosition=a;c.apply(this)}})})})},"frozen/TouchAction":function(){define("frozen/TouchAction",["dcl","./GameAction"],function(c,f){return c(f,{startPositions:null,endPositions:null,positions:null,insideCanvas:null,press:c.superCall(function(c){return function(a){this.positions=
this.startPositions=a;c.apply(this)}}),release:c.superCall(function(c){return function(a){this.endPositions=a;c.apply(this)}})})})},"frozen/utils/insideCanvas":function(){define("frozen/utils/insideCanvas",function(){return function(c,f){return 0>c.x||c.x>f.width||0>c.y||c.y>f.height?!1:!0}})},"dcl/mixins/Cleanup":function(){(function(c){"undefined"!=typeof define?define(["../dcl","./Destroyable"],c):"undefined"!=typeof module?module.exports=c(require("../dcl"),require("./Destroyable")):dclMixinsCleanup=
c(dcl,dclMixinsDestroyable)})(function(c,f){return c(f,{declaredClass:"dcl/mixins/Cleanup",constructor:function(){this.__cleanupStack=[]},pushCleanup:function(c,a){var f=a?function(){a(c)}:function(){c.destroy()};this.__cleanupStack.push(f);return f},popCleanup:function(c){if(c)return this.__cleanupStack.pop();this.__cleanupStack.pop()()},removeCleanup:function(c){for(var a=this.__cleanupStack.length-1;0<=a;--a)if(this.__cleanupStack[a]===c)return this.__cleanupStack.splice(a,1),!0},cleanup:function(){for(;this.__cleanupStack.length;)this.__cleanupStack.pop()()},
destroy:function(){this.cleanup()}})})},"dcl/mixins/Destroyable":function(){(function(c){"undefined"!=typeof define?define(["../dcl"],c):"undefined"!=typeof module?module.exports=c(require("../dcl")):dclMixinsDestroyable=c(dcl)})(function(c){var f=c(null,{declaredClass:"dcl/mixins/Destroyable"});c.chainBefore(f,"destroy");return f})},"dojo/has":function(){define(["require","module"],function(c){var f=c.has||function(){};f.add("touch","ontouchstart"in document);f.add("device-width",screen.availWidth||
innerWidth);c=document.createElement("form");f.add("dom-attributes-explicit",0==c.attributes.length);f.add("dom-attributes-specified-flag",0<c.attributes.length&&40>c.attributes.length);f.clearElement=function(c){c.innerHTML="";return c};f.normalize=function(c,a){var k=c.match(/[\?:]|[^:\?]*/g),n=0,g=function(a){var d=k[n++];if(":"==d)return 0;if("?"==k[n++]){if(!a&&f(d))return g();g(!0);return g(a)}return d||0};return(c=g())&&a(c)};f.load=function(c,a,f){c?a([c],f):f()};return f})},"dojo/on":function(){define(["require",
"./_base/kernel","./has"],function(c,f,h){function a(a,d,c,i,f){if(i=d.match(/(.*):(.*)/))return d=i[2],i=i[1],g.selector(i,d).call(f,a,c);h("touch")&&(b.test(d)&&(c=A(c)),!h("event-orientationchange")&&"orientationchange"==d&&(d="resize",a=window,c=A(c)));l&&(c=l(c));if(a.addEventListener){var k=d in e,m=k?e[d]:d;a.addEventListener(m,c,k);return{remove:function(){a.removeEventListener(m,c,k)}}}d="on"+d;throw Error("Target must be an event emitter");}function k(){this.cancelable=!1}function n(){this.bubbles=
!1}c=window.ScriptEngineMajorVersion;h.add("jscript",c&&c()+ScriptEngineMinorVersion()/10);h.add("event-orientationchange",h("touch")&&!h("android"));h.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);var g=function(b,d,e,c){return"function"==typeof b.on&&"function"!=typeof d?b.on(d,e):g.parse(b,d,e,a,c,this)};g.pausable=function(a,b,d,e){var c,a=g(a,b,function(){if(!c)return d.apply(this,arguments)},e);a.pause=function(){c=
!0};a.resume=function(){c=!1};return a};g.once=function(a,b,d){var e=g(a,b,function(){e.remove();return d.apply(this,arguments)});return e};g.parse=function(a,b,d,e,c,i){if(b.call)return b.call(i,a,d);if(-1<b.indexOf(",")){for(var b=b.split(/\s*,\s*/),g=[],f=0,h;h=b[f++];)g.push(e(a,h,d,c,i));g.remove=function(){for(var a=0;a<g.length;a++)g[a].remove()};return g}return e(a,b,d,c,i)};var b=/^touch/;g.selector=function(a,b,d){return function(e,c){function i(b){for(h=h&&h.matches?h:f.query;!h.matches(b,
a,e);)if(b==e||!1===d||!(b=b.parentNode)||1!=b.nodeType)return;return b}var h="function"==typeof a?{matches:a}:this,k=b.bubble;return k?g(e,k(i),c):g(e,b,function(a){var b=i(a.target);return b&&c.call(b,a)})}};var d=[].slice,m=g.emit=function(a,b,e){var c=d.call(arguments,2),i="on"+b;if("parentNode"in a){var g=c[0]={},f;for(f in e)g[f]=e[f];g.preventDefault=k;g.stopPropagation=n;g.target=a;g.type=b;e=g}do a[i]&&a[i].apply(a,c);while(e&&e.bubbles&&(a=a.parentNode));return e&&e.cancelable&&e},e={};
if(!h("event-stopimmediatepropagation"))var i=function(){this.modified=this.immediatelyStopped=!0},l=function(a){return function(b){if(!b.immediatelyStopped)return b.stopImmediatePropagation=i,a.apply(this,arguments)}};e={focusin:"focus",focusout:"blur"};g.emit=function(a,b,d){if(a.dispatchEvent&&document.createEvent){var e=a.ownerDocument.createEvent("HTMLEvents");e.initEvent(b,!!d.bubbles,!!d.cancelable);for(var c in d)c in e||(e[c]=d[c]);return a.dispatchEvent(e)&&e}return m.apply(g,arguments)};
if(h("touch"))var q=function(){},x=window.orientation,A=function(a){return function(b){var d=b.corrected;if(!d){var e=b.type;try{delete b.type}catch(c){}b.type?(q.prototype=b,d=new q,d.preventDefault=function(){b.preventDefault()},d.stopPropagation=function(){b.stopPropagation()}):(d=b,d.type=e);b.corrected=d;if("resize"==e){if(x==window.orientation)return null;x=window.orientation;d.type="orientationchange";return a.call(this,d)}if(!("rotation"in d))d.rotation=0,d.scale=1;var e=d.changedTouches[0],
i;for(i in e)delete d[i],d[i]=e[i]}return a.call(this,d)}};return g})},"dojo/_base/kernel":function(){define(["../has","./config","require","module"],function(c,f,h,a){var k,c={},n={},g={config:f,global:this,dijit:c,dojox:n},c={dojo:["dojo",g],dijit:["dijit",c],dojox:["dojox",n]},a=h.map&&h.map[a.id.match(/[^\/]+/)[0]];for(k in a)c[k]?c[k][0]=a[k]:c[k]=[a[k],{}];for(k in c)a=c[k],a[1]._scopeName=a[0],f.noGlobals||(this[a[0]]=a[1]);g.scopeMap=c;g.baseUrl=g.config.baseUrl=h.baseUrl;g.isAsync=h.async;
g.locale=f.locale;f="$Rev$".match(/\d+/);g.version={major:1,minor:8,patch:3,flag:"",revision:f?+f[0]:NaN,toString:function(){var a=g.version;return a.major+"."+a.minor+"."+a.patch+a.flag+" ("+a.revision+")"}};Function("d","d.eval = function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(g);g.exit=function(){};g.deprecated=g.experimental=function(){};g._hasResource={};return g})},"dojo/_base/config":function(){define(["../has","require"],function(c,f){var h={},a=f.rawConfig,
k;for(k in a)h[k]=a[k];return h})},"hammer/hammer":function(){(function(c,f){function h(){if(!a.READY){a.event.determineEventTypes();for(var b in a.gestures)a.gestures.hasOwnProperty(b)&&a.detection.register(a.gestures[b]);a.event.onTouch(a.DOCUMENT,a.EVENT_MOVE,a.detection.detect);a.event.onTouch(a.DOCUMENT,a.EVENT_END,a.detection.detect);a.READY=!0}}var a=function(b,d){return new a.Instance(b,d||{})};a.defaults={stop_browser_behavior:{userSelect:"none",touchAction:"none",touchCallout:"none",contentZooming:"none",
userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};a.HAS_POINTEREVENTS=navigator.pointerEnabled||navigator.msPointerEnabled;a.HAS_TOUCHEVENTS="ontouchstart"in c;a.MOBILE_REGEX=/mobile|tablet|ip(ad|hone|od)|android/i;a.NO_MOUSEEVENTS=a.HAS_TOUCHEVENTS&&navigator.userAgent.match(a.MOBILE_REGEX);a.EVENT_TYPES={};a.DIRECTION_DOWN="down";a.DIRECTION_LEFT="left";a.DIRECTION_UP="up";a.DIRECTION_RIGHT="right";a.POINTER_MOUSE="mouse";a.POINTER_TOUCH="touch";a.POINTER_PEN="pen";a.EVENT_START="start";a.EVENT_MOVE=
"move";a.EVENT_END="end";a.DOCUMENT=document;a.plugins={};a.READY=!1;a.Instance=function(b,d){var c=this;h();this.element=b;this.enabled=!0;this.options=a.utils.extend(a.utils.extend({},a.defaults),d||{});this.options.stop_browser_behavior&&a.utils.stopDefaultBrowserBehavior(this.element,this.options.stop_browser_behavior);a.event.onTouch(b,a.EVENT_START,function(b){c.enabled&&a.detection.startDetect(c,b)});return this};a.Instance.prototype={on:function(a,d){for(var c=a.split(" "),e=0;e<c.length;e++)this.element.addEventListener(c[e],
d,!1);return this},off:function(a,d){for(var c=a.split(" "),e=0;e<c.length;e++)this.element.removeEventListener(c[e],d,!1);return this},trigger:function(b,d){var c=a.DOCUMENT.createEvent("Event");c.initEvent(b,!0,!0);c.gesture=d;var e=this.element;if(a.utils.hasParent(d.target,e))e=d.target;e.dispatchEvent(c);return this},enable:function(a){this.enabled=a;return this}};var k=null,n=!1,g=!1;a.event={bindDom:function(a,d,c){for(var d=d.split(" "),e=0;e<d.length;e++)a.addEventListener(d[e],c,!1)},onTouch:function(b,
d,c){var e=this;this.bindDom(b,a.EVENT_TYPES[d],function(i){var f=i.type.toLowerCase();if(!f.match(/mouse/)||!g){f.match(/touch/)||f.match(/pointerdown/)||f.match(/mouse/)&&1===i.which?n=!0:f.match(/mouse/)&&1!==i.which&&(n=!1);f.match(/touch|pointer/)&&(g=!0);var h=0;if(n){a.HAS_POINTEREVENTS&&d!=a.EVENT_END?h=a.PointerEvent.updatePointer(d,i):f.match(/touch/)?h=i.touches.length:g||(h=f.match(/up/)?0:1);if(0<h&&d==a.EVENT_END)d=a.EVENT_MOVE;else if(!h)d=a.EVENT_END;!h&&null!==k?i=k:k=i;c.call(a.detection,
e.collectEventData(b,d,i));a.HAS_POINTEREVENTS&&d==a.EVENT_END&&(h=a.PointerEvent.updatePointer(d,i))}h||(k=null,g=n=!1,a.PointerEvent.reset())}})},determineEventTypes:function(){var b;b=a.HAS_POINTEREVENTS?a.PointerEvent.getEvents():a.NO_MOUSEEVENTS?["touchstart","touchmove","touchend touchcancel"]:["touchstart mousedown","touchmove mousemove","touchend touchcancel mouseup"];a.EVENT_TYPES[a.EVENT_START]=b[0];a.EVENT_TYPES[a.EVENT_MOVE]=b[1];a.EVENT_TYPES[a.EVENT_END]=b[2]},getTouchList:function(b){if(a.HAS_POINTEREVENTS)return a.PointerEvent.getTouchList();
if(b.touches)return b.touches;b.indentifier=1;return[b]},collectEventData:function(b,d,c){var b=this.getTouchList(c,d),e=a.POINTER_TOUCH;if(c.type.match(/mouse/)||a.PointerEvent.matchType(a.POINTER_MOUSE,c))e=a.POINTER_MOUSE;return{center:a.utils.getCenter(b),timeStamp:(new Date).getTime(),target:c.target,touches:b,eventType:d,pointerType:e,srcEvent:c,preventDefault:function(){this.srcEvent.preventManipulation&&this.srcEvent.preventManipulation();this.srcEvent.preventDefault&&this.srcEvent.preventDefault()},
stopPropagation:function(){this.srcEvent.stopPropagation()},stopDetect:function(){return a.detection.stopDetect()}}}};a.PointerEvent={pointers:{},getTouchList:function(){var a=this,d=[];Object.keys(a.pointers).sort().forEach(function(c){d.push(a.pointers[c])});return d},updatePointer:function(b,d){b==a.EVENT_END?this.pointers={}:(d.identifier=d.pointerId,this.pointers[d.pointerId]=d);return Object.keys(this.pointers).length},matchType:function(b,d){if(!d.pointerType)return!1;var c={};c[a.POINTER_MOUSE]=
d.pointerType==d.MSPOINTER_TYPE_MOUSE||d.pointerType==a.POINTER_MOUSE;c[a.POINTER_TOUCH]=d.pointerType==d.MSPOINTER_TYPE_TOUCH||d.pointerType==a.POINTER_TOUCH;c[a.POINTER_PEN]=d.pointerType==d.MSPOINTER_TYPE_PEN||d.pointerType==a.POINTER_PEN;return c[b]},getEvents:function(){return["pointerdown MSPointerDown","pointermove MSPointerMove","pointerup pointercancel MSPointerUp MSPointerCancel"]},reset:function(){this.pointers={}}};a.utils={extend:function(a,d,c){for(var e in d)a[e]!==f&&c||(a[e]=d[e]);
return a},hasParent:function(a,d){for(;a;){if(a==d)return!0;a=a.parentNode}return!1},getCenter:function(a){for(var d=[],c=[],e=0,i=a.length;e<i;e++)d.push(a[e].pageX),c.push(a[e].pageY);return{pageX:(Math.min.apply(Math,d)+Math.max.apply(Math,d))/2,pageY:(Math.min.apply(Math,c)+Math.max.apply(Math,c))/2}},getVelocity:function(a,d,c){return{x:Math.abs(d/a)||0,y:Math.abs(c/a)||0}},getAngle:function(a,d){return 180*Math.atan2(d.pageY-a.pageY,d.pageX-a.pageX)/Math.PI},getDirection:function(b,d){var c=
Math.abs(b.pageX-d.pageX),e=Math.abs(b.pageY-d.pageY);return c>=e?0<b.pageX-d.pageX?a.DIRECTION_LEFT:a.DIRECTION_RIGHT:0<b.pageY-d.pageY?a.DIRECTION_UP:a.DIRECTION_DOWN},getDistance:function(a,d){var c=d.pageX-a.pageX,e=d.pageY-a.pageY;return Math.sqrt(c*c+e*e)},getScale:function(a,d){return 2<=a.length&&2<=d.length?this.getDistance(d[0],d[1])/this.getDistance(a[0],a[1]):1},getRotation:function(a,d){return 2<=a.length&&2<=d.length?this.getAngle(d[1],d[0])-this.getAngle(a[1],a[0]):0},isVertical:function(b){return b==
a.DIRECTION_UP||b==a.DIRECTION_DOWN},stopDefaultBrowserBehavior:function(a,d){var c,e="webkit,khtml,moz,ms,o,".split(",");if(d&&a.style){for(var i=0;i<e.length;i++)for(var g in d)d.hasOwnProperty(g)&&(c=g,e[i]&&(c=e[i]+c.substring(0,1).toUpperCase()+c.substring(1)),a.style[c]=d[g]);if("none"==d.userSelect)a.onselectstart=function(){return!1}}}};a.detection={gestures:[],current:null,previous:null,stopped:!1,startDetect:function(b,d){if(!this.current)this.stopped=!1,this.current={inst:b,startEvent:a.utils.extend({},
d),lastEvent:!1,name:""},this.detect(d)},detect:function(b){if(this.current&&!this.stopped){for(var b=this.extendEventData(b),d=this.current.inst.options,c=0,e=this.gestures.length;c<e;c++){var i=this.gestures[c];if(!this.stopped&&!1!==d[i.name]&&!1===i.handler.call(i,b,this.current.inst)){this.stopDetect();break}}if(this.current)this.current.lastEvent=b;b.eventType==a.EVENT_END&&!b.touches.length-1&&this.stopDetect();return b}},stopDetect:function(){this.previous=a.utils.extend({},this.current);
this.current=null;this.stopped=!0},extendEventData:function(b){var d=this.current.startEvent;if(d&&(b.touches.length!=d.touches.length||b.touches===d.touches)){d.touches=[];for(var c=0,e=b.touches.length;c<e;c++)d.touches.push(a.utils.extend({},b.touches[c]))}var c=b.timeStamp-d.timeStamp,e=b.center.pageX-d.center.pageX,i=b.center.pageY-d.center.pageY,g=a.utils.getVelocity(c,e,i);a.utils.extend(b,{deltaTime:c,deltaX:e,deltaY:i,velocityX:g.x,velocityY:g.y,distance:a.utils.getDistance(d.center,b.center),
angle:a.utils.getAngle(d.center,b.center),direction:a.utils.getDirection(d.center,b.center),scale:a.utils.getScale(d.touches,b.touches),rotation:a.utils.getRotation(d.touches,b.touches),startEvent:d});return b},register:function(b){var d=b.defaults||{};d[b.name]===f&&(d[b.name]=!0);a.utils.extend(a.defaults,d,!0);b.index=b.index||1E3;this.gestures.push(b);this.gestures.sort(function(a,b){return a.index<b.index?-1:a.index>b.index?1:0});return this.gestures}};a.gestures=a.gestures||{};a.gestures.Hold=
{name:"hold",index:10,defaults:{hold_timeout:500,hold_threshold:1},timer:null,handler:function(b,d){switch(b.eventType){case a.EVENT_START:clearTimeout(this.timer);a.detection.current.name=this.name;this.timer=setTimeout(function(){"hold"==a.detection.current.name&&d.trigger("hold",b)},d.options.hold_timeout);break;case a.EVENT_MOVE:b.distance>d.options.hold_threshold&&clearTimeout(this.timer);break;case a.EVENT_END:clearTimeout(this.timer)}}};a.gestures.Tap={name:"tap",index:100,defaults:{tap_max_touchtime:250,
tap_max_distance:10,tap_always:!0,doubletap_distance:20,doubletap_interval:300},handler:function(b,d){if(b.eventType==a.EVENT_END){var c=a.detection.previous,e=!1;if(!(b.deltaTime>d.options.tap_max_touchtime||b.distance>d.options.tap_max_distance))if(c&&"tap"==c.name&&b.timeStamp-c.lastEvent.timeStamp<d.options.doubletap_interval&&b.distance<d.options.doubletap_distance&&(d.trigger("doubletap",b),e=!0),!e||d.options.tap_always)a.detection.current.name="tap",d.trigger(a.detection.current.name,b)}}};
a.gestures.Swipe={name:"swipe",index:40,defaults:{swipe_max_touches:1,swipe_velocity:0.7},handler:function(b,d){if(b.eventType==a.EVENT_END&&!(0<d.options.swipe_max_touches&&b.touches.length>d.options.swipe_max_touches)&&(b.velocityX>d.options.swipe_velocity||b.velocityY>d.options.swipe_velocity))d.trigger(this.name,b),d.trigger(this.name+b.direction,b)}};a.gestures.Drag={name:"drag",index:50,defaults:{drag_min_distance:10,correct_for_drag_min_distance:!0,drag_max_touches:1,drag_block_horizontal:!1,
drag_block_vertical:!1,drag_lock_to_axis:!1,drag_lock_min_distance:25},triggered:!1,handler:function(b,d){if(a.detection.current.name!=this.name&&this.triggered)d.trigger(this.name+"end",b),this.triggered=!1;else if(!(0<d.options.drag_max_touches&&b.touches.length>d.options.drag_max_touches))switch(b.eventType){case a.EVENT_START:this.triggered=!1;break;case a.EVENT_MOVE:if(b.distance<d.options.drag_min_distance&&a.detection.current.name!=this.name)break;if(a.detection.current.name!=this.name&&(a.detection.current.name=
this.name,d.options.correct_for_drag_min_distance)){var c=Math.abs(d.options.drag_min_distance/b.distance);a.detection.current.startEvent.center.pageX+=b.deltaX*c;a.detection.current.startEvent.center.pageY+=b.deltaY*c;b=a.detection.extendEventData(b)}if(a.detection.current.lastEvent.drag_locked_to_axis||d.options.drag_lock_to_axis&&d.options.drag_lock_min_distance<=b.distance)b.drag_locked_to_axis=!0;c=a.detection.current.lastEvent.direction;if(b.drag_locked_to_axis&&c!==b.direction)b.direction=
a.utils.isVertical(c)?0>b.deltaY?a.DIRECTION_UP:a.DIRECTION_DOWN:0>b.deltaX?a.DIRECTION_LEFT:a.DIRECTION_RIGHT;if(!this.triggered)d.trigger(this.name+"start",b),this.triggered=!0;d.trigger(this.name,b);d.trigger(this.name+b.direction,b);(d.options.drag_block_vertical&&a.utils.isVertical(b.direction)||d.options.drag_block_horizontal&&!a.utils.isVertical(b.direction))&&b.preventDefault();break;case a.EVENT_END:this.triggered&&d.trigger(this.name+"end",b),this.triggered=!1}}};a.gestures.Transform={name:"transform",
index:45,defaults:{transform_min_scale:0.01,transform_min_rotation:1,transform_always_block:!1},triggered:!1,handler:function(b,d){if(a.detection.current.name!=this.name&&this.triggered)d.trigger(this.name+"end",b),this.triggered=!1;else if(!(2>b.touches.length))switch(d.options.transform_always_block&&b.preventDefault(),b.eventType){case a.EVENT_START:this.triggered=!1;break;case a.EVENT_MOVE:var c=Math.abs(1-b.scale),e=Math.abs(b.rotation);if(c<d.options.transform_min_scale&&e<d.options.transform_min_rotation)break;
a.detection.current.name=this.name;if(!this.triggered)d.trigger(this.name+"start",b),this.triggered=!0;d.trigger(this.name,b);e>d.options.transform_min_rotation&&d.trigger("rotate",b);c>d.options.transform_min_scale&&(d.trigger("pinch",b),d.trigger("pinch"+(1>b.scale?"in":"out"),b));break;case a.EVENT_END:this.triggered&&d.trigger(this.name+"end",b),this.triggered=!1}}};a.gestures.Touch={name:"touch",index:-Infinity,defaults:{prevent_default:!1,prevent_mouseevents:!1},handler:function(b,d){d.options.prevent_mouseevents&&
b.pointerType==a.POINTER_MOUSE?b.stopDetect():(d.options.prevent_default&&b.preventDefault(),b.eventType==a.EVENT_START&&d.trigger(this.name,b))}};a.gestures.Release={name:"release",index:Infinity,handler:function(b,d){b.eventType==a.EVENT_END&&d.trigger(this.name,b)}};"function"==typeof define&&"object"==typeof define.amd&&define.amd?(c.Hammer=a,define(function(){return a})):"object"===typeof module&&"object"===typeof module.exports?module.exports=a:c.Hammer=a})(this)},"dojo/domReady":function(){define(["./has"],
function(){function c(a){n?a(h):g.push(a)}var f=this,h=document,a={loaded:1,complete:1},k="string"!=typeof h.readyState,n=!!a[h.readyState];if(k)h.readyState="loading";if(!n){var g=[],b=[],d=function(b){b=b||f.event;if(!(n||"readystatechange"==b.type&&!a[h.readyState])){n=1;if(k)h.readyState="complete";for(;g.length;)g.shift()(h)}},m=function(a,b){a.addEventListener(b,d,!1);g.push(function(){a.removeEventListener(b,d,!1)})};m(h,"DOMContentLoaded");m(f,"load");"onreadystatechange"in h?m(h,"readystatechange"):
k||b.push(function(){return a[h.readyState]});if(b.length){var e=function(){if(!n){for(var a=b.length;a--;)if(b[a]()){d("poller");return}setTimeout(e,30)}};e()}}c.load=function(a,b,d){c(d)};return c})},"frozen/ResourceManager":function(){define("frozen/ResourceManager","require,./plugins/sound!,dcl,dcl/bases/Mixer,lodash,dojo/on".split(","),function(c,f,h,a,k,n){function g(a,b){var d=b;a&&(d=[a,b].join("/"));return d.replace(/\/{2,}/g,"/")}function b(a){var b=document.createElement("canvas");b.height=
a.height;b.width=a.width;var d=b.getContext("2d");d.translate(b.width,0);d.scale(-1,1);d.drawImage(a,0,0);return b.toDataURL()}function d(a){var b=document.createElement("canvas");b.height=a.height;b.width=a.width;var d=b.getContext("2d");d.translate(0,b.height);d.scale(1,-1);d.drawImage(a,0,0);return b.toDataURL()}var m=h(null,{name:"",img:null,complete:!1,constructor:function(a){var b=this;b.name=a;b.img=new Image;n.once(b.img,"load",function(){b.complete=!0})},load:function(){this.img.src=c.toUrl(this.name)}});
return h(a,{allLoaded:!1,imageDir:null,soundDir:null,resourceList:{},loadImage:function(a){var b=!1;if("object"!==typeof a)if("string"===typeof a)b=!0,a=[a];else return;var d=this,a=k.transform(a,function(a,b,c){b=g(d.imageDir,b);if(d.resourceList[b])return a[c]=d.resourceList[b].img;d.allLoaded=!1;var e=new m(b);e.load();d.resourceList[b]=e;a[c]=e.img});return b?a[0]:a},loadSound:function(a){var b=!1;if("object"!==typeof a)if("string"===typeof a)b=!0,a=[a];else return;var d=this,a=k.transform(a,
function(a,b,c){b=g(d.soundDir,b);if(d.resourceList[b])return a[c]=d.resourceList[b];d.allLoaded=!1;var e=new f(b);d.resourceList[b]=e;a[c]=e});return b?a[0]:a},flipImage:function(a,b,d){this.allLoaded=!1;var c=new m(a);this.resourceList[a]=c;n.once(b,"load",function(){c.img.src=d(b)});k.any(this.resourceList,function(a){if(a.img===b&&a.complete)return c.img.src=d(b),!0});return c.img},flipImageX:function(a,d){return this.flipImage(a,d,b)},flipImageY:function(a,b){return this.flipImage(a,b,d)},resourcesReady:function(){if(!this.allLoaded){for(var a in this.resourceList)if(!this.resourceList[a].complete)return!1;
this.allLoaded=!0}return!0},getPercentComplete:function(){var a=0,b=0,d;for(d in this.resourceList){var c=this.resourceList[d];b++;c.complete&&(a+=1)}return 0===b?0:Math.round(100*(a/b))}})})},"frozen/plugins/sound":function(){define(["../sounds/Sound","../sounds/WebAudio","../sounds/HTML5Audio","dojo/has"],function(c,f,h,a){return{load:function(k,n,g){return a("WebAudio")?g(f):a("HTML5Audio")?g(h):g(c)}}})},"frozen/sounds/Sound":function(){define("frozen/sounds/Sound",["dcl","dojo/has","dojo/sniff"],
function(c,f){f.add("shittySound",function(){return!(!f("android")&&!f("ios")||!f("webkit"))});return c(null,{declaredClass:"frozen/sounds/Sound",name:null,complete:!1,formats:{"audio/mpeg":".mp3","audio/webm":".webm","audio/ogg":".ogg","audio/wav":".wav","audio/aac":".aac","audio/x-m4a":".m4a"},probably:null,maybe:null,constructor:function(c){if(!this.probably)this.probably=[];if(!this.maybe)this.maybe=[];"string"===typeof c&&this.load(c)},load:function(c){this.name=c;this.complete=!0},loop:function(){},
play:function(){},_initAudio:function(){},_chooseFormat:function(){if(!this.probably.length&&!this.maybe.length){var c=new Audio,a,f;for(a in this.formats)f=c.canPlayType(a),"probably"===f?this.probably.push(this.formats[a]):"maybe"===f&&this.maybe.push(this.formats[a])}return this.probably.length?this.probably[0]:this.maybe.length?this.maybe[0]:""},_nextFormat:function(){if(1<this.probably.length)return this.probably.shift(),this.probably[0];if(1===this.probably.length&&(this.probably.length=0,this.maybe.length))return this.maybe[0];
if(1<this.maybe.length)return this.maybe.shift(),this.maybe[0];if(1===this.maybe.length)this.maybe.length=0;return""}})})},"dojo/sniff":function(){define(["./has"],function(c){var f=navigator,h=f.userAgent,f=f.appVersion,a=parseFloat(f);c.add("air",0<=h.indexOf("AdobeAIR"));c.add("khtml",0<=f.indexOf("Konqueror")?a:void 0);c.add("webkit",parseFloat(h.split("WebKit/")[1])||void 0);c.add("chrome",parseFloat(h.split("Chrome/")[1])||void 0);c.add("safari",0<=f.indexOf("Safari")&&!c("chrome")?parseFloat(f.split("Version/")[1]):
void 0);c.add("mac",0<=f.indexOf("Macintosh"));c.add("quirks","BackCompat"==document.compatMode);c.add("ios",/iPhone|iPod|iPad/.test(h));c.add("android",parseFloat(h.split("Android ")[1])||void 0);if(!c("webkit")){0<=h.indexOf("Opera")&&c.add("opera",9.8<=a?parseFloat(h.split("Version/")[1])||a:a);0<=h.indexOf("Gecko")&&!c("khtml")&&!c("webkit")&&c.add("mozilla",a);c("mozilla")&&c.add("ff",parseFloat(h.split("Firefox/")[1]||h.split("Minefield/")[1])||void 0);if(document.all&&!c("opera"))h=parseFloat(f.split("MSIE ")[1])||
void 0,(f=document.documentMode)&&5!=f&&Math.floor(h)!=f&&(h=f),c.add("ie",h);c.add("wii","undefined"!=typeof opera&&opera.wiiremote)}return c})},"frozen/sounds/WebAudio":function(){define("frozen/sounds/WebAudio","require,./Sound,../utils/removeExtension,dcl,dojo/on,dojo/has,../shims/AudioContext".split(","),function(c,f,h,a,k,n){n.add("WebAudio",function(a){return!!a.AudioContext});var g=null;n("WebAudio")&&(g=new window.AudioContext);if(n("shittySound"))k.once(document,"touchstart",function(){var a=
g.createBufferSource();a.buffer=g.createBuffer(1,1,22050);a.connect(g.destination);a.noteOn(0)});return a(f,{declaredClass:"frozen/sounds/WebAudio",audioContext:g,buffer:null,load:function(a){var d=this;this.name=a;var g=h(a);g===a&&(a=g+this._chooseFormat());a=c.toUrl(a);g=new XMLHttpRequest;g.open("GET",a,!0);g.responseType="arraybuffer";k.once(g,"load",function(a){d.audioContext.decodeAudioData(a.target.response,function(a){d.buffer=a;d.complete=!0},function(){d._nextFormat()?d.load(d.name):d.complete=
!0})});g.send()},loop:function(a){this.buffer&&this._initAudio(a,!0).noteOn(0)},play:function(a,d){this.buffer&&this._initAudio(a,!1).noteOn(d||0)},_initAudio:function(a,d){var d="boolean"===typeof d?d:!1,c=this.audioContext.createBufferSource();c.buffer=this.buffer;c.loop=d;if(a){var e=this.audioContext.createGainNode();e.gain.value=a;c.connect(e);e.connect(this.audioContext.destination)}else c.connect(this.audioContext.destination);return c}})})},"frozen/utils/removeExtension":function(){define("frozen/utils/removeExtension",
function(){return function(c){return c.replace(/(.*)\.[^.]{1,4}$/,"")}})},"frozen/shims/AudioContext":function(){define("frozen/shims/AudioContext",function(){for(var c=["ms","moz","webkit","o"],f=0;f<c.length&&!window.AudioContext;++f)window.AudioContext=window[c[f]+"AudioContext"]})},"frozen/sounds/HTML5Audio":function(){define("frozen/sounds/HTML5Audio","require,./Sound,../utils/removeExtension,dcl,dojo/on,dojo/has".split(","),function(c,f,h,a,k,n){n.add("HTML5Audio",function(a){return!!a.Audio});
return a(f,{declaredClass:"frozen/sounds/HTML5Audio",audio:null,load:function(a){this.audio=new Audio;var b=this;this.name=a;var d=h(a);d===a&&(a=d+this._chooseFormat());a=c.toUrl(a);if(n("shittySound"))k.once(document,"touchstart",function(){var a=b.audio.volume;b.audio.volume=0;b.audio.play();b.audio.pause();b.audio.volume=a}),this._updateCurrentTime=null,k.once(this.audio,"progress",function(){null!==b._updateCurrentTime&&b._updateCurrentTime()});this.audio.pause();this.audio.preload="auto";k.once(this.audio,
"error",function(){b._nextFormat()?b.load(b.name):(b.audio.src=null,b.complete=!0)});k.once(this.audio,"loadeddata",function(){b.complete=!0});this.audio.src=a},loop:function(a){var b=this._initAudio(a,!0);k.once(b,"loadeddata",function(){b.play()})},play:function(a,b){b=b||0;if(n("shittySound"))try{return this.audio.currentTime=b/1E3,this.audio.play()}catch(d){return this._updateCurrentTime=function(){this._updateCurrentTime=null;this.audio.currentTime=b/1E3;return this.audio.play()},this.audio.play()}var c=
this._initAudio(a,!1);k.once(c,"loadeddata",function(){c.currentTime=b/1E3;c.play()})},_initAudio:function(a,b){var b="boolean"===typeof b?b:!1,d=new Audio;d.pause();d.volume=a||1;d.loop=b;d.preload="auto";d.mozLoadFrom?d.mozLoadFrom(this.audio):d.src=this.audio.currentSrc;return d}})})},"frozen/shims/RAF":function(){define("frozen/shims/RAF",function(){for(var c=0,f=["ms","moz","webkit","o"],h=0;h<f.length&&!window.requestAnimationFrame;++h)window.requestAnimationFrame=window[f[h]+"RequestAnimationFrame"],
window.cancelAnimationFrame=window[f[h]+"CancelAnimationFrame"]||window[f[h]+"CancelRequestAnimationFrame"];if(!window.requestAnimationFrame)window.requestAnimationFrame=function(a){var f=(new Date).getTime(),h=Math.max(0,16-(f-c)),g=window.setTimeout(function(){a(f+h)},h);c=f+h;return g};if(!window.cancelAnimationFrame)window.cancelAnimationFrame=function(a){clearTimeout(a)}})},"frozen/box2d/Box":function(){define("frozen/box2d/Box",["dcl","dcl/bases/Mixer","./listeners/Contact"],function(c,f,h){var a=
Box2D.Common.Math.b2Vec2,k=Box2D.Dynamics.b2BodyDef,n=Box2D.Dynamics.b2Body,g=Box2D.Dynamics.b2FixtureDef,b=Box2D.Dynamics.b2World,d=Box2D.Collision.Shapes.b2PolygonShape,m=Box2D.Collision.Shapes.b2CircleShape;return c(f,{intervalRate:60,adaptive:!1,bodiesMap:null,fixturesMap:null,jointsMap:null,b2World:null,gravityX:0,gravityY:9.8,allowSleep:!0,resolveCollisions:!1,contactListener:null,collisions:null,scale:30,constructor:function(d){if(d&&d.intervalRate)this.intervalRate=parseInt(d.intervalRate,
10);this.bodiesMap={};this.fixturesMap={};this.jointsMap={};this.b2World=new b(new a(this.gravityX,this.gravityY),this.allowSleep);if(this.resolveCollisions)this.contactListener=new h;this.contactListener&&this.addContactListener(this.contactListener)},update:function(a){this.contactListener&&this.contactListener.reset&&this.contactListener.reset();var b=Date.now();a?this.b2World.Step(a/1E3,10,10):this.b2World.Step(this.adaptive?(b-this.lastTimestamp)/1E3:1/this.intervalRate,10,10);this.b2World.ClearForces();
return Date.now()-b},getState:function(){for(var a={},b=this.b2World.GetBodyList();b;b=b.m_next)if(b.IsActive()&&"undefined"!==typeof b.GetUserData()&&null!==b.GetUserData()&&(a[b.GetUserData()]={x:b.GetPosition().x,y:b.GetPosition().y,angle:b.GetAngle(),center:{x:b.GetWorldCenter().x,y:b.GetWorldCenter().y},linearVelocity:b.m_linearVelocity,angularVelocity:b.m_angularVelocity},this.contactListener&&this.contactListener.collisions))a[b.GetUserData()].collisions=this.contactListener.collisions[b.GetUserData()]||
null;return a},updateExternalState:function(a){var b=this.getState(),d;for(d in b){var c=a[d];c&&!c.staticBody&&c.update(b[d])}},setBodies:function(a){for(var b in a)this.addBody(a[b]);this.ready=!0},addBody:function(b){if(!b.alreadyScaled)b.scaleShape(1/this.scale),b.scale=this.scale;var c=new k,f=new g,h,x,A,o;f.restitution=b.restitution;f.density=b.density;f.friction=b.friction;if(null!=b.maskBits)f.filter.maskBits=b.maskBits;if(null!=b.categoryBits)f.filter.categoryBits=b.categoryBits;if(null!=
b.groupIndex)f.filter.groupIndex=b.groupIndex;c.type=b.staticBody?n.b2_staticBody:n.b2_dynamicBody;c.position.x=b.x;c.position.y=b.y;c.userData=b.id;c.angle=b.angle;c.linearDamping=b.linearDamping;c.angularDamping=b.angularDamping;var t=this.b2World.CreateBody(c);if(b.radius)f.shape=new m(b.radius),t.CreateFixture(f);else if(b.points){x=[];for(c=0;c<b.points.length;c++)A=new a,A.Set(b.points[c].x,b.points[c].y),x[c]=A;f.shape=new d;f.shape.SetAsArray(x,x.length);t.CreateFixture(f)}else if(b.polys)for(h=
0;h<b.polys.length;h++){x=b.polys[h];o=[];for(c=0;c<x.length;c++)A=new a,A.Set(x[c].x,x[c].y),o[c]=A;f.shape=new d;f.shape.SetAsArray(o,o.length);t.CreateFixture(f)}else f.shape=new d,f.shape.SetAsBox(b.halfWidth,b.halfHeight),t.CreateFixture(f);this.bodiesMap[b.id]=t},setPosition:function(b,d,c){this.bodiesMap[b].SetPosition(new a(d,c))},setAngle:function(a,b){this.bodiesMap[a].SetAngle(b)},setLinearVelocity:function(b,d,c){this.bodiesMap[b].SetLinearVelocity(new a(d,c))},setAngularVelocity:function(a,
b){this.bodiesMap[a].SetAngularVelocity(b)},applyImpulseDegrees:function(b,d,c){b=this.bodiesMap[b];b.ApplyImpulse(new a(Math.sin(d*(Math.PI/180))*c,-1*Math.cos(d*(Math.PI/180))*c),b.GetWorldCenter())},applyForceDegrees:function(b,d,c){b=this.bodiesMap[b];b.ApplyForce(new a(Math.sin(d*(Math.PI/180))*c,-1*Math.cos(d*(Math.PI/180))*c),b.GetWorldCenter())},applyImpulse:function(b,d,c){b=this.bodiesMap[b];b.ApplyImpulse(new a(Math.sin(d)*c,-1*Math.cos(d)*c),b.GetWorldCenter())},applyForce:function(b,
d,c){b=this.bodiesMap[b];b.ApplyForce(new a(Math.sin(d)*c,-1*Math.cos(d)*c),b.GetWorldCenter())},applyTorque:function(a,b){this.bodiesMap[a].ApplyTorque(b)},setGravity:function(b){this.b2World.SetGravity(new a(b.x,b.y))},removeBody:function(a){this.bodiesMap[a]&&(this.fixturesMap[a]&&this.bodiesMap[a].DestroyFixture(this.fixturesMap[a]),this.b2World.DestroyBody(this.bodiesMap[a]),delete this.bodiesMap[a])},wakeUpBody:function(a){this.bodiesMap[a]&&this.bodiesMap[a].SetAwake(!0)},addContactListener:function(a){var b=
new Box2D.Dynamics.b2ContactListener;if(a.beginContact)b.BeginContact=function(b){a.beginContact(b.m_fixtureA.m_body.m_userData,b.m_fixtureB.m_body.m_userData,b)};if(a.endContact)b.EndContact=function(b){a.endContact(b.m_fixtureA.m_body.m_userData,b.m_fixtureB.m_body.m_userData,b)};if(a.preSolve)b.PreSolve=function(b,d){a.preSolve(b.m_fixtureA.m_body.m_userData,b.m_fixtureB.m_body.m_userData,d,b)};if(a.postSolve)b.PostSolve=function(b,d){a.postSolve(b.m_fixtureA.m_body.m_userData,b.m_fixtureB.m_body.m_userData,
d,b)};this.b2World.SetContactListener(b)},removeJoint:function(a){this.jointsMap[a]&&(this.b2World.DestroyJoint(this.jointsMap[a]),delete this.jointsMap[a])},addJoint:function(a){if(a&&a.id&&!this.jointsMap[a.id]){if(!a.alreadyScaled&&a.scaleJointLocation)a.scaleJointLocation(1/this.scale),a.scale=this.scale;var b=a.createB2Joint(this);b&&(this.jointsMap[a.id]=b)}}})})},"frozen/box2d/listeners/Contact":function(){define("frozen/box2d/listeners/Contact",["dcl","dcl/bases/Mixer"],function(c,f){return c(f,
{declaredClass:"frozen/box2d/listeners/Contact",constructor:function(){this.collisions=this.collisions||{}},collisions:null,reset:function(){this.collisions={}},postSolve:function(c,a,f){this.collisions[c]=this.collisions[c]||[];this.collisions[c].push({id:a,impulse:f.normalImpulses[0]});this.collisions[a]=this.collisions[a]||[];this.collisions[a].push({id:c,impulse:f.normalImpulses[0]})}})})},"frozen/box2d/entities":function(){define("frozen/box2d/entities",["./entities/Circle","./entities/MultiPolygon",
"./entities/Polygon","./entities/Rectangle"],function(){for(var c=Array.prototype.slice.call(arguments),f={},h=0;h<c.length;h++){var a=c[h],k=a.prototype.declaredClass.replace("frozen/box2d/entities/","");f[k]=a}return f})},"frozen/box2d/entities/Circle":function(){define("frozen/box2d/entities/Circle",["dcl","./Entity","../../utils/distance"],function(c,f,h){return c(f,{declaredClass:"frozen/box2d/entities/Circle",radius:1,draw:c.superCall(function(a){return function(c,f){var f=f||this.scale||1,
g=c.lineWidth;c.lineWidth=this.lineWidth;c.fillStyle=this.fillStyle;c.strokeStyle=this.strokeStyle;c.beginPath();c.arc(this.x*f,this.y*f,this.radius*f,0,2*Math.PI,!0);c.closePath();c.fill();c.stroke();this.staticBody||(c.save(),c.translate(this.x*f,this.y*f),c.rotate(this.angle),c.translate(-this.x*f,-this.y*f),c.beginPath(),c.moveTo(this.x*f,this.y*f),c.lineTo(this.x*f,this.y*f-this.radius*f),c.closePath(),c.stroke(),c.restore());c.lineWidth=g;a.apply(this,[c,f])}}),scaleShape:c.superCall(function(a){return function(c){this.radius*=
c;a.apply(this,[c])}}),pointInShape:function(a){return h(a,this)<=this.radius}})})},"frozen/box2d/entities/Entity":function(){define("frozen/box2d/entities/Entity",["dcl","dcl/bases/Mixer","lodash"],function(c,f,h){return c(f,{declaredClass:"frozen/box2d/entities/Entity",id:0,x:0,y:0,scale:null,angle:0,center:null,restitution:0.3,density:1,friction:0.9,linearDamping:0,linearVelocity:null,angularVelocity:0,angularDamping:0,staticBody:!1,fillStyle:"rgba(128,128,128,0.5)",strokeStyle:"#000",lineWidth:1,
maskBits:null,categoryBits:null,groupIndex:null,update:function(a){h.assign(this,a)},draw:function(a,c){var c=c||this.scale||1,f=a.lineWidth;a.lineWidth=this.lineWidth;a.fillStyle=this.strokeStyle;a.beginPath();a.arc(this.x*c,this.y*c,4,0,2*Math.PI,!0);a.closePath();a.fill();if(this.center)a.fillStyle="yellow",a.beginPath(),a.arc(this.center.x*c,this.center.y*c,2,0,2*Math.PI,!0),a.closePath(),a.fill();a.lineWidth=f},scaleShape:function(a){this.x*=a;this.y*=a;this.alreadyScaled=!0}})})},"frozen/utils/distance":function(){define("frozen/utils/distance",
function(){return function(c,f){return Math.sqrt((f.x-c.x)*(f.x-c.x)+(f.y-c.y)*(f.y-c.y))}})},"frozen/box2d/entities/MultiPolygon":function(){define("frozen/box2d/entities/MultiPolygon",["dcl","./Entity","../../utils/scalePoints","../../utils/pointInPolygon","../../utils/translatePoints"],function(c,f,h,a,k){return c(f,{declaredClass:"frozen/box2d/entities/MultiPolygon",polys:[],draw:c.superCall(function(a){return function(c,b){var b=b||this.scale||1,d=c.lineWidth;c.lineWidth=this.lineWidth;c.save();
c.translate(this.x*b,this.y*b);c.rotate(this.angle);c.translate(-this.x*b,-this.y*b);c.fillStyle=this.fillStyle;c.strokeStyle=this.strokeStyle;for(var f=0;f<this.polys.length;f++){c.beginPath();c.moveTo((this.x+this.polys[f][0].x)*b,(this.y+this.polys[f][0].y)*b);for(var e=1;e<this.polys[f].length;e++)c.lineTo((this.polys[f][e].x+this.x)*b,(this.polys[f][e].y+this.y)*b);c.lineTo((this.x+this.polys[f][0].x)*b,(this.y+this.polys[f][0].y)*b);c.closePath();c.fill();c.stroke()}c.restore();c.lineWidth=
d;a.apply(this,[c,b])}}),scaleShape:c.superCall(function(a){return function(c){this.polys=h(this.polys,c);a.apply(this,[c])}}),pointInShape:function(c){for(var f=0;f<this.polys.length;f++)if(a(c,k(this.polys[f],this)))return!0;return!1}})})},"frozen/utils/scalePoints":function(){define("frozen/utils/scalePoints",["lodash"],function(c){function f(h,a){return h=Array.isArray(h)?c.map(h,function(c){return f(c,a)}):"object"===typeof a?{x:h.x*a.x,y:h.y*a.y}:{x:h.x*a,y:h.y*a}}return f})},"frozen/utils/pointInPolygon":function(){define("frozen/utils/pointInPolygon",
function(){return function(c,f){if(!c||!f)return!1;for(var h=f.points||f,a=!1,k=h.length-1,n=0;n<h.length;k=n++){var g=h[n].x,b=h[n].y,d=h[k].x,k=h[k].y;b>c.y!==k>c.y&&c.x<(d-g)*(c.y-b)/(k-b)+g&&(a=!a)}return a}})},"frozen/utils/translatePoints":function(){define("frozen/utils/translatePoints",["lodash"],function(c){function f(h,a){Array.isArray(h)?h=c.map(h,function(c){return f(c,a)}):(h={x:h.x,y:h.y},null!=a.x&&(h.x+=a.x),null!=a.y&&(h.y+=a.y));return h}return f})},"frozen/box2d/entities/Polygon":function(){define("frozen/box2d/entities/Polygon",
["dcl","./Entity","../../utils/scalePoints","../../utils/pointInPolygon","../../utils/translatePoints"],function(c,f,h,a,k){return c(f,{declaredClass:"frozen/box2d/entities/Polygon",points:[],draw:c.superCall(function(a){return function(c,b){var b=b||this.scale||1,d=c.lineWidth;c.lineWidth=this.lineWidth;c.save();c.translate(this.x*b,this.y*b);c.rotate(this.angle);c.translate(-this.x*b,-this.y*b);c.fillStyle=this.fillStyle;c.strokeStyle=this.strokeStyle;c.beginPath();c.moveTo((this.x+this.points[0].x)*
b,(this.y+this.points[0].y)*b);for(var f=1;f<this.points.length;f++)c.lineTo((this.points[f].x+this.x)*b,(this.points[f].y+this.y)*b);c.lineTo((this.x+this.points[0].x)*b,(this.y+this.points[0].y)*b);c.closePath();c.fill();c.stroke();c.restore();c.lineWidth=d;a.apply(this,[c,b])}}),scaleShape:c.superCall(function(a){return function(c){this.points=h(this.points,c);a.apply(this,[c])}}),pointInShape:function(c){return a(c,k(this.points,this))}})})},"frozen/box2d/entities/Rectangle":function(){define("frozen/box2d/entities/Rectangle",
["dcl","./Entity"],function(c,f){return c(f,{declaredClass:"frozen/box2d/entities/Rectangle",halfWidth:1,halfHeight:1,draw:c.superCall(function(c){return function(a,f){var f=f||this.scale||1,n=a.lineWidth;a.lineWidth=this.lineWidth;a.save();a.translate(this.x*f,this.y*f);a.rotate(this.angle);a.translate(-this.x*f,-this.y*f);a.fillStyle=this.fillStyle;a.strokeStyle=this.strokeStyle;a.fillRect((this.x-this.halfWidth)*f,(this.y-this.halfHeight)*f,2*this.halfWidth*f,2*this.halfHeight*f);a.strokeRect((this.x-
this.halfWidth)*f,(this.y-this.halfHeight)*f,2*this.halfWidth*f,2*this.halfHeight*f);a.restore();a.lineWidth=n;c.apply(this,[a,f])}}),scaleShape:c.superCall(function(c){return function(a){this.halfHeight*=a;this.halfWidth*=a;c.apply(this,[a])}}),pointInShape:function(c){return c.x>=this.x-this.halfWidth&&c.x<=this.x+this.halfWidth&&c.y>=this.y-this.halfHeight&&c.y<=this.y+this.halfHeight}})})},"frozen/box2d/joints":function(){define("frozen/box2d/joints",["./joints/Distance","./joints/Prismatic",
"./joints/Revolute"],function(){for(var c=Array.prototype.slice.call(arguments),f={},h=0;h<c.length;h++){var a=c[h],k=a.prototype.declaredClass.replace("frozen/box2d/joints/","");f[k]=a}return f})},"frozen/box2d/joints/Distance":function(){define("frozen/box2d/joints/Distance",["dcl","lodash","./Joint"],function(c,f,h){var a=Box2D.Common.Math.b2Vec2,k=Box2D.Dynamics.Joints.b2DistanceJointDef;return c(h,{declaredClass:"frozen/box2d/joints/Distance",bodyPoint2:null,scaleJointLocation:c.superCall(function(a){return function(c){if(c&&
this.bodyPoint2)this.bodyPoint2.x*=c,this.bodyPoint2.y*=c,this.alreadyScaled=!0;a.apply(this,[c])}}),createB2Joint:function(c){if(c&&c.bodiesMap&&c.b2World&&c.jointsMap&&!c.jointsMap[this.id]){var g=c.bodiesMap[this.bodyId1],b=c.bodiesMap[this.bodyId2];if(g&&b){var d,h;this.bodyPoint1&&(d=new a(this.bodyPoint1.x,this.bodyPoint1.y));this.bodyPoint2&&(h=new a(this.bodyPoint2.x,this.bodyPoint2.y));d=d||g.GetWorldCenter();h=h||b.GetWorldCenter();var e=new k;e.Initialize(g,b,d,h);this.jointAttributes&&
f.assign(e,this.jointAttributes);return c.b2World.CreateJoint(e)}}}})})},"frozen/box2d/joints/Joint":function(){define("frozen/box2d/joints/Joint",["dcl","dcl/bases/Mixer"],function(c,f){return c(f,{declaredClass:"frozen/box2d/joints/Joint",bodyId1:null,bodyId2:null,bodyPoint1:null,jointAttributes:null,scaleJointLocation:function(c){if(c&&this.bodyPoint1)this.bodyPoint1.x*=c,this.bodyPoint1.y*=c,this.alreadyScaled=!0}})})},"frozen/box2d/joints/Prismatic":function(){define("frozen/box2d/joints/Prismatic",
["dcl","lodash","./Joint"],function(c,f,h){var a=Box2D.Common.Math.b2Vec2,k=Box2D.Dynamics.Joints.b2PrismaticJointDef;return c(h,{declaredClass:"frozen/box2d/joints/Prismatic",axisScale:null,createB2Joint:function(c){if(c&&c.bodiesMap&&c.b2World&&c.jointsMap&&!c.jointsMap[this.id]){var g=c.bodiesMap[this.bodyId1],b=c.bodiesMap[this.bodyId2];if(g&&b){var d;this.bodyPoint1&&(d=new a(this.bodyPoint1.x,this.bodyPoint1.y));d=d||g.GetWorldCenter();var h=new k,e;e=this.axisScale?new a(this.axisScale.x,this.axisScale.y):
new a(1,0);h.Initialize(g,b,d,e);this.jointAttributes&&f.assign(h,this.jointAttributes);return c.b2World.CreateJoint(h)}}}})})},"frozen/box2d/joints/Revolute":function(){define("frozen/box2d/joints/Revolute",["dcl","lodash","./Joint"],function(c,f,h){var a=Box2D.Common.Math.b2Vec2,k=Box2D.Dynamics.Joints.b2RevoluteJointDef;return c(h,{declaredClass:"frozen/box2d/joints/Revolute",createB2Joint:function(c){if(c&&c.bodiesMap&&c.b2World&&c.jointsMap&&!c.jointsMap[this.id]){var g=c.bodiesMap[this.bodyId1],
b=c.bodiesMap[this.bodyId2];if(g&&b){var d;this.bodyPoint1&&(d=new a(this.bodyPoint1.x,this.bodyPoint1.y));d=d||g.GetWorldCenter();var h=new k;h.Initialize(g,b,d,void 0);this.jointAttributes&&f.assign(h,this.jointAttributes);return c.b2World.CreateJoint(h)}}}})})},"frozen/plugins/loadImage":function(){define(["../ResourceManager","../utils/parseString"],function(c,f){var h=new c;return{load:function(a,c,n){a=f(a);a=h.loadImage(a);n(a)}}})},"frozen/utils/parseString":function(){define("frozen/utils/parseString",
function(){return function(c){0===c.indexOf("{")&&c.lastIndexOf("}")===c.length-1?c=JSON.parse(c.replace(/,/g,'","').replace(/:(?!\/\/)/g,'":"').replace(/\{/,'{"').replace(/\}/,'"}')):0===c.indexOf("[")&&c.lastIndexOf("]")===c.length-1&&(c=JSON.parse(c.replace(/,/g,'","').replace(/\[/g,'["').replace(/\]/g,'"]')));return c}})},"frozen/plugins/loadSound":function(){define(["../ResourceManager","../utils/parseString"],function(c,f){var h=new c;return{load:function(a,c,n){a=f(a);a=h.loadSound(a);n(a)}}})},
"frozen/reiner/Creature":function(){define("frozen/reiner/Creature",["dcl","../Sprite","../Animation"],function(c,f,h){return c(f,{statics:{EAST:0,NORTH:1,NORTHEAST:2,NORTHWEST:3,SOUTH:4,SOUTHEAST:5,SOUTHWEST:6,WEST:7,STATE_WALKING:0,STATE_DYING:1,STATE_IDLE:2},state:0,walkingAnims:[],dyingAnims:[],idleAnims:[],direction:0,constructor:function(){this.state=this.statics.STATE_IDLE;this.direction=this.statics.EAST},updateDirection:function(a){this.x+=this.dx*a;this.y+=this.dy*a;if(this.state!==this.statics.STATE_DYING){if(0<
this.dx&&0===this.dy)this.direction=this.statics.EAST;else if(0===this.dx&&0>this.dy)this.direction=this.statics.NORTH;else if(0<this.dx&&0>this.dy)this.direction=this.statics.NORTHEAST;else if(0>this.dx&&0>this.dy)this.direction=this.statics.NORTHWEST;else if(0===this.dx&&0<this.dy)this.direction=this.statics.SOUTH;else if(0<this.dx&&0<this.dy)this.direction=this.statics.SOUTHEAST;else if(0>this.dx&&0<this.dy)this.direction=this.statics.SOUTHWEST;else if(0>this.dx&&0===this.dy)this.direction=this.statics.WEST;
this.state=0===this.dx&&0===this.dy?this.statics.STATE_IDLE:this.statics.STATE_WALKING}},updateAnimations:function(a){this.anim=this.state===this.statics.STATE_WALKING?this.walkingAnims[this.direction]:this.state===this.statics.STATE_DYING?this.dyingAnims[this.direction]:this.idleAnims[this.direction];this.anim.update(a)},createAnimations:function(a,c,f,g,b,d){var m=[],e=Array.isArray(c),i=1;d||(d=0);for(var l=0;8>l;l++){m[l]=new h({height:g,width:b,image:f});for(var q=0;q<a;q++)i=e?c[q]:c,m[l].addFrame(i,
q+a*l,d)}return m}})})},"frozen/Sprite":function(){define("frozen/Sprite",["dcl","dcl/bases/Mixer"],function(c,f){var h=c(f,{x:0,y:0,dx:0,dy:0,maxSpeed:0,name:null,collisionRadius:40,update:function(a){this.x+=this.dx*a;this.y+=this.dy*a;this.anim.update(a)},limitSpeed:function(a){return this.maxSpeed?Math.abs(a)>this.maxSpeed?0<a?this.maxSpeed:0>a?this.maxSpeed:0:a:a},getCurrentFrame:function(){if(this.anim)return this.anim.getCurrentFrame()},draw:function(a){this.anim&&this.anim.draw(a,this.x,this.y)},
clone:function(){return new h({anim:this.anim.clone()})}});return h})},"frozen/Animation":function(){define("frozen/Animation",["./AnimFrame","dcl","dcl/bases/Mixer"],function(c,f,h){var a=f(h,{currFrameIndex:0,animTime:0,totalDuration:0,height:64,width:64,image:null,offsetX:0,offsetY:0,constructor:function(){this.start()},createFromSheet:function(c,f,g,b,d,h){g=new a({image:g,height:d,width:b});b=Array.isArray(f);d=1;h||(h=0);for(var e=0;e<c;e++)d=b?f[e]:f,g.addFrame(d,e,h);return g},clone:function(){return new a({image:this.image,
frames:this.frames,totalDuration:this.totalDuration})},addFrame:function(a,f,g){if(!this.frames)this.frames=[];this.totalDuration+=a;this.frames.push(new c({endTime:this.totalDuration,image:this.image,imgSlotX:f,imgSlotY:g}))},start:function(){this.currFrameIndex=this.animTime=0},update:function(a){if(1<this.frames.length){this.animTime+=a;if(this.animTime>=this.totalDuration)this.animTime%=this.totalDuration,this.currFrameIndex=0;for(;this.animTime>this.frames[this.currFrameIndex].endTime;)this.currFrameIndex++}},
getCurrentFrame:function(){return 0===this.frames.length?null:this.frames[this.currFrameIndex]},draw:function(a,c,f){var b=this.getCurrentFrame();a.drawImage(this.image,b.imgSlotX*this.width+this.offsetX,b.imgSlotY*this.height+this.offsetY,this.width,this.height,c,f,this.width,this.height)}});return a})},"frozen/AnimFrame":function(){define("frozen/AnimFrame",["dcl","dcl/bases/Mixer"],function(c,f){return c(f,{endTime:0,imgSlotX:0,imgSlotY:0,image:null})})},"frozen/utils":function(){define("frozen/utils",
"./utils/averagePoints,./utils/degreesToRadians,./utils/radiansToDegrees,./utils/pointInPolygon,./utils/distance,./utils/degreesFromCenter,./utils/radiansFromCenter,./utils/scalePoints,./utils/translatePoints,./utils/insideCanvas".split(","),function(c,f,h,a,k,n,g,b,d,m){return{averagePoints:c,degreesToRadians:f,radiansToDegrees:h,pointInPolygon:a,distance:k,degreesFromCenter:n,radiansFromCenter:g,scalePoints:b,translatePoints:d,insideCanvas:m}})},"frozen/utils/averagePoints":function(){define("frozen/utils/averagePoints",
["lodash"],function(c){return function(f){var h={x:0,y:0};c.forEach(f,function(a){h.x+=a.x;h.y+=a.y});h.x/=f.length;h.y/=f.length;return h}})},"frozen/utils/degreesToRadians":function(){define("frozen/utils/degreesToRadians",function(){var c=Math.PI/180;return function(f){return f*c}})},"frozen/utils/radiansToDegrees":function(){define("frozen/utils/radiansToDegrees",function(){var c=180/Math.PI;return function(f){return f*c}})},"frozen/utils/degreesFromCenter":function(){define("frozen/utils/degreesFromCenter",
["./radiansToDegrees","./radiansFromCenter"],function(c,f){return function(h,a){return c(f(h,a))}})},"frozen/utils/radiansFromCenter":function(){define("frozen/utils/radiansFromCenter",function(){var c={x:0,y:0};return function(f,h){f=f||c;return f.x===h.x&&f.y===h.y?0:f.x===h.x?f.y>h.y?0:Math.PI:f.y===h.y?f.x>h.x?1.5*Math.PI:Math.PI/2:f.x<h.x&&f.y>h.y?Math.atan((h.x-f.x)/(f.y-h.y)):f.x<h.x&&f.y<h.y?Math.PI/2+Math.atan((h.y-f.y)/(h.x-f.x)):f.x>h.x&&f.y<h.y?Math.PI+Math.atan((f.x-h.x)/(h.y-f.y)):1.5*
Math.PI+Math.atan((f.y-h.y)/(f.x-h.x))}})},"dojo/keys":function(){define(["./_base/kernel","./sniff"],function(c,f){return c.keys={BACKSPACE:8,TAB:9,CLEAR:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,META:f("webkit")?91:224,PAUSE:19,CAPS_LOCK:20,ESCAPE:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT_ARROW:37,UP_ARROW:38,RIGHT_ARROW:39,DOWN_ARROW:40,INSERT:45,DELETE:46,HELP:47,LEFT_WINDOW:91,RIGHT_WINDOW:92,SELECT:93,NUMPAD_0:96,NUMPAD_1:97,NUMPAD_2:98,NUMPAD_3:99,NUMPAD_4:100,NUMPAD_5:101,NUMPAD_6:102,
NUMPAD_7:103,NUMPAD_8:104,NUMPAD_9:105,NUMPAD_MULTIPLY:106,NUMPAD_PLUS:107,NUMPAD_ENTER:108,NUMPAD_MINUS:109,NUMPAD_PERIOD:110,NUMPAD_DIVIDE:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,F13:124,F14:125,F15:126,NUM_LOCK:144,SCROLL_LOCK:145,UP_DPAD:175,DOWN_DPAD:176,LEFT_DPAD:177,RIGHT_DPAD:178,copyKey:f("mac")&&!f("air")?f("safari")?91:224:17}})}}});(function(){require({cache:{}});require.boot&&require.apply(null,require.boot)})();