<?php
$skin_settings = array(
	'suf_header_layout_style' => 'in-align',
	'suf_nav_bar_style' => 'align',
	'suf_navt_bar_style' => 'align',
	'suf_date_box_show' => 'hide-search',
	'suf_nav_item_type' => 'tab',
	'suf_navt_item_type' => 'tab',
	'suf_footer_layout_style' => 'in-align',
	'suf_post_meta_position' => 'corners',
	'suf_page_meta_position' => 'corners',
	'suf_post_aside_meta_position' => 'corners',
	'suf_post_gallery_meta_position' => 'corners',
	'suf_post_link_meta_position' => 'corners',
	'suf_post_image_meta_position' => 'corners',
	'suf_post_quote_meta_position' => 'corners',
	'suf_post_status_meta_position' => 'corners',
	'suf_post_video_meta_position' => 'corners',
	'suf_post_audio_meta_position' => 'corners',
	'suf_post_chat_meta_position' => 'corners',
	'suf_comment_label_styles' => 'plain',
	'suf_comment_display_type' => 'plain',
	'suf_featured_show_border' => 'show',
	'suf_iconset' => 'iconset-0',
	'suf_nav_dd_pos' => 'left',
	'suf_navt_dd_pos' => 'left',
	'suf_tile_title_alignment' => 'left',
);
?>