(function(b){"function"===typeof define&&define.amd?define(["jquery","./grid.base"],b):"object"===typeof exports?b(require("jquery")):b(jQuery)})(function(b){var n=b.jgrid,w=n.jqID,l=b.fn.jqGrid,y=function(){var a=b.makeArray(arguments);a[0]="subGrid"+a[0].charAt(0).toUpperCase()+a[0].substring(1);a.unshift("");a.unshift("");a.unshift(this.p);return n.feedback.apply(this,a)},q=function(a,e){return this.each(function(){if(this.grid&&null!=a&&!0===this.p.subGrid){var d=b(this).jqGrid("getInd",a,!0);
b(d).find(">td."+e).trigger("click")}})};n.extend({setSubGrid:function(){return this.each(function(){var a=this.p,e=a.subGridModel[0];a.subGridOptions=b.extend({expandOnLoad:!1,delayOnLoad:50,selectOnExpand:!1,selectOnCollapse:!1,reloadOnExpand:!0},a.subGridOptions||{});a.colNames.unshift("");a.colModel.unshift({name:"subgrid",width:n.cell_width?a.subGridWidth+a.cellLayout:a.subGridWidth,labelClasses:"jqgh_subgrid",sortable:!1,resizable:!1,hidedlg:!0,search:!1,fixed:!0,frozen:!0});if(e)for(e.align=
b.extend([],e.align||[]),a=0;a<e.name.length;a++)e.align[a]=e.align[a]||"left"})},addSubGridCell:function(a,e,d,c){var k=this[0],f=k.p.subGridOptions;d=b.isFunction(f.hasSubgrid)?f.hasSubgrid.call(k,{rowid:d,iRow:e,iCol:a,data:c}):!0;return null==k||null==k.p||null==f?"":"<td role='gridcell' class='"+l.getGuiStyles.call(this,"subgrid.tdStart",d?"ui-sgcollapsed sgcollapsed":"")+"' "+k.formatCol(a,e)+">"+(d?"<div class='"+l.getGuiStyles.call(this,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+
l.getGuiStyles.call(this,"subgrid.button","sgbutton")+"'><span class='"+n.mergeCssClasses(f.commonIconClass,f.plusicon)+"'></span></a></div>":"&nbsp;")+"</td>"},addSubGrid:function(a,e){return this.each(function(){var d=this,c=d.p,k=c.subGridModel[0],f=function(b,c){return l.getGuiStyles.call(d,"subgrid."+b,c||"")},q=f("thSubgrid","ui-th-subgrid ui-th-column ui-th-"+c.direction),z=f("rowSubTable","ui-subtblcell"),C=f("row","ui-subgrid ui-row-"+c.direction),D=f("tdWithIcon","subgrid-cell"),E=f("tdData",
"subgrid-data"),r=function(c,a,d){a=b("<td align='"+k.align[d]+"'></td>").html(a);c.append(a)},A=function(a,d){var g=c.xmlReader.subgrid;b(g.root+" "+g.row,a).each(function(){var c,a,m=b("<tr class='"+z+"'></tr>");if(!0===g.repeatitems)b(g.cell,this).each(function(c){r(m,b(this).text()||"&#160;",c)});else if(c=k.mapping||k.name)for(a=0;a<c.length;a++)r(m,b(c[a],this).text()||"&#160;",a);d.append(m)})},B=function(a,d){var g,t,h,m,e,f=c.jsonReader.subgrid,l=n.getAccessor(a,f.root);if(null!=l)for(t=
0;t<l.length;t++){e=l[t];g=b("<tr class='"+z+"'></tr>");if(!0===f.repeatitems)for(f.cell&&(e=e[f.cell]),h=0;h<e.length;h++)r(g,e[h]||"&#160;",h);else if(m=k.mapping||k.name,m.length)for(h=0;h<m.length;h++)r(g,e[m[h]]||"&#160;",h);d.append(g)}},u=function(a,e,g){var f,h,m=b("<table"+(n.msie&&8>n.msiever()?" cellspacing='0'":"")+"><tbody></tbody></table>"),l=b(m[0].tBodies[0]),p=b("<tr></tr>");for(h=0;h<k.name.length;h++)f=b("<th class='"+q+"'></th>").html(k.name[h]).width(k.width[h]),p.append(f);l.append(p);
g(a,l);b("#"+w(c.id+"_"+e)).append(m);d.grid.hDiv.loading=!1;b("#load_"+w(c.id)).hide();return!1},F=function(a){var e=b(a).attr("id"),g={nd_:(new Date).getTime()},f,h;g[c.prmNames.subgridid]=e;if(!k)return!1;if(k.params)for(h=0;h<k.params.length;h++)f=c.iColByName[k.params[h]],void 0!==f&&(g[c.colModel[f].name]=b(a.cells[f]).text().replace(/\&#160\;/ig,""));if(!d.grid.hDiv.loading)switch(d.grid.hDiv.loading=!0,b("#load_"+w(c.id)).show(),c.subgridtype||(c.subgridtype=c.datatype),b.isFunction(c.subgridtype)?
c.subgridtype.call(d,g):c.subgridtype=c.subgridtype.toLowerCase(),c.subgridtype){case "xml":case "json":b.ajax(b.extend({type:c.mtype,url:b.isFunction(c.subGridUrl)?c.subGridUrl.call(d,g):c.subGridUrl,dataType:c.subgridtype,data:n.serializeFeedback.call(d,c.serializeSubGridData,"jqGridSerializeSubGridData",g),complete:function(a){"xml"===c.subgridtype?u(a.responseXML,e,A):(a=b.parseJSON(a.responseText),u(a,e,B))}},n.ajaxOptions,c.ajaxSubgridOptions||{}))}return!1},f=function(){var e=b(this).parent("tr")[0],
f=e.nextSibling,g=e.id,k=c.id+"_"+g,h=function(a){return n.mergeCssClasses(c.subGridOptions.commonIconClass,c.subGridOptions[a])},m=1;b.each(c.colModel,function(){!0!==this.hidden&&"rn"!==this.name&&"cb"!==this.name||m++});if(b(this).hasClass("sgcollapsed")){if(!0===c.subGridOptions.reloadOnExpand||!1===c.subGridOptions.reloadOnExpand&&!b(f).hasClass("ui-subgrid")){f=1<=a?"<td colspan='"+a+"'>&#160;</td>":"";if(!y.call(d,"beforeExpand",k,g))return;b(e).after("<tr role='row' class='"+C+"'>"+f+"<td class='"+
D+"'><span class='"+h("openicon")+"'></span></td><td colspan='"+parseInt(c.colNames.length-m,10)+"' class='"+E+"'><div id='"+k+"' class='tablediv'></div></td></tr>");b(d).triggerHandler("jqGridSubGridRowExpanded",[k,g]);b.isFunction(c.subGridRowExpanded)?c.subGridRowExpanded.call(d,k,g):F(e)}else b(f).show();b(this).html("<div class='"+l.getGuiStyles.call(d,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+l.getGuiStyles.call(d,"subgrid.button","sgbutton")+"'><span class='"+h("minusicon")+
"'></span></a></div>").removeClass("sgcollapsed").addClass("sgexpanded");c.subGridOptions.selectOnExpand&&b(d).jqGrid("setSelection",g)}else if(b(this).hasClass("sgexpanded")){if(!y.call(d,"beforeCollapse",k,g))return;!0===c.subGridOptions.reloadOnExpand?b(f).remove(".ui-subgrid"):b(f).hasClass("ui-subgrid")&&b(f).hide();b(this).html("<div class='"+l.getGuiStyles.call(d,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+l.getGuiStyles.call(d,"subgrid.button","sgbutton")+"'><span class='"+
h("plusicon")+"'></span></a></div>").removeClass("sgexpanded").addClass("sgcollapsed");c.subGridOptions.selectOnCollapse&&b(d).jqGrid("setSelection",g)}return!1},x,p,v=1;if(d.grid){x=d.rows.length;void 0!==e&&0<e&&(v=e,x=e+1);for(;v<x;)p=d.rows[v],b(p).hasClass("jqgrow")&&(p=b(p.cells[a]),p.hasClass("ui-sgcollapsed")&&(c.scroll&&p.unbind("click"),p.bind("click",f))),v++;!0===c.subGridOptions.expandOnLoad&&b(d.rows).filter(".jqgrow").each(function(a,c){b(c.cells[0]).click()});d.subGridXml=function(a,
b){u(a,b,A)};d.subGridJson=function(a,b){u(a,b,B)}}})},expandSubGridRow:function(a){return q.call(this,a,"sgcollapsed")},collapseSubGridRow:function(a){return q.call(this,a,"sgexpanded")},toggleSubGridRow:function(a){return q.call(this,a,"ui-sgcollapsed")}})});
//# sourceMappingURL=grid.subgrid.map
