author = "Jacob Turner"
github = "https://github.com/SpotTech/CS-Widget"
homepage = "http://www.cancerspot.co/"
description = "CS-Widget is a small widget to redirect to the CancerSpot home page."
mainfile = "widget.js"
